#!/usr/bin/env python3
"""Regenerate Unicode 16.0.0 source-identifier tables with pinned CPython.

Regeneration accepts only CPython 3.14.6 with UCD 16.0.0. This optional tooling
guard does not impose a Python version on pyCircuit builds or users.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import unicodedata

EXPECTED_UNICODE_VERSION = "16.0.0"
EXPECTED_CPYTHON_VERSION = (3, 14, 6)
DEFAULT_OUTPUT = (
    pathlib.Path(__file__).resolve().parents[2]
    / "compiler/lib/Compiler/SourceIdentifierUnicodeData.h"
)


def ranges(values: list[int]) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    for value in values:
        if result and value == result[-1][1] + 1:
            result[-1] = (result[-1][0], value)
        else:
            result.append((value, value))
    return result


def c_array(name: str, type_name: str, values: list[str]) -> list[str]:
    lines = [f"inline constexpr {type_name} {name}[] = {{"]
    for start in range(0, len(values), 3):
        lines.append("    " + ", ".join(values[start : start + 3]) + ",")
    lines.append("};")
    return lines


def generate() -> str:
    if (
        sys.implementation.name != "cpython"
        or sys.version_info[:3] != EXPECTED_CPYTHON_VERSION
    ):
        expected = ".".join(str(part) for part in EXPECTED_CPYTHON_VERSION)
        found_version = ".".join(str(part) for part in sys.version_info[:3])
        found = f"{sys.implementation.name} {found_version}"
        raise RuntimeError(
            f"generator recipe requires CPython {expected}; found {found}"
        )
    if unicodedata.unidata_version != EXPECTED_UNICODE_VERSION:
        raise RuntimeError(
            f"Unicode database mismatch: expected {EXPECTED_UNICODE_VERSION}, "
            f"found {unicodedata.unidata_version} in CPython {sys.version.split()[0]}"
        )

    start_points: list[int] = []
    continue_points: list[int] = []
    decompositions: list[tuple[int, list[int]]] = []
    combining_classes: list[tuple[int, int]] = []
    compositions: list[tuple[int, int, int]] = []
    decomposition_values: list[int] = []

    for codepoint in range(0x110000):
        character = chr(codepoint)
        if character.isidentifier():
            start_points.append(codepoint)
        if ("A" + character).isidentifier():
            continue_points.append(codepoint)

        combining = unicodedata.combining(character)
        if combining:
            combining_classes.append((codepoint, combining))

        mapping = unicodedata.decomposition(character)
        if mapping:
            parts = mapping.split()
            if parts[0].startswith("<"):
                parts = parts[1:]
            values = [int(part, 16) for part in parts]
            offset = len(decomposition_values)
            decomposition_values.extend(values)
            decompositions.append((codepoint, [offset, len(values)]))

            # Canonical two-code-point decompositions compose unless the
            # Unicode database excludes that pair. NFC is the UCD-backed
            # composition-exclusion oracle exposed by the stdlib.
            canonical = unicodedata.decomposition(character).split()
            if (
                len(canonical) == 2
                and not canonical[0].startswith("<")
                and unicodedata.normalize(
                    "NFC", "".join(chr(int(p, 16)) for p in canonical)
                )
                == character
            ):
                compositions.append(
                    (int(canonical[0], 16), int(canonical[1], 16), codepoint)
                )

    start_ranges = ranges(start_points)
    continue_ranges = ranges(continue_points)
    compositions.sort()

    lines = [
        "// Generated by tools/pycircuit/generate_source_identifier_unicode.py.",
        "// Regeneration recipe: CPython 3.14.6 and its UCD 16.0.0 database.",
        "// This generator-only pin does not constrain pyCircuit runtime/build/source Python.",
        "// Unicode 16.0.0 data Copyright (c) 2024 Unicode, Inc.; see SourceIdentifierUnicodeData.LICENSE.txt.",
        "// XID membership is derived from str.isidentifier(); normalization",
        "// properties are derived from unicodedata decomposition/combining/NFC.",
        "// The CPython standard-library LICENSE files are cited in the adjacent notice.",
        "// Unicode UCD 16.0.0 ReadMe: https://www.unicode.org/Public/16.0.0/ucd/ReadMe.txt",
        "// Unicode License v3: https://www.unicode.org/license.txt",
        "// Do not edit by hand; the generator enforces this exact recipe.",
        "#ifndef ACIR_LIB_COMPILER_SOURCEIDENTIFIERUNICODEDATA_H",
        "#define ACIR_LIB_COMPILER_SOURCEIDENTIFIERUNICODEDATA_H",
        "",
        "#include <cstdint>",
        "",
        "namespace acir::compiler::detail::unicode_data {",
        "struct Range { uint32_t first; uint32_t last; };",
        "struct Decomposition { uint32_t codepoint; uint32_t offset; uint8_t length; };",
        "struct CombiningClass { uint32_t codepoint; uint8_t value; };",
        "struct Composition { uint32_t first; uint32_t second; uint32_t result; };",
        "",
    ]
    lines += c_array(
        "xidStartRanges", "Range", [f"{{0x{a:X}, 0x{b:X}}}" for a, b in start_ranges]
    )
    lines.append("")
    lines += c_array(
        "xidContinueRanges",
        "Range",
        [f"{{0x{a:X}, 0x{b:X}}}" for a, b in continue_ranges],
    )
    lines.append("")
    lines += c_array(
        "decompositions",
        "Decomposition",
        [
            f"{{0x{cp:X}, {offset}, {length}}}"
            for cp, (offset, length) in decompositions
        ],
    )
    lines.append("")
    lines += c_array(
        "decompositionValues",
        "uint32_t",
        [f"0x{value:X}" for value in decomposition_values],
    )
    lines.append("")
    lines += c_array(
        "combiningClasses",
        "CombiningClass",
        [f"{{0x{cp:X}, {value}}}" for cp, value in combining_classes],
    )
    lines.append("")
    lines += c_array(
        "compositions",
        "Composition",
        [
            f"{{0x{first:X}, 0x{second:X}, 0x{result:X}}}"
            for first, second, result in compositions
        ],
    )
    lines += [
        "",
        "} // namespace acir::compiler::detail::unicode_data",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    try:
        rendered = generate()
    except RuntimeError as error:
        parser.error(str(error))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="ascii", newline="\n")
    print(f"wrote {args.output} using Unicode {EXPECTED_UNICODE_VERSION}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
