"""Regular-clock known-state checks; original physical-control oracles remain independent."""

from example_issue_queue_2picker.issue_queue_2picker import IssueQueue2Picker
from pycircuit import bits, log, rule, struct, system, table


@struct
class Stimulus:
    in_valid: bits[1]
    in_data: bits[8]
    out0_ready: bits[1]
    out1_ready: bits[1]
    expected_in_ready: bits[1]
    expected_out0_valid: bits[1]
    expected_out0_data: bits[8]
    expected_out1_valid: bits[1]
    expected_out1_data: bits[8]


@struct
class Stimuli:
    rows: table[345, Stimulus]


@rule
def stimulus(phase: bits[16]) -> Stimulus:
    # fmt: off
    stimuli = Stimuli(
        rows=(
            Stimulus(in_valid=1, expected_in_ready=1),
            Stimulus(in_valid=1, in_data=255, expected_in_ready=1, expected_out0_valid=1),
            Stimulus(in_valid=1, in_data=254, expected_in_ready=1, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=128, expected_in_ready=1, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=127, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=170, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=85, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=1, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=2, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=4, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=8, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=16, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=32, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=64, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=255),
            Stimulus(in_valid=1, in_data=128, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=255, expected_out1_valid=1, expected_out1_data=254),
            Stimulus(in_valid=1, in_data=1, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=254, expected_out1_valid=1, expected_out1_data=128),
            Stimulus(in_valid=1, in_data=2, expected_out0_valid=1, expected_out0_data=128, expected_out1_valid=1, expected_out1_data=64),
            Stimulus(in_valid=1, in_data=4, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_valid=1, expected_out1_data=64),
            Stimulus(in_valid=1, in_data=8, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=64, expected_out1_valid=1, expected_out1_data=128),
            Stimulus(in_valid=1, in_data=16, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_valid=1, expected_out1_data=1),
            Stimulus(in_valid=1, in_data=32, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=4),
            Stimulus(in_valid=1, in_data=64, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=4),
            Stimulus(in_valid=1, in_data=128, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=8, expected_out1_valid=1, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=1, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_valid=1, expected_out1_data=64),
            Stimulus(in_valid=1, in_data=2, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_valid=1, expected_out1_data=1),
            Stimulus(in_valid=1, in_data=4, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_valid=1, expected_out1_data=1),
            Stimulus(in_valid=1, in_data=8, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=16, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=4, expected_out1_valid=1, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=32, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=64, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_valid=1, expected_out1_data=32),
            Stimulus(in_valid=1, in_data=128, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=64, expected_out1_data=16),
            Stimulus(in_data=1, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=2, out1_ready=1, expected_in_ready=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=4, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=2, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=8, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=4, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=16, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=8, expected_out1_data=16),
            Stimulus(in_data=32, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=64, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=128, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=64, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=1, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=2, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_data=16),
            Stimulus(in_data=4, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=8, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=16, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=8, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=32, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=64, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_valid=1, expected_out1_data=32),
            Stimulus(in_data=128, out0_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=64, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=1, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=16, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=2, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_data=16),
            Stimulus(in_valid=1, in_data=4, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=8, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_data=16, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=32, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=64, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=128, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_data=2, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=4, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=8, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=16, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=32, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_data=64, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=128, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=1, out1_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=1, expected_out1_valid=1, expected_out1_data=2),
            Stimulus(in_valid=1, in_data=1, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=4, expected_out1_valid=1, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=2, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out1_valid=1, expected_out1_data=1),
            Stimulus(in_valid=1, in_data=3, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=2, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=4, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=3, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=5, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=4, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=6, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=5, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=7, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=6, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=8, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=7, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=9, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=10, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=9, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=11, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=10, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=12, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=11, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=13, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=12, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=14, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=13, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=15, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=14, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=16, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=15, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=17, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=16, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=18, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=17, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=19, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=18, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=20, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=19, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=21, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=20, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=22, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=21, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=23, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=22, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=24, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=23, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=25, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=24, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=26, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=25, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=27, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=26, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=28, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=27, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=29, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=28, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=30, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=29, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=31, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=30, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=32, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=31, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=33, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=32, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=34, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=33, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=35, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=34, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=36, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=35, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=37, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=36, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=38, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=37, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=39, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=38, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=40, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=39, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=41, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=40, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=42, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=41, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=43, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=42, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=44, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=43, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=45, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=44, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=46, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=45, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=47, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=46, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=48, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=47, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=49, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=48, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=50, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=49, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=51, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=50, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=52, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=51, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=53, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=52, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=54, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=53, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=55, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=54, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=56, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=55, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=57, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=56, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=58, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=57, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=59, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=58, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=60, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=59, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=61, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=60, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=62, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=61, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=63, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=62, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=64, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=63, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=65, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=64, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=66, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=65, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=67, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=66, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=68, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=67, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=69, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=68, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=70, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=69, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=71, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=70, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=72, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=71, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=73, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=72, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=74, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=73, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=75, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=74, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=76, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=75, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=77, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=76, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=78, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=77, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=79, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=78, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=80, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=79, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=81, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=80, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=82, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=81, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=83, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=82, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=84, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=83, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=85, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=84, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=86, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=85, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=87, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=86, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=88, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=87, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=89, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=88, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=90, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=89, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=91, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=90, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=92, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=91, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=93, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=92, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=94, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=93, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=95, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=94, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=96, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=95, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=97, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=96, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=98, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=97, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=99, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=98, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=100, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=99, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=101, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=100, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=102, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=101, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=103, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=102, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=104, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=103, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=105, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=104, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=106, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=105, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=107, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=106, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=108, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=107, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=109, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=108, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=110, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=109, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=111, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=110, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=112, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=111, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=113, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=112, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=114, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=113, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=115, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=114, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=116, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=115, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=117, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=116, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=118, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=117, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=119, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=118, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=120, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=119, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=121, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=120, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=122, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=121, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=123, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=122, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=124, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=123, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=125, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=124, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=126, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=125, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=127, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=126, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=128, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=127, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=129, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=128, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=130, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=129, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=131, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=130, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=132, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=131, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=133, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=132, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=134, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=133, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=135, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=134, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=136, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=135, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=137, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=136, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=138, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=137, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=139, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=138, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=140, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=139, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=141, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=140, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=142, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=141, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=143, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=142, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=144, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=143, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=145, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=144, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=146, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=145, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=147, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=146, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=148, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=147, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=149, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=148, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=150, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=149, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=151, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=150, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=152, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=151, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=153, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=152, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=154, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=153, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=155, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=154, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=156, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=155, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=157, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=156, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=158, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=157, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=159, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=158, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=160, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=159, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=161, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=160, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=162, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=161, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=163, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=162, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=164, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=163, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=165, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=164, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=166, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=165, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=167, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=166, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=168, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=167, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=169, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=168, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=170, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=169, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=171, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=170, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=172, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=171, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=173, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=172, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=174, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=173, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=175, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=174, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=176, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=175, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=177, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=176, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=178, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=177, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=179, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=178, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=180, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=179, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=181, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=180, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=182, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=181, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=183, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=182, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=184, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=183, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=185, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=184, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=186, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=185, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=187, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=186, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=188, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=187, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=189, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=188, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=190, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=189, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=191, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=190, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=192, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=191, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=193, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=192, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=194, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=193, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=195, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=194, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=196, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=195, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=197, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=196, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=198, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=197, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=199, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=198, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=200, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=199, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=201, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=200, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=202, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=201, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=203, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=202, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=204, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=203, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=205, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=204, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=206, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=205, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=207, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=206, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=208, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=207, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=209, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=208, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=210, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=209, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=211, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=210, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=212, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=211, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=213, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=212, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=214, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=213, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=215, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=214, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=216, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=215, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=217, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=216, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=218, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=217, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=219, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=218, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=220, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=219, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=221, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=220, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=222, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=221, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=223, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=222, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=224, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=223, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=225, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=224, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=226, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=225, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=227, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=226, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=228, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=227, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=229, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=228, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=230, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=229, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=231, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=230, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=232, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=231, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=233, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=232, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=234, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=233, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=235, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=234, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=236, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=235, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=237, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=236, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=238, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=237, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=239, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=238, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=240, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=239, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=241, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=240, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=242, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=241, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=243, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=242, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=244, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=243, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=245, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=244, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=246, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=245, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=247, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=246, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=248, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=247, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=249, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=248, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=250, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=249, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=251, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=250, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=252, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=251, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=253, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=252, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=254, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=253, expected_out1_data=8),
            Stimulus(in_valid=1, in_data=255, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=254, expected_out1_data=8),
            Stimulus(out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_valid=1, expected_out0_data=255, expected_out1_data=8),
            Stimulus(in_data=1, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=2, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=3, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=4, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=5, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=6, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=7, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=8, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=9, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=10, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=11, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=12, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=13, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=14, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=15, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=16, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=17, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=18, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=19, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=20, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=21, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=22, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(in_data=23, out0_ready=1, out1_ready=1, expected_in_ready=1, expected_out0_data=8, expected_out1_data=8),
            Stimulus(),
        ),
    )
    # fmt: on
    position = phase if phase < 344 else 344
    return stimuli.rows[position]


@rule
def advance(phase):
    if phase < 343:
        phase = phase + 1


@system
def IssueQueue2PickerSystem():  # noqa: N802
    phase: bits[16] = 0
    frame = stimulus(phase)
    dut = IssueQueue2Picker(
        frame.in_valid, frame.in_data, frame.out0_ready, frame.out1_ready
    )

    @rule
    def exercise():
        assert (
            dut.in_ready == frame.expected_in_ready
        ), "issue_queue_2picker in_ready old-state check"
        assert (
            dut.out0_valid == frame.expected_out0_valid
        ), "issue_queue_2picker out0_valid old-state check"
        assert (
            dut.out0_data == frame.expected_out0_data
        ), "issue_queue_2picker out0_data old-state check"
        assert (
            dut.out1_valid == frame.expected_out1_valid
        ), "issue_queue_2picker out1_valid old-state check"
        assert (
            dut.out1_data == frame.expected_out1_data
        ), "issue_queue_2picker out1_data old-state check"
        log("info", "phase", phase)
        log("info", "in_ready", dut.in_ready)
        log("info", "out0_valid", dut.out0_valid)
        log("info", "out0_data", dut.out0_data)
        log("info", "out1_valid", dut.out1_valid)
        log("info", "out1_data", dut.out1_data)

    advance(phase)
    exercise()
