"""Regular-clock record checks; independent physical-control oracles remain intact."""

from example_frontend_composition_pipeline.frontend_composition_pipeline import (
    FrontendCompositionPipeline,
    Header,
    Patch,
    Packet,
    Item,
    Result,
    Opcode,
)
from pycircuit import bits, enum_to_bits, log, rule, struct, system, table


@struct
class Stimulus:
    valid: bits[1]
    take: bits[1]
    input_header_opcode_bits: bits[4]
    input_header_tag: bits[4]
    input_patch_tag: bits[4]
    input_patch_valid: bits[1]
    input_opcode: bits[4]
    input_flags: bits[4]
    input_result_tag: bits[4]
    input_result_valid: bits[1]
    input_result_opcode: bits[4]
    input_onehot_index: bits[2]
    input_onehot_valid: bits[1]
    input_onehot_conflict: bits[1]
    expected_ready: bits[1]
    expected_valid: bits[1]
    expected_header_opcode_bits: bits[4]
    expected_header_tag: bits[4]
    expected_patch_tag: bits[4]
    expected_patch_valid: bits[1]
    expected_opcode: bits[4]
    expected_flags: bits[4]
    expected_result_tag: bits[4]
    expected_result_valid: bits[1]
    expected_result_opcode: bits[4]
    expected_onehot_index: bits[2]
    expected_onehot_valid: bits[1]
    expected_onehot_conflict: bits[1]


@struct
class Stimuli:
    rows: table[185, Stimulus]


@rule
def stimulus(phase: bits[16]) -> Stimulus:
    # fmt: off
    stimuli = Stimuli(
        rows=(
            Stimulus(valid=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_flags=15, input_result_tag=2, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(valid=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=3, input_result_tag=3, input_result_opcode=3, input_onehot_valid=1, expected_ready=1),
            Stimulus(valid=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=9, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_flags=2, input_result_tag=5, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=3, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=9, input_flags=4, input_result_tag=7, input_result_opcode=9, input_onehot_valid=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_flags=5, input_result_tag=8, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=3, input_flags=6, input_result_tag=9, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=9, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_flags=8, input_result_tag=11, input_onehot_valid=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=3, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=9, input_flags=10, input_result_tag=13, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_flags=11, input_result_tag=14, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=3, input_flags=12, input_result_tag=15, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=9, input_flags=13, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_opcode=3, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_flags=14, input_result_tag=1, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_opcode=3, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=3, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_opcode=9, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=9, input_result_tag=3, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_opcode=9, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_flags=1, input_result_tag=4, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=3, input_flags=2, input_result_tag=5, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_opcode=9, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=9, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_flags=4, input_result_tag=7, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=3, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_opcode=3, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=9, input_flags=6, input_result_tag=9, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_flags=7, input_result_tag=10, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=3, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_opcode=3, input_flags=8, input_result_tag=11, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=3, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=9, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_opcode=9, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_flags=10, input_result_tag=13, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_opcode=3, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_opcode=3, input_flags=11, input_result_tag=14, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_opcode=9, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=9, input_flags=12, input_result_tag=15, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_opcode=9, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_flags=13, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_opcode=3, input_flags=14, input_result_tag=1, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_opcode=9, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=9, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_result_tag=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=3, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_opcode=9, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=9, input_flags=2, input_result_tag=5, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_flags=3, input_result_tag=6, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_opcode=3, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=3, input_flags=4, input_result_tag=7, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_opcode=3, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=9, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_opcode=9, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_flags=6, input_result_tag=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_opcode=3, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=3, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=9, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_opcode=9, input_flags=8, input_result_tag=11, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=9, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_flags=9, input_result_tag=12, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=3, input_flags=10, input_result_tag=13, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(valid=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_opcode=9, input_flags=11, input_result_tag=14, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_flags=12, input_result_tag=15, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=3, input_flags=13, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_opcode=3, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_opcode=9, input_flags=14, input_result_tag=1, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_flags=15, input_result_tag=2, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(valid=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=3, input_result_tag=3, input_result_opcode=3, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=9, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_flags=2, input_result_tag=5, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=3, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=9, input_flags=4, input_result_tag=7, input_result_opcode=9, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_flags=5, input_result_tag=8, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=3, input_flags=6, input_result_tag=9, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=9, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_flags=8, input_result_tag=11, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=3, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=9, input_flags=10, input_result_tag=13, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_flags=11, input_result_tag=14, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(input_header_opcode_bits=13, input_patch_tag=3, input_opcode=3, input_flags=12, input_result_tag=15, input_result_opcode=3, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=9, input_flags=13, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_flags=14, input_result_tag=1, input_onehot_index=2, input_onehot_valid=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_flags=15, input_result_tag=2, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=3, input_result_tag=3, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=9, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_flags=2, input_result_tag=5, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_opcode=3, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=3, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_opcode=9, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=9, input_flags=4, input_result_tag=7, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_flags=5, input_result_tag=8, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=4, expected_header_tag=7, expected_patch_tag=10, expected_patch_valid=1, expected_opcode=3, expected_flags=3, expected_result_tag=10, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=3, input_flags=6, input_result_tag=9, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_opcode=9, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=9, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_flags=8, input_result_tag=11, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_opcode=3, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=3, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=8, expected_header_tag=11, expected_patch_tag=14, expected_patch_valid=1, expected_opcode=9, expected_flags=7, expected_result_tag=14, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=9, input_flags=10, input_result_tag=13, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_flags=11, input_result_tag=14, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_opcode=3, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=3, input_flags=12, input_result_tag=15, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_opcode=9, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=9, input_flags=13, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=12, expected_header_tag=15, expected_patch_tag=2, expected_patch_valid=1, expected_flags=11, expected_result_tag=2, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_flags=14, input_result_tag=1, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_opcode=3, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=3, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_opcode=9, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=9, input_result_tag=3, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_flags=1, input_result_tag=4, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_opcode=3, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=3, input_flags=2, input_result_tag=5, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_opcode=9, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=9, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_flags=4, input_result_tag=7, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_opcode=3, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=3, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=4, expected_header_tag=7, expected_patch_tag=10, expected_patch_valid=1, expected_opcode=9, expected_flags=3, expected_result_tag=10, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=9, input_flags=6, input_result_tag=9, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_flags=7, input_result_tag=10, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=3, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_opcode=3, input_flags=8, input_result_tag=11, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_opcode=9, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=9, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=8, expected_header_tag=11, expected_patch_tag=14, expected_patch_valid=1, expected_flags=7, expected_result_tag=14, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_flags=10, input_result_tag=13, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_opcode=3, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_opcode=3, input_flags=11, input_result_tag=14, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_opcode=9, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=9, input_flags=12, input_result_tag=15, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_flags=13, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=12, expected_header_tag=15, expected_patch_tag=2, expected_patch_valid=1, expected_opcode=3, expected_flags=11, expected_result_tag=2, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_opcode=3, input_flags=14, input_result_tag=1, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_opcode=9, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=9, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_result_tag=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=3, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=3, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_opcode=9, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=9, input_flags=2, input_result_tag=5, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_flags=3, input_result_tag=6, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_opcode=3, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=3, input_flags=4, input_result_tag=7, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_opcode=9, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=9, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=4, expected_header_tag=7, expected_patch_tag=10, expected_patch_valid=1, expected_flags=3, expected_result_tag=10, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_flags=6, input_result_tag=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_opcode=3, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=3, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=9, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_opcode=9, input_flags=8, input_result_tag=11, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_flags=9, input_result_tag=12, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=8, expected_header_tag=11, expected_patch_tag=14, expected_patch_valid=1, expected_opcode=3, expected_flags=7, expected_result_tag=14, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=3, input_flags=10, input_result_tag=13, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_opcode=9, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_opcode=9, input_flags=11, input_result_tag=14, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_flags=12, input_result_tag=15, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_opcode=3, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=3, input_flags=13, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=12, expected_header_tag=15, expected_patch_tag=2, expected_patch_valid=1, expected_opcode=9, expected_flags=11, expected_result_tag=2, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_opcode=9, input_flags=14, input_result_tag=1, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_flags=15, input_result_tag=2, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_opcode=3, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=3, input_result_tag=3, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=9, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_flags=2, input_result_tag=5, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_opcode=3, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=3, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_opcode=9, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=9, input_flags=4, input_result_tag=7, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_flags=5, input_result_tag=8, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=4, expected_header_tag=7, expected_patch_tag=10, expected_patch_valid=1, expected_opcode=3, expected_flags=3, expected_result_tag=10, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=3, input_flags=6, input_result_tag=9, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_opcode=9, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=9, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_flags=8, input_result_tag=11, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_opcode=3, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=3, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=8, expected_header_tag=11, expected_patch_tag=14, expected_patch_valid=1, expected_opcode=9, expected_flags=7, expected_result_tag=14, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=9, input_flags=10, input_result_tag=13, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_flags=11, input_result_tag=14, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_opcode=3, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=3, input_flags=12, input_result_tag=15, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_opcode=9, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=9, input_flags=13, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=12, expected_header_tag=15, expected_patch_tag=2, expected_patch_valid=1, expected_flags=11, expected_result_tag=2, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_flags=14, input_result_tag=1, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_opcode=3, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=3, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_opcode=9, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=9, input_result_tag=3, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_flags=1, input_result_tag=4, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_opcode=3, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=3, input_flags=2, input_result_tag=5, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_opcode=9, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=9, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_flags=4, input_result_tag=7, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_opcode=3, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=3, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=4, expected_header_tag=7, expected_patch_tag=10, expected_patch_valid=1, expected_opcode=9, expected_flags=3, expected_result_tag=10, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=9, input_flags=6, input_result_tag=9, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_flags=7, input_result_tag=10, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=3, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_opcode=3, input_flags=8, input_result_tag=11, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_opcode=9, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=9, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=8, expected_header_tag=11, expected_patch_tag=14, expected_patch_valid=1, expected_flags=7, expected_result_tag=14, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_flags=10, input_result_tag=13, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_opcode=3, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_opcode=3, input_flags=11, input_result_tag=14, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_opcode=9, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=9, input_flags=12, input_result_tag=15, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_flags=13, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=12, expected_header_tag=15, expected_patch_tag=2, expected_patch_valid=1, expected_opcode=3, expected_flags=11, expected_result_tag=2, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_opcode=3, input_flags=14, input_result_tag=1, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_opcode=9, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=9, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_result_tag=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=3, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=3, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_tag=3, expected_patch_tag=6, expected_patch_valid=1, expected_opcode=9, expected_flags=15, expected_result_tag=6, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=9, input_flags=2, input_result_tag=5, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=1, expected_header_tag=4, expected_patch_tag=7, expected_result_tag=7, expected_result_opcode=9),
            Stimulus(valid=1, take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_flags=3, input_result_tag=6, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=2, expected_header_tag=5, expected_patch_tag=8, expected_patch_valid=1, expected_opcode=3, expected_flags=1, expected_result_tag=8, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=3, input_flags=4, input_result_tag=7, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=3, expected_header_tag=6, expected_patch_tag=9, expected_opcode=9, expected_flags=2, expected_result_tag=9, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=9, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=4, expected_header_tag=7, expected_patch_tag=10, expected_patch_valid=1, expected_flags=3, expected_result_tag=10, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_flags=6, input_result_tag=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=5, expected_header_tag=8, expected_patch_tag=11, expected_opcode=3, expected_flags=4, expected_result_tag=11, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=3, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=6, expected_header_tag=9, expected_patch_tag=12, expected_patch_valid=1, expected_opcode=9, expected_flags=5, expected_result_tag=12, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_opcode=9, input_flags=8, input_result_tag=11, input_result_opcode=9, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=7, expected_header_tag=10, expected_patch_tag=13, expected_flags=6, expected_result_tag=13, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_flags=9, input_result_tag=12, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=8, expected_header_tag=11, expected_patch_tag=14, expected_patch_valid=1, expected_opcode=3, expected_flags=7, expected_result_tag=14, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=3, input_flags=10, input_result_tag=13, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=9, expected_header_tag=12, expected_patch_tag=15, expected_opcode=9, expected_flags=8, expected_result_tag=15, expected_result_opcode=9, expected_onehot_index=3, expected_onehot_valid=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_opcode=9, input_flags=11, input_result_tag=14, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=10, expected_header_tag=13, expected_patch_valid=1, expected_flags=9, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=13, input_patch_tag=3, input_flags=12, input_result_tag=15, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=11, expected_header_tag=14, expected_patch_tag=1, expected_opcode=3, expected_flags=10, expected_result_tag=1, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=3, input_flags=13, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=12, expected_header_tag=15, expected_patch_tag=2, expected_patch_valid=1, expected_opcode=9, expected_flags=11, expected_result_tag=2, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(valid=1, take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_opcode=9, input_flags=14, input_result_tag=1, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=13, expected_patch_tag=3, expected_flags=12, expected_result_tag=3, expected_result_opcode=9, expected_onehot_index=2, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_flags=15, input_result_tag=2, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=14, expected_header_tag=1, expected_patch_tag=4, expected_patch_valid=1, expected_opcode=3, expected_flags=13, expected_result_tag=4, expected_result_valid=1, expected_result_opcode=9, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=3, input_result_tag=3, input_result_opcode=3, input_onehot_valid=1, expected_ready=1, expected_valid=1, expected_header_opcode_bits=15, expected_header_tag=2, expected_patch_tag=5, expected_opcode=9, expected_flags=14, expected_result_tag=5, expected_result_opcode=9, expected_onehot_index=1, expected_onehot_valid=1, expected_onehot_conflict=1),
            Stimulus(take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_opcode=9, input_flags=1, input_result_tag=4, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_flags=2, input_result_tag=5, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=3, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_opcode=9, input_flags=4, input_result_tag=7, input_result_opcode=9, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_flags=5, input_result_tag=8, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=3, input_flags=6, input_result_tag=9, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=8, input_header_tag=11, input_patch_tag=14, input_patch_valid=1, input_opcode=9, input_flags=7, input_result_tag=10, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=9, input_header_tag=12, input_patch_tag=15, input_flags=8, input_result_tag=11, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=10, input_header_tag=13, input_patch_valid=1, input_opcode=3, input_flags=9, input_result_tag=12, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=11, input_header_tag=14, input_patch_tag=1, input_opcode=9, input_flags=10, input_result_tag=13, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=12, input_header_tag=15, input_patch_tag=2, input_patch_valid=1, input_flags=11, input_result_tag=14, input_result_valid=1, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=13, input_patch_tag=3, input_opcode=3, input_flags=12, input_result_tag=15, input_result_opcode=3, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=14, input_header_tag=1, input_patch_tag=4, input_patch_valid=1, input_opcode=9, input_flags=13, input_result_valid=1, input_result_opcode=9, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=15, input_header_tag=2, input_patch_tag=5, input_flags=14, input_result_tag=1, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_tag=3, input_patch_tag=6, input_patch_valid=1, input_opcode=3, input_flags=15, input_result_tag=2, input_result_valid=1, input_result_opcode=3, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=1, input_header_tag=4, input_patch_tag=7, input_opcode=9, input_result_tag=3, input_result_opcode=9, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=2, input_header_tag=5, input_patch_tag=8, input_patch_valid=1, input_flags=1, input_result_tag=4, input_result_valid=1, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=3, input_header_tag=6, input_patch_tag=9, input_opcode=3, input_flags=2, input_result_tag=5, input_result_opcode=3, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=4, input_header_tag=7, input_patch_tag=10, input_patch_valid=1, input_opcode=9, input_flags=3, input_result_tag=6, input_result_valid=1, input_result_opcode=9, input_onehot_index=3, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=5, input_header_tag=8, input_patch_tag=11, input_flags=4, input_result_tag=7, input_onehot_valid=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=6, input_header_tag=9, input_patch_tag=12, input_patch_valid=1, input_opcode=3, input_flags=5, input_result_tag=8, input_result_valid=1, input_result_opcode=3, input_onehot_index=1, input_onehot_conflict=1, expected_ready=1),
            Stimulus(take=1, input_header_opcode_bits=7, input_header_tag=10, input_patch_tag=13, input_opcode=9, input_flags=6, input_result_tag=9, input_result_opcode=9, input_onehot_index=2, input_onehot_valid=1, expected_ready=1),
            Stimulus(),
        ),
    )
    # fmt: on
    position = phase if phase < 184 else 184
    return stimuli.rows[position]


@rule
def advance(phase):
    if phase < 183:
        phase = phase + 1


@system
def FrontendCompositionPipelineSystem():  # noqa: N802
    phase: bits[16] = 0
    frame = stimulus(phase)
    packet = Item(
        header=Header(
            opcode_bits=frame.input_header_opcode_bits, tag=frame.input_header_tag
        ),
        patch=Patch(tag=frame.input_patch_tag, valid=frame.input_patch_valid),
        opcode=(
            Opcode.NONE
            if frame.input_opcode == 0
            else (Opcode.READ if frame.input_opcode == 3 else Opcode.WRITE)
        ),
        flags=frame.input_flags,
        result_tag=frame.input_result_tag,
        result_valid=frame.input_result_valid,
        result_opcode=(
            Opcode.NONE
            if frame.input_result_opcode == 0
            else (Opcode.READ if frame.input_result_opcode == 3 else Opcode.WRITE)
        ),
        onehot_index=frame.input_onehot_index,
        onehot_valid=frame.input_onehot_valid,
        onehot_conflict=frame.input_onehot_conflict,
    )
    dut = FrontendCompositionPipeline(frame.valid, packet, frame.take)

    @rule
    def check():
        assert (
            dut.ready == frame.expected_ready
        ), "frontend_composition_pipeline input capacity"
        assert (
            dut.valid == frame.expected_valid
        ), "frontend_composition_pipeline result availability"
        assert (
            dut.data.header.opcode_bits == frame.expected_header_opcode_bits
        ), "frontend_composition_pipeline header.opcode_bits old-state check"
        assert (
            dut.data.header.tag == frame.expected_header_tag
        ), "frontend_composition_pipeline header.tag old-state check"
        assert (
            dut.data.patch.tag == frame.expected_patch_tag
        ), "frontend_composition_pipeline patch.tag old-state check"
        assert (
            dut.data.patch.valid == frame.expected_patch_valid
        ), "frontend_composition_pipeline patch.valid old-state check"
        assert (
            enum_to_bits(dut.data.opcode) == frame.expected_opcode
        ), "frontend_composition_pipeline opcode old-state check"
        assert (
            dut.data.flags == frame.expected_flags
        ), "frontend_composition_pipeline flags old-state check"
        assert (
            dut.data.result_tag == frame.expected_result_tag
        ), "frontend_composition_pipeline result_tag old-state check"
        assert (
            dut.data.result_valid == frame.expected_result_valid
        ), "frontend_composition_pipeline result_valid old-state check"
        assert (
            enum_to_bits(dut.data.result_opcode) == frame.expected_result_opcode
        ), "frontend_composition_pipeline result_opcode old-state check"
        assert (
            dut.data.onehot_index == frame.expected_onehot_index
        ), "frontend_composition_pipeline onehot_index old-state check"
        assert (
            dut.data.onehot_valid == frame.expected_onehot_valid
        ), "frontend_composition_pipeline onehot_valid old-state check"
        assert (
            dut.data.onehot_conflict == frame.expected_onehot_conflict
        ), "frontend_composition_pipeline onehot_conflict old-state check"
        log("info", "phase", phase)
        log("info", "ready", dut.ready)
        log("info", "valid", dut.valid)
        log("info", "header_opcode_bits", dut.data.header.opcode_bits)
        log("info", "header_tag", dut.data.header.tag)
        log("info", "patch_tag", dut.data.patch.tag)
        log("info", "patch_valid", dut.data.patch.valid)
        log("info", "opcode", enum_to_bits(dut.data.opcode))
        log("info", "flags", dut.data.flags)
        log("info", "result_tag", dut.data.result_tag)
        log("info", "result_valid", dut.data.result_valid)
        log("info", "result_opcode", enum_to_bits(dut.data.result_opcode))
        log("info", "onehot_index", dut.data.onehot_index)
        log("info", "onehot_valid", dut.data.onehot_valid)
        log("info", "onehot_conflict", dut.data.onehot_conflict)

    advance(phase)
    check()
