"""Regular-clock full known-input stream from the retained loop_control_pipeline oracle."""

from example_loop_control_pipeline.loop_control_pipeline import (
    LoopControlPipeline,
    LoopToken,
)
from pycircuit import bits, log, rule, struct, system, table, u1, u4


@struct
class Scenario:
    valid: u1
    remaining: u4
    stop: u1
    skip: u1
    take: u1
    expected_ready: u1
    expected_valid: u1
    expected_data_remaining: u4
    expected_data_stop: u1
    expected_data_skip: u1


@struct
class Scenarios:
    rows: table[635, Scenario]


@rule
def advance(phase):
    phase = phase + 1


@system
def ExerciseLoopControlPipeline():  # noqa: N802
    phase: bits[64] = 0
    # fmt: off
    scenarios = Scenarios(
        rows=(
            Scenario(expected_ready=1),
            Scenario(valid=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=1, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=1, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=1, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=1, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=2, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=2, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=2, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=2, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=2, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=2, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=3, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=3, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=3, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=3, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=3, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=3, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=4, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=4, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=4, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=4, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=5, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=5, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=5, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=5, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=5, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=5, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=6, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=6, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=6, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=6, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=6, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=6, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=7, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=7, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=7, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=7, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=7, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=7, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=8, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=8, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=8, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=8, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=8, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=8, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=9, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=9, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=9, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=9, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=10, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=10, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=10, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=10, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=10, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=10, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=11, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=11, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=11, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=11, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=11, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=11, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=12, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=12, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=12, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=12, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=12, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=12, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=13, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=13, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=13, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=13, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=13, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=13, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=14, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=14, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=14, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=14, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=14, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=14, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=15, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=15, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=15, stop=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=15, expected_data_stop=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=15, stop=1, skip=1, take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_remaining=15, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=9, stop=1, expected_ready=1),
            Scenario(valid=1, remaining=15, skip=1, expected_ready=1),
            Scenario(valid=1, remaining=4, stop=1, skip=1, expected_ready=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=7, stop=1, expected_ready=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=2, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=3, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=4, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=5, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=6, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=7, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=8, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=9, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=10, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=11, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=12, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=13, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=14, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=15, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=2, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=3, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, stop=1, take=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=2, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, remaining=3, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=7, expected_data_stop=1),
            Scenario(valid=1, remaining=4, take=1),
            Scenario(valid=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=1, stop=1, take=1),
            Scenario(valid=1, remaining=2, skip=1, take=1),
            Scenario(valid=1, remaining=3, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=4, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=3, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=1, skip=1, take=1),
            Scenario(valid=1, remaining=2, stop=1, take=1),
            Scenario(valid=1, remaining=3, skip=1, take=1),
            Scenario(valid=1, remaining=4, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, remaining=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=2, skip=1, take=1),
            Scenario(valid=1, remaining=3, stop=1, take=1),
            Scenario(valid=1, remaining=4, skip=1, take=1),
            Scenario(valid=1, take=1),
            Scenario(valid=1, remaining=1, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=2, take=1, expected_ready=1, expected_valid=1, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, remaining=3, skip=1, take=1),
            Scenario(valid=1, remaining=4, stop=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=1, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, remaining=1, take=1),
            Scenario(valid=1, remaining=2, stop=1, skip=1, take=1),
            Scenario(valid=1, remaining=3, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=4, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1),
            Scenario(valid=1, stop=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=1, skip=1, take=1),
            Scenario(valid=1, remaining=2, take=1),
            Scenario(valid=1, remaining=3, stop=1, skip=1, take=1),
            Scenario(valid=1, remaining=4, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, skip=1, take=1),
            Scenario(valid=1, remaining=1, stop=1, take=1),
            Scenario(valid=1, remaining=2, skip=1, take=1),
            Scenario(valid=1, remaining=3, take=1),
            Scenario(valid=1, remaining=4, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, take=1, expected_ready=1, expected_valid=1, expected_data_stop=1),
            Scenario(valid=1, remaining=1, skip=1, take=1),
            Scenario(valid=1, remaining=2, stop=1, take=1),
            Scenario(valid=1, remaining=3, skip=1, take=1),
            Scenario(valid=1, remaining=4, take=1),
            Scenario(valid=1, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, remaining=2, skip=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=3, stop=1, take=1, expected_ready=1, expected_valid=1, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, remaining=4, skip=1, take=1),
            Scenario(valid=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=1, stop=1, skip=1, take=1),
            Scenario(valid=1, remaining=2, take=1),
            Scenario(valid=1, remaining=3, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=4, stop=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=3, expected_data_stop=1),
            Scenario(valid=1, skip=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=1, take=1),
            Scenario(valid=1, remaining=2, stop=1, skip=1, take=1),
            Scenario(valid=1, remaining=3, take=1),
            Scenario(valid=1, remaining=4, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, stop=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1),
            Scenario(valid=1, remaining=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=2, take=1),
            Scenario(valid=1, remaining=3, stop=1, skip=1, take=1),
            Scenario(valid=1, remaining=4, take=1),
            Scenario(valid=1, skip=1, take=1),
            Scenario(valid=1, remaining=1, stop=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=2, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_stop=1),
            Scenario(valid=1, remaining=3, take=1),
            Scenario(valid=1, remaining=4, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=1, expected_data_stop=1),
            Scenario(valid=1, remaining=1, skip=1, take=1),
            Scenario(valid=1, remaining=2, stop=1, take=1),
            Scenario(valid=1, remaining=3, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(valid=1, remaining=4, take=1, expected_ready=1, expected_valid=1, expected_data_remaining=4, expected_data_stop=1, expected_data_skip=1),
            Scenario(valid=1, stop=1, skip=1, take=1, expected_ready=1, expected_valid=1),
            Scenario(valid=1, remaining=1, take=1),
            Scenario(valid=1, remaining=2, skip=1, take=1),
            Scenario(valid=1, remaining=3, stop=1, take=1),
            Scenario(valid=1, remaining=4, skip=1, take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1),
            Scenario(take=1),
            Scenario(take=1),
            Scenario(take=1),
            Scenario(take=1, expected_ready=1, expected_valid=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_stop=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1, expected_valid=1, expected_data_skip=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(take=1, expected_ready=1),
            Scenario(valid=1, remaining=9, stop=1, expected_ready=1),
            Scenario(valid=1, remaining=15, skip=1, expected_ready=1),
            Scenario(valid=1, remaining=4, stop=1, skip=1, expected_ready=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, remaining=7, stop=1, expected_ready=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(valid=1, take=1, expected_valid=1, expected_data_remaining=9, expected_data_stop=1),
            Scenario(take=1),
            Scenario(take=1),
            Scenario(take=1),
            Scenario(take=1),
            Scenario(take=1),
        )
    )
    # fmt: on
    position = phase if phase < 635 else 634
    scenario = scenarios.rows[position]
    payload = LoopToken(
        remaining=scenario.remaining, stop=scenario.stop, skip=scenario.skip
    )
    dut = LoopControlPipeline(scenario.valid, payload, scenario.take)

    @rule
    def check():
        if phase < 635:
            assert dut.ready == scenario.expected_ready, "loop_control_pipeline: ready"
            assert dut.valid == scenario.expected_valid, "loop_control_pipeline: valid"
            assert (
                dut.data.remaining == scenario.expected_data_remaining
            ), "loop_control_pipeline: data.remaining"
            assert (
                dut.data.stop == scenario.expected_data_stop
            ), "loop_control_pipeline: data.stop"
            assert (
                dut.data.skip == scenario.expected_data_skip
            ), "loop_control_pipeline: data.skip"
        log("info", "loop_control_pipeline.ready", dut.ready)
        log("info", "loop_control_pipeline.valid", dut.valid)
        log("info", "loop_control_pipeline.data.remaining", dut.data.remaining)
        log("info", "loop_control_pipeline.data.stop", dut.data.stop)
        log("info", "loop_control_pipeline.data.skip", dut.data.skip)

    check()
    advance(phase)
