"""Regular-clock known-state checks; original physical-control oracles remain independent."""

from example_inferred_boundary_pipeline.inferred_boundary_pipeline import (
    InferredBoundaryPipeline,
)
from pycircuit import bits, log, rule, struct, system, table


@struct
class Stimulus:
    valid: bits[1]
    data: bits[8]
    take: bits[1]
    expected_ready: bits[1]
    expected_valid: bits[1]
    expected_data: bits[8]


@struct
class Stimuli:
    rows: table[345, Stimulus]


@rule
def stimulus(phase: bits[16]) -> Stimulus:
    # fmt: off
    stimuli = Stimuli(
        rows=(
            Stimulus(valid=1, expected_ready=1),
            Stimulus(valid=1, data=255, expected_ready=1),
            Stimulus(valid=1, data=254, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=128, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=127, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=170, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=85, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=1, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=2, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=4, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=8, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=16, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=32, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=64, take=1, expected_ready=1, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=128, take=1, expected_ready=1, expected_valid=1),
            Stimulus(valid=1, data=1, take=1, expected_ready=1, expected_valid=1, expected_data=65),
            Stimulus(valid=1, data=2, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=4, take=1, expected_ready=1, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=8, take=1, expected_ready=1, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=16, take=1, expected_ready=1, expected_valid=1, expected_data=5),
            Stimulus(valid=1, data=32, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=64, take=1, expected_ready=1, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=128, take=1, expected_ready=1, expected_valid=1, expected_data=17),
            Stimulus(valid=1, data=1, take=1, expected_ready=1, expected_valid=1, expected_data=65),
            Stimulus(valid=1, data=2, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=4, take=1, expected_ready=1, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=8, take=1, expected_ready=1, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=16, take=1, expected_ready=1, expected_valid=1, expected_data=5),
            Stimulus(valid=1, data=32, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=64, take=1, expected_ready=1, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=128, take=1, expected_ready=1, expected_valid=1, expected_data=17),
            Stimulus(data=1, take=1, expected_ready=1, expected_valid=1, expected_data=65),
            Stimulus(valid=1, data=2, expected_ready=1, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=4, take=1, expected_ready=1, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=8, take=1, expected_ready=1, expected_valid=1, expected_data=3),
            Stimulus(valid=1, data=16, take=1, expected_ready=1, expected_valid=1, expected_data=5),
            Stimulus(data=32, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=64, take=1, expected_ready=1, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=128, take=1, expected_ready=1, expected_valid=1, expected_data=17),
            Stimulus(valid=1, data=1, take=1, expected_ready=1, expected_valid=1, expected_data=65),
            Stimulus(valid=1, data=2, expected_valid=1, expected_data=129),
            Stimulus(data=4, take=1, expected_ready=1, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=8, take=1, expected_ready=1, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=16, take=1, expected_ready=1),
            Stimulus(valid=1, data=32, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=64, take=1, expected_ready=1, expected_valid=1, expected_data=9),
            Stimulus(data=128, take=1, expected_ready=1, expected_valid=1, expected_data=17),
            Stimulus(valid=1, data=1, take=1, expected_ready=1, expected_valid=1, expected_data=65),
            Stimulus(valid=1, data=2, expected_ready=1),
            Stimulus(valid=1, data=4, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=8, expected_valid=1, expected_data=2),
            Stimulus(data=16, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=32, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=64, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=128, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=1, expected_valid=1, expected_data=2),
            Stimulus(data=2, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=4, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=8, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=16, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=32, expected_valid=1, expected_data=2),
            Stimulus(data=64, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=128, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=1, expected_valid=1, expected_data=2),
            Stimulus(valid=1, take=1, expected_ready=1, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=1, take=1, expected_ready=1, expected_valid=1, expected_data=3),
            Stimulus(valid=1, data=2, take=1, expected_ready=1, expected_valid=1, expected_data=1),
            Stimulus(valid=1, data=3, take=1, expected_ready=1, expected_valid=1, expected_data=2),
            Stimulus(valid=1, data=4, take=1, expected_ready=1, expected_valid=1, expected_data=3),
            Stimulus(valid=1, data=5, take=1, expected_ready=1, expected_valid=1, expected_data=4),
            Stimulus(valid=1, data=6, take=1, expected_ready=1, expected_valid=1, expected_data=5),
            Stimulus(valid=1, data=7, take=1, expected_ready=1, expected_valid=1, expected_data=6),
            Stimulus(valid=1, data=8, take=1, expected_ready=1, expected_valid=1, expected_data=7),
            Stimulus(valid=1, data=9, take=1, expected_ready=1, expected_valid=1, expected_data=8),
            Stimulus(valid=1, data=10, take=1, expected_ready=1, expected_valid=1, expected_data=9),
            Stimulus(valid=1, data=11, take=1, expected_ready=1, expected_valid=1, expected_data=10),
            Stimulus(valid=1, data=12, take=1, expected_ready=1, expected_valid=1, expected_data=11),
            Stimulus(valid=1, data=13, take=1, expected_ready=1, expected_valid=1, expected_data=12),
            Stimulus(valid=1, data=14, take=1, expected_ready=1, expected_valid=1, expected_data=13),
            Stimulus(valid=1, data=15, take=1, expected_ready=1, expected_valid=1, expected_data=14),
            Stimulus(valid=1, data=16, take=1, expected_ready=1, expected_valid=1, expected_data=15),
            Stimulus(valid=1, data=17, take=1, expected_ready=1, expected_valid=1, expected_data=16),
            Stimulus(valid=1, data=18, take=1, expected_ready=1, expected_valid=1, expected_data=17),
            Stimulus(valid=1, data=19, take=1, expected_ready=1, expected_valid=1, expected_data=18),
            Stimulus(valid=1, data=20, take=1, expected_ready=1, expected_valid=1, expected_data=19),
            Stimulus(valid=1, data=21, take=1, expected_ready=1, expected_valid=1, expected_data=20),
            Stimulus(valid=1, data=22, take=1, expected_ready=1, expected_valid=1, expected_data=21),
            Stimulus(valid=1, data=23, take=1, expected_ready=1, expected_valid=1, expected_data=22),
            Stimulus(valid=1, data=24, take=1, expected_ready=1, expected_valid=1, expected_data=23),
            Stimulus(valid=1, data=25, take=1, expected_ready=1, expected_valid=1, expected_data=24),
            Stimulus(valid=1, data=26, take=1, expected_ready=1, expected_valid=1, expected_data=25),
            Stimulus(valid=1, data=27, take=1, expected_ready=1, expected_valid=1, expected_data=26),
            Stimulus(valid=1, data=28, take=1, expected_ready=1, expected_valid=1, expected_data=27),
            Stimulus(valid=1, data=29, take=1, expected_ready=1, expected_valid=1, expected_data=28),
            Stimulus(valid=1, data=30, take=1, expected_ready=1, expected_valid=1, expected_data=29),
            Stimulus(valid=1, data=31, take=1, expected_ready=1, expected_valid=1, expected_data=30),
            Stimulus(valid=1, data=32, take=1, expected_ready=1, expected_valid=1, expected_data=31),
            Stimulus(valid=1, data=33, take=1, expected_ready=1, expected_valid=1, expected_data=32),
            Stimulus(valid=1, data=34, take=1, expected_ready=1, expected_valid=1, expected_data=33),
            Stimulus(valid=1, data=35, take=1, expected_ready=1, expected_valid=1, expected_data=34),
            Stimulus(valid=1, data=36, take=1, expected_ready=1, expected_valid=1, expected_data=35),
            Stimulus(valid=1, data=37, take=1, expected_ready=1, expected_valid=1, expected_data=36),
            Stimulus(valid=1, data=38, take=1, expected_ready=1, expected_valid=1, expected_data=37),
            Stimulus(valid=1, data=39, take=1, expected_ready=1, expected_valid=1, expected_data=38),
            Stimulus(valid=1, data=40, take=1, expected_ready=1, expected_valid=1, expected_data=39),
            Stimulus(valid=1, data=41, take=1, expected_ready=1, expected_valid=1, expected_data=40),
            Stimulus(valid=1, data=42, take=1, expected_ready=1, expected_valid=1, expected_data=41),
            Stimulus(valid=1, data=43, take=1, expected_ready=1, expected_valid=1, expected_data=42),
            Stimulus(valid=1, data=44, take=1, expected_ready=1, expected_valid=1, expected_data=43),
            Stimulus(valid=1, data=45, take=1, expected_ready=1, expected_valid=1, expected_data=44),
            Stimulus(valid=1, data=46, take=1, expected_ready=1, expected_valid=1, expected_data=45),
            Stimulus(valid=1, data=47, take=1, expected_ready=1, expected_valid=1, expected_data=46),
            Stimulus(valid=1, data=48, take=1, expected_ready=1, expected_valid=1, expected_data=47),
            Stimulus(valid=1, data=49, take=1, expected_ready=1, expected_valid=1, expected_data=48),
            Stimulus(valid=1, data=50, take=1, expected_ready=1, expected_valid=1, expected_data=49),
            Stimulus(valid=1, data=51, take=1, expected_ready=1, expected_valid=1, expected_data=50),
            Stimulus(valid=1, data=52, take=1, expected_ready=1, expected_valid=1, expected_data=51),
            Stimulus(valid=1, data=53, take=1, expected_ready=1, expected_valid=1, expected_data=52),
            Stimulus(valid=1, data=54, take=1, expected_ready=1, expected_valid=1, expected_data=53),
            Stimulus(valid=1, data=55, take=1, expected_ready=1, expected_valid=1, expected_data=54),
            Stimulus(valid=1, data=56, take=1, expected_ready=1, expected_valid=1, expected_data=55),
            Stimulus(valid=1, data=57, take=1, expected_ready=1, expected_valid=1, expected_data=56),
            Stimulus(valid=1, data=58, take=1, expected_ready=1, expected_valid=1, expected_data=57),
            Stimulus(valid=1, data=59, take=1, expected_ready=1, expected_valid=1, expected_data=58),
            Stimulus(valid=1, data=60, take=1, expected_ready=1, expected_valid=1, expected_data=59),
            Stimulus(valid=1, data=61, take=1, expected_ready=1, expected_valid=1, expected_data=60),
            Stimulus(valid=1, data=62, take=1, expected_ready=1, expected_valid=1, expected_data=61),
            Stimulus(valid=1, data=63, take=1, expected_ready=1, expected_valid=1, expected_data=62),
            Stimulus(valid=1, data=64, take=1, expected_ready=1, expected_valid=1, expected_data=63),
            Stimulus(valid=1, data=65, take=1, expected_ready=1, expected_valid=1, expected_data=64),
            Stimulus(valid=1, data=66, take=1, expected_ready=1, expected_valid=1, expected_data=65),
            Stimulus(valid=1, data=67, take=1, expected_ready=1, expected_valid=1, expected_data=66),
            Stimulus(valid=1, data=68, take=1, expected_ready=1, expected_valid=1, expected_data=67),
            Stimulus(valid=1, data=69, take=1, expected_ready=1, expected_valid=1, expected_data=68),
            Stimulus(valid=1, data=70, take=1, expected_ready=1, expected_valid=1, expected_data=69),
            Stimulus(valid=1, data=71, take=1, expected_ready=1, expected_valid=1, expected_data=70),
            Stimulus(valid=1, data=72, take=1, expected_ready=1, expected_valid=1, expected_data=71),
            Stimulus(valid=1, data=73, take=1, expected_ready=1, expected_valid=1, expected_data=72),
            Stimulus(valid=1, data=74, take=1, expected_ready=1, expected_valid=1, expected_data=73),
            Stimulus(valid=1, data=75, take=1, expected_ready=1, expected_valid=1, expected_data=74),
            Stimulus(valid=1, data=76, take=1, expected_ready=1, expected_valid=1, expected_data=75),
            Stimulus(valid=1, data=77, take=1, expected_ready=1, expected_valid=1, expected_data=76),
            Stimulus(valid=1, data=78, take=1, expected_ready=1, expected_valid=1, expected_data=77),
            Stimulus(valid=1, data=79, take=1, expected_ready=1, expected_valid=1, expected_data=78),
            Stimulus(valid=1, data=80, take=1, expected_ready=1, expected_valid=1, expected_data=79),
            Stimulus(valid=1, data=81, take=1, expected_ready=1, expected_valid=1, expected_data=80),
            Stimulus(valid=1, data=82, take=1, expected_ready=1, expected_valid=1, expected_data=81),
            Stimulus(valid=1, data=83, take=1, expected_ready=1, expected_valid=1, expected_data=82),
            Stimulus(valid=1, data=84, take=1, expected_ready=1, expected_valid=1, expected_data=83),
            Stimulus(valid=1, data=85, take=1, expected_ready=1, expected_valid=1, expected_data=84),
            Stimulus(valid=1, data=86, take=1, expected_ready=1, expected_valid=1, expected_data=85),
            Stimulus(valid=1, data=87, take=1, expected_ready=1, expected_valid=1, expected_data=86),
            Stimulus(valid=1, data=88, take=1, expected_ready=1, expected_valid=1, expected_data=87),
            Stimulus(valid=1, data=89, take=1, expected_ready=1, expected_valid=1, expected_data=88),
            Stimulus(valid=1, data=90, take=1, expected_ready=1, expected_valid=1, expected_data=89),
            Stimulus(valid=1, data=91, take=1, expected_ready=1, expected_valid=1, expected_data=90),
            Stimulus(valid=1, data=92, take=1, expected_ready=1, expected_valid=1, expected_data=91),
            Stimulus(valid=1, data=93, take=1, expected_ready=1, expected_valid=1, expected_data=92),
            Stimulus(valid=1, data=94, take=1, expected_ready=1, expected_valid=1, expected_data=93),
            Stimulus(valid=1, data=95, take=1, expected_ready=1, expected_valid=1, expected_data=94),
            Stimulus(valid=1, data=96, take=1, expected_ready=1, expected_valid=1, expected_data=95),
            Stimulus(valid=1, data=97, take=1, expected_ready=1, expected_valid=1, expected_data=96),
            Stimulus(valid=1, data=98, take=1, expected_ready=1, expected_valid=1, expected_data=97),
            Stimulus(valid=1, data=99, take=1, expected_ready=1, expected_valid=1, expected_data=98),
            Stimulus(valid=1, data=100, take=1, expected_ready=1, expected_valid=1, expected_data=99),
            Stimulus(valid=1, data=101, take=1, expected_ready=1, expected_valid=1, expected_data=100),
            Stimulus(valid=1, data=102, take=1, expected_ready=1, expected_valid=1, expected_data=101),
            Stimulus(valid=1, data=103, take=1, expected_ready=1, expected_valid=1, expected_data=102),
            Stimulus(valid=1, data=104, take=1, expected_ready=1, expected_valid=1, expected_data=103),
            Stimulus(valid=1, data=105, take=1, expected_ready=1, expected_valid=1, expected_data=104),
            Stimulus(valid=1, data=106, take=1, expected_ready=1, expected_valid=1, expected_data=105),
            Stimulus(valid=1, data=107, take=1, expected_ready=1, expected_valid=1, expected_data=106),
            Stimulus(valid=1, data=108, take=1, expected_ready=1, expected_valid=1, expected_data=107),
            Stimulus(valid=1, data=109, take=1, expected_ready=1, expected_valid=1, expected_data=108),
            Stimulus(valid=1, data=110, take=1, expected_ready=1, expected_valid=1, expected_data=109),
            Stimulus(valid=1, data=111, take=1, expected_ready=1, expected_valid=1, expected_data=110),
            Stimulus(valid=1, data=112, take=1, expected_ready=1, expected_valid=1, expected_data=111),
            Stimulus(valid=1, data=113, take=1, expected_ready=1, expected_valid=1, expected_data=112),
            Stimulus(valid=1, data=114, take=1, expected_ready=1, expected_valid=1, expected_data=113),
            Stimulus(valid=1, data=115, take=1, expected_ready=1, expected_valid=1, expected_data=114),
            Stimulus(valid=1, data=116, take=1, expected_ready=1, expected_valid=1, expected_data=115),
            Stimulus(valid=1, data=117, take=1, expected_ready=1, expected_valid=1, expected_data=116),
            Stimulus(valid=1, data=118, take=1, expected_ready=1, expected_valid=1, expected_data=117),
            Stimulus(valid=1, data=119, take=1, expected_ready=1, expected_valid=1, expected_data=118),
            Stimulus(valid=1, data=120, take=1, expected_ready=1, expected_valid=1, expected_data=119),
            Stimulus(valid=1, data=121, take=1, expected_ready=1, expected_valid=1, expected_data=120),
            Stimulus(valid=1, data=122, take=1, expected_ready=1, expected_valid=1, expected_data=121),
            Stimulus(valid=1, data=123, take=1, expected_ready=1, expected_valid=1, expected_data=122),
            Stimulus(valid=1, data=124, take=1, expected_ready=1, expected_valid=1, expected_data=123),
            Stimulus(valid=1, data=125, take=1, expected_ready=1, expected_valid=1, expected_data=124),
            Stimulus(valid=1, data=126, take=1, expected_ready=1, expected_valid=1, expected_data=125),
            Stimulus(valid=1, data=127, take=1, expected_ready=1, expected_valid=1, expected_data=126),
            Stimulus(valid=1, data=128, take=1, expected_ready=1, expected_valid=1, expected_data=127),
            Stimulus(valid=1, data=129, take=1, expected_ready=1, expected_valid=1, expected_data=128),
            Stimulus(valid=1, data=130, take=1, expected_ready=1, expected_valid=1, expected_data=129),
            Stimulus(valid=1, data=131, take=1, expected_ready=1, expected_valid=1, expected_data=130),
            Stimulus(valid=1, data=132, take=1, expected_ready=1, expected_valid=1, expected_data=131),
            Stimulus(valid=1, data=133, take=1, expected_ready=1, expected_valid=1, expected_data=132),
            Stimulus(valid=1, data=134, take=1, expected_ready=1, expected_valid=1, expected_data=133),
            Stimulus(valid=1, data=135, take=1, expected_ready=1, expected_valid=1, expected_data=134),
            Stimulus(valid=1, data=136, take=1, expected_ready=1, expected_valid=1, expected_data=135),
            Stimulus(valid=1, data=137, take=1, expected_ready=1, expected_valid=1, expected_data=136),
            Stimulus(valid=1, data=138, take=1, expected_ready=1, expected_valid=1, expected_data=137),
            Stimulus(valid=1, data=139, take=1, expected_ready=1, expected_valid=1, expected_data=138),
            Stimulus(valid=1, data=140, take=1, expected_ready=1, expected_valid=1, expected_data=139),
            Stimulus(valid=1, data=141, take=1, expected_ready=1, expected_valid=1, expected_data=140),
            Stimulus(valid=1, data=142, take=1, expected_ready=1, expected_valid=1, expected_data=141),
            Stimulus(valid=1, data=143, take=1, expected_ready=1, expected_valid=1, expected_data=142),
            Stimulus(valid=1, data=144, take=1, expected_ready=1, expected_valid=1, expected_data=143),
            Stimulus(valid=1, data=145, take=1, expected_ready=1, expected_valid=1, expected_data=144),
            Stimulus(valid=1, data=146, take=1, expected_ready=1, expected_valid=1, expected_data=145),
            Stimulus(valid=1, data=147, take=1, expected_ready=1, expected_valid=1, expected_data=146),
            Stimulus(valid=1, data=148, take=1, expected_ready=1, expected_valid=1, expected_data=147),
            Stimulus(valid=1, data=149, take=1, expected_ready=1, expected_valid=1, expected_data=148),
            Stimulus(valid=1, data=150, take=1, expected_ready=1, expected_valid=1, expected_data=149),
            Stimulus(valid=1, data=151, take=1, expected_ready=1, expected_valid=1, expected_data=150),
            Stimulus(valid=1, data=152, take=1, expected_ready=1, expected_valid=1, expected_data=151),
            Stimulus(valid=1, data=153, take=1, expected_ready=1, expected_valid=1, expected_data=152),
            Stimulus(valid=1, data=154, take=1, expected_ready=1, expected_valid=1, expected_data=153),
            Stimulus(valid=1, data=155, take=1, expected_ready=1, expected_valid=1, expected_data=154),
            Stimulus(valid=1, data=156, take=1, expected_ready=1, expected_valid=1, expected_data=155),
            Stimulus(valid=1, data=157, take=1, expected_ready=1, expected_valid=1, expected_data=156),
            Stimulus(valid=1, data=158, take=1, expected_ready=1, expected_valid=1, expected_data=157),
            Stimulus(valid=1, data=159, take=1, expected_ready=1, expected_valid=1, expected_data=158),
            Stimulus(valid=1, data=160, take=1, expected_ready=1, expected_valid=1, expected_data=159),
            Stimulus(valid=1, data=161, take=1, expected_ready=1, expected_valid=1, expected_data=160),
            Stimulus(valid=1, data=162, take=1, expected_ready=1, expected_valid=1, expected_data=161),
            Stimulus(valid=1, data=163, take=1, expected_ready=1, expected_valid=1, expected_data=162),
            Stimulus(valid=1, data=164, take=1, expected_ready=1, expected_valid=1, expected_data=163),
            Stimulus(valid=1, data=165, take=1, expected_ready=1, expected_valid=1, expected_data=164),
            Stimulus(valid=1, data=166, take=1, expected_ready=1, expected_valid=1, expected_data=165),
            Stimulus(valid=1, data=167, take=1, expected_ready=1, expected_valid=1, expected_data=166),
            Stimulus(valid=1, data=168, take=1, expected_ready=1, expected_valid=1, expected_data=167),
            Stimulus(valid=1, data=169, take=1, expected_ready=1, expected_valid=1, expected_data=168),
            Stimulus(valid=1, data=170, take=1, expected_ready=1, expected_valid=1, expected_data=169),
            Stimulus(valid=1, data=171, take=1, expected_ready=1, expected_valid=1, expected_data=170),
            Stimulus(valid=1, data=172, take=1, expected_ready=1, expected_valid=1, expected_data=171),
            Stimulus(valid=1, data=173, take=1, expected_ready=1, expected_valid=1, expected_data=172),
            Stimulus(valid=1, data=174, take=1, expected_ready=1, expected_valid=1, expected_data=173),
            Stimulus(valid=1, data=175, take=1, expected_ready=1, expected_valid=1, expected_data=174),
            Stimulus(valid=1, data=176, take=1, expected_ready=1, expected_valid=1, expected_data=175),
            Stimulus(valid=1, data=177, take=1, expected_ready=1, expected_valid=1, expected_data=176),
            Stimulus(valid=1, data=178, take=1, expected_ready=1, expected_valid=1, expected_data=177),
            Stimulus(valid=1, data=179, take=1, expected_ready=1, expected_valid=1, expected_data=178),
            Stimulus(valid=1, data=180, take=1, expected_ready=1, expected_valid=1, expected_data=179),
            Stimulus(valid=1, data=181, take=1, expected_ready=1, expected_valid=1, expected_data=180),
            Stimulus(valid=1, data=182, take=1, expected_ready=1, expected_valid=1, expected_data=181),
            Stimulus(valid=1, data=183, take=1, expected_ready=1, expected_valid=1, expected_data=182),
            Stimulus(valid=1, data=184, take=1, expected_ready=1, expected_valid=1, expected_data=183),
            Stimulus(valid=1, data=185, take=1, expected_ready=1, expected_valid=1, expected_data=184),
            Stimulus(valid=1, data=186, take=1, expected_ready=1, expected_valid=1, expected_data=185),
            Stimulus(valid=1, data=187, take=1, expected_ready=1, expected_valid=1, expected_data=186),
            Stimulus(valid=1, data=188, take=1, expected_ready=1, expected_valid=1, expected_data=187),
            Stimulus(valid=1, data=189, take=1, expected_ready=1, expected_valid=1, expected_data=188),
            Stimulus(valid=1, data=190, take=1, expected_ready=1, expected_valid=1, expected_data=189),
            Stimulus(valid=1, data=191, take=1, expected_ready=1, expected_valid=1, expected_data=190),
            Stimulus(valid=1, data=192, take=1, expected_ready=1, expected_valid=1, expected_data=191),
            Stimulus(valid=1, data=193, take=1, expected_ready=1, expected_valid=1, expected_data=192),
            Stimulus(valid=1, data=194, take=1, expected_ready=1, expected_valid=1, expected_data=193),
            Stimulus(valid=1, data=195, take=1, expected_ready=1, expected_valid=1, expected_data=194),
            Stimulus(valid=1, data=196, take=1, expected_ready=1, expected_valid=1, expected_data=195),
            Stimulus(valid=1, data=197, take=1, expected_ready=1, expected_valid=1, expected_data=196),
            Stimulus(valid=1, data=198, take=1, expected_ready=1, expected_valid=1, expected_data=197),
            Stimulus(valid=1, data=199, take=1, expected_ready=1, expected_valid=1, expected_data=198),
            Stimulus(valid=1, data=200, take=1, expected_ready=1, expected_valid=1, expected_data=199),
            Stimulus(valid=1, data=201, take=1, expected_ready=1, expected_valid=1, expected_data=200),
            Stimulus(valid=1, data=202, take=1, expected_ready=1, expected_valid=1, expected_data=201),
            Stimulus(valid=1, data=203, take=1, expected_ready=1, expected_valid=1, expected_data=202),
            Stimulus(valid=1, data=204, take=1, expected_ready=1, expected_valid=1, expected_data=203),
            Stimulus(valid=1, data=205, take=1, expected_ready=1, expected_valid=1, expected_data=204),
            Stimulus(valid=1, data=206, take=1, expected_ready=1, expected_valid=1, expected_data=205),
            Stimulus(valid=1, data=207, take=1, expected_ready=1, expected_valid=1, expected_data=206),
            Stimulus(valid=1, data=208, take=1, expected_ready=1, expected_valid=1, expected_data=207),
            Stimulus(valid=1, data=209, take=1, expected_ready=1, expected_valid=1, expected_data=208),
            Stimulus(valid=1, data=210, take=1, expected_ready=1, expected_valid=1, expected_data=209),
            Stimulus(valid=1, data=211, take=1, expected_ready=1, expected_valid=1, expected_data=210),
            Stimulus(valid=1, data=212, take=1, expected_ready=1, expected_valid=1, expected_data=211),
            Stimulus(valid=1, data=213, take=1, expected_ready=1, expected_valid=1, expected_data=212),
            Stimulus(valid=1, data=214, take=1, expected_ready=1, expected_valid=1, expected_data=213),
            Stimulus(valid=1, data=215, take=1, expected_ready=1, expected_valid=1, expected_data=214),
            Stimulus(valid=1, data=216, take=1, expected_ready=1, expected_valid=1, expected_data=215),
            Stimulus(valid=1, data=217, take=1, expected_ready=1, expected_valid=1, expected_data=216),
            Stimulus(valid=1, data=218, take=1, expected_ready=1, expected_valid=1, expected_data=217),
            Stimulus(valid=1, data=219, take=1, expected_ready=1, expected_valid=1, expected_data=218),
            Stimulus(valid=1, data=220, take=1, expected_ready=1, expected_valid=1, expected_data=219),
            Stimulus(valid=1, data=221, take=1, expected_ready=1, expected_valid=1, expected_data=220),
            Stimulus(valid=1, data=222, take=1, expected_ready=1, expected_valid=1, expected_data=221),
            Stimulus(valid=1, data=223, take=1, expected_ready=1, expected_valid=1, expected_data=222),
            Stimulus(valid=1, data=224, take=1, expected_ready=1, expected_valid=1, expected_data=223),
            Stimulus(valid=1, data=225, take=1, expected_ready=1, expected_valid=1, expected_data=224),
            Stimulus(valid=1, data=226, take=1, expected_ready=1, expected_valid=1, expected_data=225),
            Stimulus(valid=1, data=227, take=1, expected_ready=1, expected_valid=1, expected_data=226),
            Stimulus(valid=1, data=228, take=1, expected_ready=1, expected_valid=1, expected_data=227),
            Stimulus(valid=1, data=229, take=1, expected_ready=1, expected_valid=1, expected_data=228),
            Stimulus(valid=1, data=230, take=1, expected_ready=1, expected_valid=1, expected_data=229),
            Stimulus(valid=1, data=231, take=1, expected_ready=1, expected_valid=1, expected_data=230),
            Stimulus(valid=1, data=232, take=1, expected_ready=1, expected_valid=1, expected_data=231),
            Stimulus(valid=1, data=233, take=1, expected_ready=1, expected_valid=1, expected_data=232),
            Stimulus(valid=1, data=234, take=1, expected_ready=1, expected_valid=1, expected_data=233),
            Stimulus(valid=1, data=235, take=1, expected_ready=1, expected_valid=1, expected_data=234),
            Stimulus(valid=1, data=236, take=1, expected_ready=1, expected_valid=1, expected_data=235),
            Stimulus(valid=1, data=237, take=1, expected_ready=1, expected_valid=1, expected_data=236),
            Stimulus(valid=1, data=238, take=1, expected_ready=1, expected_valid=1, expected_data=237),
            Stimulus(valid=1, data=239, take=1, expected_ready=1, expected_valid=1, expected_data=238),
            Stimulus(valid=1, data=240, take=1, expected_ready=1, expected_valid=1, expected_data=239),
            Stimulus(valid=1, data=241, take=1, expected_ready=1, expected_valid=1, expected_data=240),
            Stimulus(valid=1, data=242, take=1, expected_ready=1, expected_valid=1, expected_data=241),
            Stimulus(valid=1, data=243, take=1, expected_ready=1, expected_valid=1, expected_data=242),
            Stimulus(valid=1, data=244, take=1, expected_ready=1, expected_valid=1, expected_data=243),
            Stimulus(valid=1, data=245, take=1, expected_ready=1, expected_valid=1, expected_data=244),
            Stimulus(valid=1, data=246, take=1, expected_ready=1, expected_valid=1, expected_data=245),
            Stimulus(valid=1, data=247, take=1, expected_ready=1, expected_valid=1, expected_data=246),
            Stimulus(valid=1, data=248, take=1, expected_ready=1, expected_valid=1, expected_data=247),
            Stimulus(valid=1, data=249, take=1, expected_ready=1, expected_valid=1, expected_data=248),
            Stimulus(valid=1, data=250, take=1, expected_ready=1, expected_valid=1, expected_data=249),
            Stimulus(valid=1, data=251, take=1, expected_ready=1, expected_valid=1, expected_data=250),
            Stimulus(valid=1, data=252, take=1, expected_ready=1, expected_valid=1, expected_data=251),
            Stimulus(valid=1, data=253, take=1, expected_ready=1, expected_valid=1, expected_data=252),
            Stimulus(valid=1, data=254, take=1, expected_ready=1, expected_valid=1, expected_data=253),
            Stimulus(valid=1, data=255, take=1, expected_ready=1, expected_valid=1, expected_data=254),
            Stimulus(take=1, expected_ready=1, expected_valid=1, expected_data=255),
            Stimulus(data=1, take=1, expected_ready=1, expected_valid=1),
            Stimulus(data=2, take=1, expected_ready=1),
            Stimulus(data=3, take=1, expected_ready=1),
            Stimulus(data=4, take=1, expected_ready=1),
            Stimulus(data=5, take=1, expected_ready=1),
            Stimulus(data=6, take=1, expected_ready=1),
            Stimulus(data=7, take=1, expected_ready=1),
            Stimulus(data=8, take=1, expected_ready=1),
            Stimulus(data=9, take=1, expected_ready=1),
            Stimulus(data=10, take=1, expected_ready=1),
            Stimulus(data=11, take=1, expected_ready=1),
            Stimulus(data=12, take=1, expected_ready=1),
            Stimulus(data=13, take=1, expected_ready=1),
            Stimulus(data=14, take=1, expected_ready=1),
            Stimulus(data=15, take=1, expected_ready=1),
            Stimulus(data=16, take=1, expected_ready=1),
            Stimulus(data=17, take=1, expected_ready=1),
            Stimulus(data=18, take=1, expected_ready=1),
            Stimulus(data=19, take=1, expected_ready=1),
            Stimulus(data=20, take=1, expected_ready=1),
            Stimulus(data=21, take=1, expected_ready=1),
            Stimulus(data=22, take=1, expected_ready=1),
            Stimulus(data=23, take=1, expected_ready=1),
            Stimulus(),
        ),
    )
    # fmt: on
    position = phase if phase < 344 else 344
    return stimuli.rows[position]


@rule
def advance(phase):
    if phase < 343:
        phase = phase + 1


@system
def InferredBoundaryPipelineSystem():  # noqa: N802
    phase: bits[16] = 0
    frame = stimulus(phase)
    dut = InferredBoundaryPipeline(frame.valid, frame.data, frame.take)

    @rule
    def exercise():
        assert (
            dut.ready == frame.expected_ready
        ), "inferred_boundary_pipeline ready old-state check"
        assert (
            dut.valid == frame.expected_valid
        ), "inferred_boundary_pipeline valid old-state check"
        assert (
            dut.data == frame.expected_data
        ), "inferred_boundary_pipeline data old-state check"
        log("info", "phase", phase)
        log("info", "ready", dut.ready)
        log("info", "valid", dut.valid)
        log("info", "data", dut.data)

    advance(phase)
    exercise()
