// Native common-IR family fixture; no source-level collection admission claim.
#w1 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<1>}, origin = {site = {definition = @execution.collections.Top, ast_path = [{kind = "index", value = 0 : i64}]}, expansion = []}, location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
#w2 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<2>}, origin = {site = {definition = @execution.collections.Top, ast_path = [{kind = "index", value = 0 : i64}]}, expansion = []}, location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
#w3 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<3>}, origin = {site = {definition = @execution.collections.Top, ast_path = [{kind = "index", value = 0 : i64}]}, expansion = []}, location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
!b1 = !ac.bits<#w1>
!controls = !ac.table<[#w2, #w3], !b1>
!result = !ac.struct<"execution.collections.Flag">
!results = !ac.table<[#w2, #w3], !result>
module {
  ac.struct "execution.collections.Flag" fields [{name = "value", type = !b1}] {ac.source_owner = {package = "execution", path = "collections.py"}}
  "ac.module"() ({
  ^bb0(%condition: !b1, %clk: !b1, %rst: !b1):
    %one = "ac.bits.constant"() {value = #w1} : () -> !b1
    %output = ac.struct.create(%condition) : (!b1) -> !result
    %check:2 = "ac.rule"(%condition, %one) ({
    ^bb0(%c: !b1, %p: !b1):
      "ac.yield"(%c, %p) : (!b1, !b1) -> ()
    }) {name = "inspect", occurrence = {site = {definition = @execution.collections.Child, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, ac.required_checks = [{id = {registration = {site = {definition = @execution.collections.Child, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, check = {site = {definition = @execution.collections.Child, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = []}, obligation = 0 : i64}, kind = "assert", location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}]} : (!b1, !b1) -> (!b1, !b1)
    "ac.expect"(%check#0, %check#1) {kind = "assert", location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, ac.check_id = {registration = {site = {definition = @execution.collections.Child, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, check = {site = {definition = @execution.collections.Child, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = []}, obligation = 0 : i64}, ac.message = "family"} : (!b1, !b1) -> ()
    "ac.yield"(%output) : (!result) -> ()
  }) {sym_name = "execution.collections.Child", source_owner = {package = "execution", path = "collections.py"}, parameters = [], type_parameters = [], input_names = ["condition", "pyc_clk", "pyc_rst"], output_names = ["result"], function_type = (!b1, !b1, !b1) -> !result, ac.return_form = "single", ac.parameters = [{name = "condition", binding = "positional_or_keyword", default = {present = false}, constraint = {kind = "hardware", type = !b1, source_kind = "fixed_bits"}, origin = {site = {definition = @execution.collections.Child, ast_path = [{kind = "index", value = 1 : i64}]}, expansion = []}, location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}], ac.result_constraints = [{kind = "hardware", type = !result, source_kind = "nominal"}], ac.domain_inputs = {clock = 1 : i64, reset = 2 : i64}} : () -> ()
  "ac.module"() ({
  ^bb0(%condition: !b1):
    %one = "ac.bits.constant"() {value = #w1} : () -> !b1
    %check:4 = "ac.rule"(%condition, %one) ({
    ^bb0(%c: !b1, %p: !b1):
      "ac.yield"(%c, %p, %c, %p) : (!b1, !b1, !b1, !b1) -> ()
    }) {name = "inspect", occurrence = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, ac.required_checks = [{id = {registration = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, check = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = [{kind = "iteration", site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 19 : i64}]}, ordinal = 4 : i32, value = {kind = "integer", value = #ac.math_int<-170141183460469231731687303715884105733>}}]}, obligation = 3 : i64}, kind = "assert", location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}, {id = {registration = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, check = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = [{kind = "iteration", site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 19 : i64}]}, ordinal = 4 : i32, value = {kind = "integer", value = #ac.math_int<-170141183460469231731687303715884105733>}}]}, obligation = 11 : i64}, kind = "assert", location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}]} : (!b1, !b1) -> (!b1, !b1, !b1, !b1)
    "ac.expect"(%check#0, %check#1) {kind = "assert", location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, ac.check_id = {registration = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, check = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = [{kind = "iteration", site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 19 : i64}]}, ordinal = 4 : i32, value = {kind = "integer", value = #ac.math_int<-170141183460469231731687303715884105733>}}]}, obligation = 3 : i64}, ac.message = "quote\22 backslash\5C newline\0A nul\00 tail"} : (!b1, !b1) -> ()
    "ac.expect"(%check#2, %check#3) {kind = "assert", location = {path = "collections.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, ac.check_id = {registration = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 7 : i64}]}, expansion = []}, check = {site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = [{kind = "iteration", site = {definition = @execution.collections.Ordinary, ast_path = [{kind = "index", value = 19 : i64}]}, ordinal = 4 : i32, value = {kind = "integer", value = #ac.math_int<-170141183460469231731687303715884105733>}}]}, obligation = 11 : i64}, ac.message = "ordinary 11"} : (!b1, !b1) -> ()
    "ac.yield"(%condition) : (!b1) -> ()
  }) {sym_name = "execution.collections.Ordinary", source_owner = {package = "execution", path = "collections.py"}, parameters = [], type_parameters = [], input_names = ["condition"], output_names = ["value"], function_type = (!b1) -> !b1} : () -> ()
  "ac.module"() ({
  ^bb0(%conditions: !controls, %clocks: !controls, %resets: !controls, %ordinary: !b1):
    %cells = "ac.collection"(%conditions, %clocks, %resets) {callee = @execution.collections.Child, instance_name = "cells", parameters = [], type_arguments = [], shape = [#w2, #w3], occurrence = {site = {definition = @execution.collections.Top, ast_path = [{kind = "index", value = 11 : i64}]}, expansion = []}} : (!controls, !controls, !controls) -> !results
    %tail = "ac.instance"(%ordinary) {callee = @execution.collections.Ordinary, instance_name = "tail", parameters = [], type_arguments = [], occurrence = {site = {definition = @execution.collections.Top, ast_path = [{kind = "index", value = 27 : i64}]}, expansion = []}} : (!b1) -> !b1
    "ac.yield"(%cells, %tail) : (!results, !b1) -> ()
  }) {sym_name = "execution.collections.Top", source_owner = {package = "execution", path = "collections.py"}, parameters = [], type_parameters = [], input_names = ["conditions", "clocks", "resets", "ordinary"], output_names = ["cells", "tail"], function_type = (!controls, !controls, !controls, !b1) -> (!results, !b1)} : () -> ()
  "ac.system"() {entry = {callee = @execution.collections.Top, parameters = [], type_arguments = []}, domain = "default"} : () -> ()
}
