// Direct verified common IR: no Python collection/leaf-source admission claim.
#w7 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<7>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
#w0 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<0>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
#w1 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<1>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
!b1 = !ac.bits<#w1>
#w2 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<2>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
!b2 = !ac.bits<#w2>
#w3 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<3>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
!b3 = !ac.bits<#w3>
#w4 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<4>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
!b4 = !ac.bits<#w4>
#w8 = #ac.static_expr<{kind = "literal", value = {kind = "integer", value = #ac.math_int<8>}, origin = {site = {definition = @execution.leaves.Top, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>
!b8 = !ac.bits<#w8>
module {
  "ac.module.import"() {sym_name = "native.dff", source_owner = {package = "gfsim", path = "dff.py"}, parameters = [], type_parameters = ["T"], input_names = ["clk", "rst", "d", "init"], output_names = ["q"], primitive_kind = "dff", dependency_summary = [{output = {port = 0 : i64, path = []}, inputs = []}], function_type = (!b1, !b1, !ac.type_param<@native.dff, "T">, !ac.type_param<@native.dff, "T">) -> (!ac.type_param<@native.dff, "T">)} : () -> ()
  "ac.module.import"() {sym_name = "native.dffe", source_owner = {package = "gfsim", path = "dffe.py"}, parameters = [], type_parameters = ["T"], input_names = ["clk", "rst", "en", "d", "init"], output_names = ["q"], primitive_kind = "dffe", dependency_summary = [{output = {port = 0 : i64, path = []}, inputs = []}], function_type = (!b1, !b1, !b1, !ac.type_param<@native.dffe, "T">, !ac.type_param<@native.dffe, "T">) -> (!ac.type_param<@native.dffe, "T">)} : () -> ()
  "ac.module.import"() {sym_name = "native.byte_mem", source_owner = {package = "gfsim", path = "byte_mem.py"}, parameters = [{name = "ADDR_WIDTH", type = !ac.math_int}, {name = "DEPTH", type = !ac.math_int}], type_parameters = ["T"], input_names = ["clk", "rst", "raddr", "wvalid", "waddr", "wdata", "wstrb"], output_names = ["rdata"], primitive_kind = "byte_mem", dependency_summary = [{output = {port = 0 : i64, path = []}, inputs = [{port = 2 : i64, path = []}]}], function_type = (!b1, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.byte_mem, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.byte_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.byte_mem, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.byte_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !ac.type_param<@native.byte_mem, "T">, !ac.bits<#ac.static_expr<{kind = "binary", operator = "floordiv", lhs = #ac.static_expr<{kind = "type_width", type = !ac.type_param<@native.byte_mem, "T">, origin = {site = {definition = @native.byte_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>, rhs = #w8, origin = {site = {definition = @native.byte_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>) -> (!ac.type_param<@native.byte_mem, "T">)} : () -> ()
  "ac.module.import"() {sym_name = "native.sync_mem", source_owner = {package = "gfsim", path = "sync_mem.py"}, parameters = [{name = "ADDR_WIDTH", type = !ac.math_int}, {name = "DEPTH", type = !ac.math_int}], type_parameters = ["T"], input_names = ["clk", "rst", "ren", "raddr", "wvalid", "waddr", "wdata", "wstrb"], output_names = ["rdata"], primitive_kind = "sync_mem", dependency_summary = [{output = {port = 0 : i64, path = []}, inputs = []}], function_type = (!b1, !b1, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.sync_mem, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.sync_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.sync_mem, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.sync_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !ac.type_param<@native.sync_mem, "T">, !ac.bits<#ac.static_expr<{kind = "binary", operator = "floordiv", lhs = #ac.static_expr<{kind = "binary", operator = "add", lhs = #ac.static_expr<{kind = "type_width", type = !ac.type_param<@native.sync_mem, "T">, origin = {site = {definition = @native.sync_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>, rhs = #w7, origin = {site = {definition = @native.sync_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>, rhs = #w8, origin = {site = {definition = @native.sync_mem, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>) -> (!ac.type_param<@native.sync_mem, "T">)} : () -> ()
  "ac.module.import"() {sym_name = "native.sync_mem_dp", source_owner = {package = "gfsim", path = "sync_mem_dp.py"}, parameters = [{name = "ADDR_WIDTH", type = !ac.math_int}, {name = "DEPTH", type = !ac.math_int}], type_parameters = ["T"], input_names = ["clk", "rst", "ren0", "raddr0", "ren1", "raddr1", "wvalid", "waddr", "wdata", "wstrb"], output_names = ["rdata0", "rdata1"], primitive_kind = "sync_mem_dp", dependency_summary = [{output = {port = 0 : i64, path = []}, inputs = []}, {output = {port = 1 : i64, path = []}, inputs = []}], function_type = (!b1, !b1, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.sync_mem_dp, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.sync_mem_dp, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.sync_mem_dp, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.sync_mem_dp, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !b1, !ac.bits<#ac.static_expr<{kind = "reference", ref = {kind = "parameter", owner = @native.sync_mem_dp, name = "ADDR_WIDTH"}, origin = {site = {definition = @native.sync_mem_dp, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>, !ac.type_param<@native.sync_mem_dp, "T">, !ac.bits<#ac.static_expr<{kind = "binary", operator = "floordiv", lhs = #ac.static_expr<{kind = "binary", operator = "add", lhs = #ac.static_expr<{kind = "type_width", type = !ac.type_param<@native.sync_mem_dp, "T">, origin = {site = {definition = @native.sync_mem_dp, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>, rhs = #w7, origin = {site = {definition = @native.sync_mem_dp, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>, rhs = #w8, origin = {site = {definition = @native.sync_mem_dp, ast_path = []}, expansion = []}, location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}>>) -> (!ac.type_param<@native.sync_mem_dp, "T">, !ac.type_param<@native.sync_mem_dp, "T">)} : () -> ()
  "ac.module"() ({
  ^bb0(%clk: !b1, %rst: !b1, %en: !b1, %ren: !b1, %write: !b1, %push: !b1, %take: !b1, %condition: !b1, %path: !b1, %data: !b8, %read_addr: !b2, %write_addr: !b2, %strobe: !b1):
    %zero = "ac.bits.constant"() {value = #w0} : () -> !b8
    %qdff = "ac.instance"(%clk, %rst, %data, %zero) {callee = @native.dff, instance_name = "dff", parameters = [], type_arguments = [!b8], occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 10 : i64}]}, expansion = []}} : (!b1, !b1, !b8, !b8) -> (!b8)
    %qdffe = "ac.instance"(%clk, %rst, %en, %data, %zero) {callee = @native.dffe, instance_name = "dffe", parameters = [], type_arguments = [!b8], occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 11 : i64}]}, expansion = []}} : (!b1, !b1, !b1, !b8, !b8) -> (!b8)
    %qbyte = "ac.instance"(%clk, %rst, %read_addr, %write, %write_addr, %data, %strobe) {callee = @native.byte_mem, instance_name = "byte_mem", parameters = [#w2, #w4], type_arguments = [!b8], occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 12 : i64}]}, expansion = []}} : (!b1, !b1, !b2, !b1, !b2, !b8, !b1) -> (!b8)
    %qsync = "ac.instance"(%clk, %rst, %ren, %read_addr, %write, %write_addr, %data, %strobe) {callee = @native.sync_mem, instance_name = "sync_mem", parameters = [#w2, #w4], type_arguments = [!b8], occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 13 : i64}]}, expansion = []}} : (!b1, !b1, !b1, !b2, !b1, !b2, !b8, !b1) -> (!b8)
    %qdp0:2 = "ac.instance"(%clk, %rst, %ren, %read_addr, %ren, %read_addr, %write, %write_addr, %data, %strobe) {callee = @native.sync_mem_dp, instance_name = "sync_mem_dp", parameters = [#w2, #w4], type_arguments = [!b8], occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 14 : i64}]}, expansion = []}} : (!b1, !b1, !b1, !b2, !b1, !b2, !b1, !b2, !b8, !b1) -> (!b8, !b8)
    %fifo:3 = "ac.queue"(%clk, %rst, %push, %data, %take) {instance_name = "fifo", depth = #w2, ready_policy = "downstream_pop", availability_latency = #w1, head_read_latency = #w0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 21 : i64}]}, expansion = []}} : (!b1, !b1, !b1, !b8, !b1) -> (!b1, !b1, !b8)
    %delay:3 = "ac.queue"(%clk, %rst, %push, %data, %take) {instance_name = "delay", depth = #w2, ready_policy = "downstream_pop", availability_latency = #w3, head_read_latency = #w0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 23 : i64}]}, expansion = []}} : (!b1, !b1, !b1, !b8, !b1) -> (!b1, !b1, !b8)
    %check:2 = "ac.rule"(%condition, %path) ({
    ^bb0(%c: !b1, %p: !b1):
      "ac.yield"(%c, %p) : (!b1, !b1) -> ()
    }) {name = "inspect", occurrence = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 40 : i64}]}, expansion = []}, ac.required_checks = [{id = {registration = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 40 : i64}]}, expansion = []}, check = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 41 : i64}]}, expansion = []}, obligation = 0 : i64}, kind = "assert", location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}}]} : (!b1, !b1) -> (!b1, !b1)
    "ac.expect"(%check#0, %check#1) {kind = "assert", location = {path = "leaves.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, ac.check_id = {registration = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 40 : i64}]}, expansion = []}, check = {site = {definition = @execution.leaves.Top, ast_path = [{kind = "index", value = 41 : i64}]}, expansion = []}, obligation = 0 : i64}, ac.message = "all-leaf barrier"} : (!b1, !b1) -> ()
    "ac.yield"(%qdff, %qdffe, %qbyte, %qsync, %qdp0#0, %qdp0#1, %fifo#0, %fifo#1, %fifo#2, %delay#0, %delay#1, %delay#2) : (!b8, !b8, !b8, !b8, !b8, !b8, !b1, !b1, !b8, !b1, !b1, !b8) -> ()
  }) {sym_name = "execution.leaves.Top", source_owner = {package = "execution", path = "leaves.py"}, parameters = [], type_parameters = [], input_names = ["clk", "rst", "en", "ren", "write", "push", "take", "condition", "path", "data", "read_addr", "write_addr", "strobe"], output_names = ["qdff", "qdffe", "qbyte", "qsync", "qdp0", "qdp1", "ready", "available", "head", "delayed_ready", "delayed_available", "delayed_head"], function_type = (!b1, !b1, !b1, !b1, !b1, !b1, !b1, !b1, !b1, !b8, !b2, !b2, !b1) -> (!b8, !b8, !b8, !b8, !b8, !b8, !b1, !b1, !b8, !b1, !b1, !b8)} : () -> ()
  "ac.system"() {entry = {callee = @execution.leaves.Top, parameters = [], type_arguments = []}, domain = "default"} : () -> ()
}
