"""Regular-clock known-state checks; original physical-control oracles remain independent."""

from example_fifo_loopback.fifo_loopback import FifoLoopback
from pycircuit import bits, log, rule, struct, system, table


@struct
class Stimulus:
    in_valid: bits[1]
    in_data: bits[8]
    out_ready: bits[1]
    expected_in_ready: bits[1]
    expected_out_valid: bits[1]
    expected_out_data: bits[8]


@struct
class Stimuli:
    rows: table[345, Stimulus]


@rule
def stimulus(phase: bits[16]) -> Stimulus:
    # fmt: off
    stimuli = Stimuli(
        rows=(
            Stimulus(in_valid=1, expected_in_ready=1),
            Stimulus(in_valid=1, in_data=255, expected_in_ready=1, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=254, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=128, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=127, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=170, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=85, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=1, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=2, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=4, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=8, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=16, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=32, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=64, out_ready=1, expected_in_ready=1, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=128, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=255),
            Stimulus(in_valid=1, in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=64),
            Stimulus(in_valid=1, in_data=2, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=4, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=8, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=16, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=4),
            Stimulus(in_valid=1, in_data=32, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=64, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=128, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=16),
            Stimulus(in_valid=1, in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=64),
            Stimulus(in_valid=1, in_data=2, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=4, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=8, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=16, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=4),
            Stimulus(in_valid=1, in_data=32, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=64, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=128, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=16),
            Stimulus(in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=64),
            Stimulus(in_valid=1, in_data=2, expected_in_ready=1, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=4, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=8, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=2),
            Stimulus(in_valid=1, in_data=16, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=4),
            Stimulus(in_data=32, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=64, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=128, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=16),
            Stimulus(in_valid=1, in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=64),
            Stimulus(in_valid=1, in_data=2, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_data=4, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=8, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=16, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=32, expected_in_ready=1, expected_out_valid=1, expected_out_data=16),
            Stimulus(in_valid=1, in_data=64, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=16),
            Stimulus(in_data=128, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=32),
            Stimulus(in_valid=1, in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=64),
            Stimulus(in_valid=1, in_data=2, expected_in_ready=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=4, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=8, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_data=16, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=32, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=64, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=128, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_data=2, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=4, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=8, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=16, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=32, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_data=64, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=128, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=2),
            Stimulus(in_valid=1, in_data=2, out_ready=1, expected_in_ready=1, expected_out_valid=1),
            Stimulus(in_valid=1, in_data=3, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=1),
            Stimulus(in_valid=1, in_data=4, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=2),
            Stimulus(in_valid=1, in_data=5, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=3),
            Stimulus(in_valid=1, in_data=6, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=4),
            Stimulus(in_valid=1, in_data=7, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=5),
            Stimulus(in_valid=1, in_data=8, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=6),
            Stimulus(in_valid=1, in_data=9, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=7),
            Stimulus(in_valid=1, in_data=10, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=8),
            Stimulus(in_valid=1, in_data=11, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=9),
            Stimulus(in_valid=1, in_data=12, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=10),
            Stimulus(in_valid=1, in_data=13, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=11),
            Stimulus(in_valid=1, in_data=14, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=12),
            Stimulus(in_valid=1, in_data=15, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=13),
            Stimulus(in_valid=1, in_data=16, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=14),
            Stimulus(in_valid=1, in_data=17, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=15),
            Stimulus(in_valid=1, in_data=18, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=16),
            Stimulus(in_valid=1, in_data=19, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=17),
            Stimulus(in_valid=1, in_data=20, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=18),
            Stimulus(in_valid=1, in_data=21, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=19),
            Stimulus(in_valid=1, in_data=22, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=20),
            Stimulus(in_valid=1, in_data=23, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=21),
            Stimulus(in_valid=1, in_data=24, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=22),
            Stimulus(in_valid=1, in_data=25, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=23),
            Stimulus(in_valid=1, in_data=26, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=24),
            Stimulus(in_valid=1, in_data=27, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=25),
            Stimulus(in_valid=1, in_data=28, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=26),
            Stimulus(in_valid=1, in_data=29, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=27),
            Stimulus(in_valid=1, in_data=30, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=28),
            Stimulus(in_valid=1, in_data=31, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=29),
            Stimulus(in_valid=1, in_data=32, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=30),
            Stimulus(in_valid=1, in_data=33, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=31),
            Stimulus(in_valid=1, in_data=34, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=32),
            Stimulus(in_valid=1, in_data=35, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=33),
            Stimulus(in_valid=1, in_data=36, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=34),
            Stimulus(in_valid=1, in_data=37, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=35),
            Stimulus(in_valid=1, in_data=38, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=36),
            Stimulus(in_valid=1, in_data=39, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=37),
            Stimulus(in_valid=1, in_data=40, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=38),
            Stimulus(in_valid=1, in_data=41, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=39),
            Stimulus(in_valid=1, in_data=42, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=40),
            Stimulus(in_valid=1, in_data=43, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=41),
            Stimulus(in_valid=1, in_data=44, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=42),
            Stimulus(in_valid=1, in_data=45, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=43),
            Stimulus(in_valid=1, in_data=46, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=44),
            Stimulus(in_valid=1, in_data=47, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=45),
            Stimulus(in_valid=1, in_data=48, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=46),
            Stimulus(in_valid=1, in_data=49, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=47),
            Stimulus(in_valid=1, in_data=50, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=48),
            Stimulus(in_valid=1, in_data=51, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=49),
            Stimulus(in_valid=1, in_data=52, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=50),
            Stimulus(in_valid=1, in_data=53, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=51),
            Stimulus(in_valid=1, in_data=54, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=52),
            Stimulus(in_valid=1, in_data=55, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=53),
            Stimulus(in_valid=1, in_data=56, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=54),
            Stimulus(in_valid=1, in_data=57, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=55),
            Stimulus(in_valid=1, in_data=58, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=56),
            Stimulus(in_valid=1, in_data=59, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=57),
            Stimulus(in_valid=1, in_data=60, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=58),
            Stimulus(in_valid=1, in_data=61, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=59),
            Stimulus(in_valid=1, in_data=62, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=60),
            Stimulus(in_valid=1, in_data=63, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=61),
            Stimulus(in_valid=1, in_data=64, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=62),
            Stimulus(in_valid=1, in_data=65, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=63),
            Stimulus(in_valid=1, in_data=66, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=64),
            Stimulus(in_valid=1, in_data=67, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=65),
            Stimulus(in_valid=1, in_data=68, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=66),
            Stimulus(in_valid=1, in_data=69, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=67),
            Stimulus(in_valid=1, in_data=70, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=68),
            Stimulus(in_valid=1, in_data=71, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=69),
            Stimulus(in_valid=1, in_data=72, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=70),
            Stimulus(in_valid=1, in_data=73, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=71),
            Stimulus(in_valid=1, in_data=74, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=72),
            Stimulus(in_valid=1, in_data=75, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=73),
            Stimulus(in_valid=1, in_data=76, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=74),
            Stimulus(in_valid=1, in_data=77, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=75),
            Stimulus(in_valid=1, in_data=78, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=76),
            Stimulus(in_valid=1, in_data=79, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=77),
            Stimulus(in_valid=1, in_data=80, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=78),
            Stimulus(in_valid=1, in_data=81, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=79),
            Stimulus(in_valid=1, in_data=82, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=80),
            Stimulus(in_valid=1, in_data=83, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=81),
            Stimulus(in_valid=1, in_data=84, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=82),
            Stimulus(in_valid=1, in_data=85, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=83),
            Stimulus(in_valid=1, in_data=86, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=84),
            Stimulus(in_valid=1, in_data=87, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=85),
            Stimulus(in_valid=1, in_data=88, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=86),
            Stimulus(in_valid=1, in_data=89, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=87),
            Stimulus(in_valid=1, in_data=90, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=88),
            Stimulus(in_valid=1, in_data=91, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=89),
            Stimulus(in_valid=1, in_data=92, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=90),
            Stimulus(in_valid=1, in_data=93, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=91),
            Stimulus(in_valid=1, in_data=94, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=92),
            Stimulus(in_valid=1, in_data=95, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=93),
            Stimulus(in_valid=1, in_data=96, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=94),
            Stimulus(in_valid=1, in_data=97, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=95),
            Stimulus(in_valid=1, in_data=98, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=96),
            Stimulus(in_valid=1, in_data=99, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=97),
            Stimulus(in_valid=1, in_data=100, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=98),
            Stimulus(in_valid=1, in_data=101, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=99),
            Stimulus(in_valid=1, in_data=102, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=100),
            Stimulus(in_valid=1, in_data=103, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=101),
            Stimulus(in_valid=1, in_data=104, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=102),
            Stimulus(in_valid=1, in_data=105, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=103),
            Stimulus(in_valid=1, in_data=106, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=104),
            Stimulus(in_valid=1, in_data=107, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=105),
            Stimulus(in_valid=1, in_data=108, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=106),
            Stimulus(in_valid=1, in_data=109, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=107),
            Stimulus(in_valid=1, in_data=110, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=108),
            Stimulus(in_valid=1, in_data=111, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=109),
            Stimulus(in_valid=1, in_data=112, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=110),
            Stimulus(in_valid=1, in_data=113, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=111),
            Stimulus(in_valid=1, in_data=114, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=112),
            Stimulus(in_valid=1, in_data=115, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=113),
            Stimulus(in_valid=1, in_data=116, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=114),
            Stimulus(in_valid=1, in_data=117, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=115),
            Stimulus(in_valid=1, in_data=118, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=116),
            Stimulus(in_valid=1, in_data=119, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=117),
            Stimulus(in_valid=1, in_data=120, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=118),
            Stimulus(in_valid=1, in_data=121, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=119),
            Stimulus(in_valid=1, in_data=122, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=120),
            Stimulus(in_valid=1, in_data=123, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=121),
            Stimulus(in_valid=1, in_data=124, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=122),
            Stimulus(in_valid=1, in_data=125, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=123),
            Stimulus(in_valid=1, in_data=126, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=124),
            Stimulus(in_valid=1, in_data=127, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=125),
            Stimulus(in_valid=1, in_data=128, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=126),
            Stimulus(in_valid=1, in_data=129, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=127),
            Stimulus(in_valid=1, in_data=130, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=128),
            Stimulus(in_valid=1, in_data=131, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=129),
            Stimulus(in_valid=1, in_data=132, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=130),
            Stimulus(in_valid=1, in_data=133, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=131),
            Stimulus(in_valid=1, in_data=134, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=132),
            Stimulus(in_valid=1, in_data=135, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=133),
            Stimulus(in_valid=1, in_data=136, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=134),
            Stimulus(in_valid=1, in_data=137, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=135),
            Stimulus(in_valid=1, in_data=138, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=136),
            Stimulus(in_valid=1, in_data=139, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=137),
            Stimulus(in_valid=1, in_data=140, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=138),
            Stimulus(in_valid=1, in_data=141, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=139),
            Stimulus(in_valid=1, in_data=142, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=140),
            Stimulus(in_valid=1, in_data=143, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=141),
            Stimulus(in_valid=1, in_data=144, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=142),
            Stimulus(in_valid=1, in_data=145, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=143),
            Stimulus(in_valid=1, in_data=146, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=144),
            Stimulus(in_valid=1, in_data=147, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=145),
            Stimulus(in_valid=1, in_data=148, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=146),
            Stimulus(in_valid=1, in_data=149, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=147),
            Stimulus(in_valid=1, in_data=150, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=148),
            Stimulus(in_valid=1, in_data=151, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=149),
            Stimulus(in_valid=1, in_data=152, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=150),
            Stimulus(in_valid=1, in_data=153, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=151),
            Stimulus(in_valid=1, in_data=154, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=152),
            Stimulus(in_valid=1, in_data=155, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=153),
            Stimulus(in_valid=1, in_data=156, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=154),
            Stimulus(in_valid=1, in_data=157, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=155),
            Stimulus(in_valid=1, in_data=158, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=156),
            Stimulus(in_valid=1, in_data=159, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=157),
            Stimulus(in_valid=1, in_data=160, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=158),
            Stimulus(in_valid=1, in_data=161, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=159),
            Stimulus(in_valid=1, in_data=162, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=160),
            Stimulus(in_valid=1, in_data=163, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=161),
            Stimulus(in_valid=1, in_data=164, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=162),
            Stimulus(in_valid=1, in_data=165, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=163),
            Stimulus(in_valid=1, in_data=166, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=164),
            Stimulus(in_valid=1, in_data=167, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=165),
            Stimulus(in_valid=1, in_data=168, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=166),
            Stimulus(in_valid=1, in_data=169, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=167),
            Stimulus(in_valid=1, in_data=170, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=168),
            Stimulus(in_valid=1, in_data=171, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=169),
            Stimulus(in_valid=1, in_data=172, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=170),
            Stimulus(in_valid=1, in_data=173, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=171),
            Stimulus(in_valid=1, in_data=174, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=172),
            Stimulus(in_valid=1, in_data=175, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=173),
            Stimulus(in_valid=1, in_data=176, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=174),
            Stimulus(in_valid=1, in_data=177, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=175),
            Stimulus(in_valid=1, in_data=178, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=176),
            Stimulus(in_valid=1, in_data=179, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=177),
            Stimulus(in_valid=1, in_data=180, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=178),
            Stimulus(in_valid=1, in_data=181, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=179),
            Stimulus(in_valid=1, in_data=182, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=180),
            Stimulus(in_valid=1, in_data=183, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=181),
            Stimulus(in_valid=1, in_data=184, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=182),
            Stimulus(in_valid=1, in_data=185, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=183),
            Stimulus(in_valid=1, in_data=186, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=184),
            Stimulus(in_valid=1, in_data=187, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=185),
            Stimulus(in_valid=1, in_data=188, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=186),
            Stimulus(in_valid=1, in_data=189, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=187),
            Stimulus(in_valid=1, in_data=190, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=188),
            Stimulus(in_valid=1, in_data=191, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=189),
            Stimulus(in_valid=1, in_data=192, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=190),
            Stimulus(in_valid=1, in_data=193, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=191),
            Stimulus(in_valid=1, in_data=194, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=192),
            Stimulus(in_valid=1, in_data=195, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=193),
            Stimulus(in_valid=1, in_data=196, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=194),
            Stimulus(in_valid=1, in_data=197, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=195),
            Stimulus(in_valid=1, in_data=198, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=196),
            Stimulus(in_valid=1, in_data=199, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=197),
            Stimulus(in_valid=1, in_data=200, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=198),
            Stimulus(in_valid=1, in_data=201, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=199),
            Stimulus(in_valid=1, in_data=202, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=200),
            Stimulus(in_valid=1, in_data=203, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=201),
            Stimulus(in_valid=1, in_data=204, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=202),
            Stimulus(in_valid=1, in_data=205, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=203),
            Stimulus(in_valid=1, in_data=206, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=204),
            Stimulus(in_valid=1, in_data=207, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=205),
            Stimulus(in_valid=1, in_data=208, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=206),
            Stimulus(in_valid=1, in_data=209, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=207),
            Stimulus(in_valid=1, in_data=210, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=208),
            Stimulus(in_valid=1, in_data=211, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=209),
            Stimulus(in_valid=1, in_data=212, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=210),
            Stimulus(in_valid=1, in_data=213, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=211),
            Stimulus(in_valid=1, in_data=214, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=212),
            Stimulus(in_valid=1, in_data=215, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=213),
            Stimulus(in_valid=1, in_data=216, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=214),
            Stimulus(in_valid=1, in_data=217, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=215),
            Stimulus(in_valid=1, in_data=218, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=216),
            Stimulus(in_valid=1, in_data=219, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=217),
            Stimulus(in_valid=1, in_data=220, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=218),
            Stimulus(in_valid=1, in_data=221, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=219),
            Stimulus(in_valid=1, in_data=222, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=220),
            Stimulus(in_valid=1, in_data=223, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=221),
            Stimulus(in_valid=1, in_data=224, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=222),
            Stimulus(in_valid=1, in_data=225, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=223),
            Stimulus(in_valid=1, in_data=226, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=224),
            Stimulus(in_valid=1, in_data=227, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=225),
            Stimulus(in_valid=1, in_data=228, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=226),
            Stimulus(in_valid=1, in_data=229, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=227),
            Stimulus(in_valid=1, in_data=230, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=228),
            Stimulus(in_valid=1, in_data=231, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=229),
            Stimulus(in_valid=1, in_data=232, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=230),
            Stimulus(in_valid=1, in_data=233, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=231),
            Stimulus(in_valid=1, in_data=234, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=232),
            Stimulus(in_valid=1, in_data=235, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=233),
            Stimulus(in_valid=1, in_data=236, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=234),
            Stimulus(in_valid=1, in_data=237, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=235),
            Stimulus(in_valid=1, in_data=238, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=236),
            Stimulus(in_valid=1, in_data=239, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=237),
            Stimulus(in_valid=1, in_data=240, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=238),
            Stimulus(in_valid=1, in_data=241, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=239),
            Stimulus(in_valid=1, in_data=242, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=240),
            Stimulus(in_valid=1, in_data=243, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=241),
            Stimulus(in_valid=1, in_data=244, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=242),
            Stimulus(in_valid=1, in_data=245, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=243),
            Stimulus(in_valid=1, in_data=246, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=244),
            Stimulus(in_valid=1, in_data=247, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=245),
            Stimulus(in_valid=1, in_data=248, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=246),
            Stimulus(in_valid=1, in_data=249, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=247),
            Stimulus(in_valid=1, in_data=250, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=248),
            Stimulus(in_valid=1, in_data=251, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=249),
            Stimulus(in_valid=1, in_data=252, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=250),
            Stimulus(in_valid=1, in_data=253, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=251),
            Stimulus(in_valid=1, in_data=254, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=252),
            Stimulus(in_valid=1, in_data=255, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=253),
            Stimulus(out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=254),
            Stimulus(in_data=1, out_ready=1, expected_in_ready=1, expected_out_valid=1, expected_out_data=255),
            Stimulus(in_data=2, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=3, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=4, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=5, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=6, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=7, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=8, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=9, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=10, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=11, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=12, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=13, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=14, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=15, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=16, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=17, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=18, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=19, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=20, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=21, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=22, out_ready=1, expected_in_ready=1),
            Stimulus(in_data=23, out_ready=1, expected_in_ready=1),
            Stimulus(),
        ),
    )
    # fmt: on
    position = phase if phase < 344 else 344
    return stimuli.rows[position]


@rule
def advance(phase):
    if phase < 343:
        phase = phase + 1


@system
def FifoLoopbackSystem():  # noqa: N802
    phase: bits[16] = 0
    frame = stimulus(phase)
    dut = FifoLoopback(frame.in_valid, frame.in_data, frame.out_ready)

    @rule
    def exercise():
        assert (
            dut.in_ready == frame.expected_in_ready
        ), "fifo_loopback in_ready old-state check"
        assert (
            dut.out_valid == frame.expected_out_valid
        ), "fifo_loopback out_valid old-state check"
        assert (
            dut.out_data == frame.expected_out_data
        ), "fifo_loopback out_data old-state check"
        log("info", "phase", phase)
        log("info", "in_ready", dut.in_ready)
        log("info", "out_valid", dut.out_valid)
        log("info", "out_data", dut.out_data)

    advance(phase)
    exercise()
