// QUEUE-CASE: tokens
// Generic FIFO token/family witness; independent harness owns expectations.
#n0 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<0>}}>
#n1 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<1>}}>
#n2 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<2>}}>
#n3 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<3>}}>
#n5 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<5>}}>
#n13 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<13>}}>
#n65 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<65>}}>
#n130 = #ac.static_expr<{kind = "literal", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<130>}}>
!b1 = !ac.bits<#n1>
!b13 = !ac.bits<#n13>
!b65 = !ac.bits<#n65>
!b130 = !ac.bits<#n130>
!controls = !ac.table<[#n2], !b1>
#depth_QueuePair = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueuePair, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueuePair, name = "D"}}>
#latency_QueuePair = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueuePair, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueuePair, name = "L"}}>
!type_QueuePair = !ac.type_param<@QueuePair, "T">
#depth_QueueTablePair = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTablePair, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueueTablePair, name = "D"}}>
#latency_QueueTablePair = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTablePair, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueueTablePair, name = "L"}}>
!type_QueueTablePair = !ac.type_param<@QueueTablePair, "T">
#depth_QueueForward = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueForward, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueueForward, name = "D"}}>
#latency_QueueForward = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueForward, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueueForward, name = "L"}}>
!type_QueueForward = !ac.type_param<@QueueForward, "T">
#depth_QueueDefaultPair = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueDefaultPair, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueueDefaultPair, name = "D"}}>
#latency_QueueDefaultPair = #ac.static_expr<{kind = "reference", location = {path = "queue_emission.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueDefaultPair, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @QueueDefaultPair, name = "L"}}>
!type_QueueDefaultPair = !ac.type_param<@QueueDefaultPair, "T">
!type_QueueDefaultForward = !ac.type_param<@QueueDefaultForward, "T">
module {
  ac.struct "HeaderA" fields [{name = "tag", type = !b13}, {name = "flag", type = !b1}]
  ac.struct "RecordA" fields [{name = "header", type = !ac.struct<"HeaderA">}, {name = "data", type = !b65}]
  ac.struct "HeaderB" fields [{name = "address", type = !b130}, {name = "length", type = !b13}]
  ac.struct "RecordB" fields [{name = "valid", type = !b1}, {name = "metadata", type = !ac.struct<"HeaderB">}]
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !type_QueuePair, %take: !b1, %clk: !b1, %rst: !b1):
    %local_ready, %local_valid, %local_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "local", depth = #depth_QueuePair, ready_policy = "local_occupancy", availability_latency = #latency_QueuePair, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueuePair, ast_path = [{kind = "field", name = "local"}]}, expansion = []}} : (!b1, !b1, !b1, !type_QueuePair, !b1) -> (!b1, !b1, !type_QueuePair)
    %pop_ready, %pop_valid, %pop_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "pop", depth = #depth_QueuePair, ready_policy = "downstream_pop", availability_latency = #latency_QueuePair, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueuePair, ast_path = [{kind = "field", name = "pop"}]}, expansion = []}} : (!b1, !b1, !b1, !type_QueuePair, !b1) -> (!b1, !b1, !type_QueuePair)
    "ac.yield"(%local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data) : (!b1, !b1, !type_QueuePair, !b1, !b1, !type_QueuePair) -> ()
  }) {sym_name = "QueuePair", source_owner = {package = "", path = "queue_emission.py"}, parameters = [{name = "D", type = !ac.math_int}, {name = "L", type = !ac.math_int}], type_parameters = ["T"], function_type = (!b1, !type_QueuePair, !b1, !b1, !b1) -> (!b1, !b1, !type_QueuePair, !b1, !b1, !type_QueuePair), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["local_ready", "local_valid", "local_data", "pop_ready", "pop_valid", "pop_data"]} : () -> ()
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !type_QueueDefaultPair, %take: !b1, %clk: !b1, %rst: !b1):
    %local_ready, %local_valid, %local_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "local", depth = #depth_QueueDefaultPair, ready_policy = "local_occupancy", availability_latency = #latency_QueueDefaultPair, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueueDefaultPair, ast_path = [{kind = "field", name = "local"}]}, expansion = []}} : (!b1, !b1, !b1, !type_QueueDefaultPair, !b1) -> (!b1, !b1, !type_QueueDefaultPair)
    %pop_ready, %pop_valid, %pop_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "pop", depth = #depth_QueueDefaultPair, ready_policy = "downstream_pop", availability_latency = #latency_QueueDefaultPair, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueueDefaultPair, ast_path = [{kind = "field", name = "pop"}]}, expansion = []}} : (!b1, !b1, !b1, !type_QueueDefaultPair, !b1) -> (!b1, !b1, !type_QueueDefaultPair)
    "ac.yield"(%local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data) : (!b1, !b1, !type_QueueDefaultPair, !b1, !b1, !type_QueueDefaultPair) -> ()
  }) {sym_name = "QueueDefaultPair", source_owner = {package = "", path = "queue_emission.py"}, parameters = [{name = "D", type = !ac.math_int, default = #n3}, {name = "L", type = !ac.math_int, default = #n2}], type_parameters = ["T"], function_type = (!b1, !type_QueueDefaultPair, !b1, !b1, !b1) -> (!b1, !b1, !type_QueueDefaultPair, !b1, !b1, !type_QueueDefaultPair), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["local_ready", "local_valid", "local_data", "pop_ready", "pop_valid", "pop_data"]} : () -> ()
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !type_QueueDefaultForward, %take: !b1, %clk: !b1, %rst: !b1):
    %local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data = "ac.instance"(%valid, %data, %take, %clk, %rst) {instance_name = "forward", callee = @QueueDefaultPair, parameters = [], type_arguments = [!type_QueueDefaultForward], occurrence = {site = {definition = @QueueDefaultForward, ast_path = [{kind = "field", name = "forward"}]}, expansion = []}} : (!b1, !type_QueueDefaultForward, !b1, !b1, !b1) -> (!b1, !b1, !type_QueueDefaultForward, !b1, !b1, !type_QueueDefaultForward)
    "ac.yield"(%local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data) : (!b1, !b1, !type_QueueDefaultForward, !b1, !b1, !type_QueueDefaultForward) -> ()
  }) {sym_name = "QueueDefaultForward", source_owner = {package = "", path = "queue_emission.py"}, parameters = [], type_parameters = ["T"], function_type = (!b1, !type_QueueDefaultForward, !b1, !b1, !b1) -> (!b1, !b1, !type_QueueDefaultForward, !b1, !b1, !type_QueueDefaultForward), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["local_ready", "local_valid", "local_data", "pop_ready", "pop_valid", "pop_data"]} : () -> ()
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !type_QueueForward, %take: !b1, %clk: !b1, %rst: !b1):
    %local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data = "ac.instance"(%valid, %data, %take, %clk, %rst) {instance_name = "forward", callee = @QueuePair, parameters = [#depth_QueueForward, #latency_QueueForward], type_arguments = [!type_QueueForward], occurrence = {site = {definition = @QueueForward, ast_path = [{kind = "field", name = "forward"}]}, expansion = []}} : (!b1, !type_QueueForward, !b1, !b1, !b1) -> (!b1, !b1, !type_QueueForward, !b1, !b1, !type_QueueForward)
    "ac.yield"(%local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data) : (!b1, !b1, !type_QueueForward, !b1, !b1, !type_QueueForward) -> ()
  }) {sym_name = "QueueForward", source_owner = {package = "", path = "queue_emission.py"}, parameters = [{name = "D", type = !ac.math_int}, {name = "L", type = !ac.math_int}], type_parameters = ["T"], function_type = (!b1, !type_QueueForward, !b1, !b1, !b1) -> (!b1, !b1, !type_QueueForward, !b1, !b1, !type_QueueForward), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["local_ready", "local_valid", "local_data", "pop_ready", "pop_valid", "pop_data"]} : () -> ()
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !ac.table<[#n3], !type_QueueTablePair>, %take: !b1, %clk: !b1, %rst: !b1):
    %local_ready, %local_valid, %local_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "local", depth = #depth_QueueTablePair, ready_policy = "local_occupancy", availability_latency = #latency_QueueTablePair, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueueTablePair, ast_path = [{kind = "field", name = "local"}]}, expansion = []}} : (!b1, !b1, !b1, !ac.table<[#n3], !type_QueueTablePair>, !b1) -> (!b1, !b1, !ac.table<[#n3], !type_QueueTablePair>)
    %pop_ready, %pop_valid, %pop_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "pop", depth = #depth_QueueTablePair, ready_policy = "downstream_pop", availability_latency = #latency_QueueTablePair, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueueTablePair, ast_path = [{kind = "field", name = "pop"}]}, expansion = []}} : (!b1, !b1, !b1, !ac.table<[#n3], !type_QueueTablePair>, !b1) -> (!b1, !b1, !ac.table<[#n3], !type_QueueTablePair>)
    "ac.yield"(%local_ready, %local_valid, %local_data, %pop_ready, %pop_valid, %pop_data) : (!b1, !b1, !ac.table<[#n3], !type_QueueTablePair>, !b1, !b1, !ac.table<[#n3], !type_QueueTablePair>) -> ()
  }) {sym_name = "QueueTablePair", source_owner = {package = "", path = "queue_emission.py"}, parameters = [{name = "D", type = !ac.math_int}, {name = "L", type = !ac.math_int}], type_parameters = ["T"], function_type = (!b1, !ac.table<[#n3], !type_QueueTablePair>, !b1, !b1, !b1) -> (!b1, !b1, !ac.table<[#n3], !type_QueueTablePair>, !b1, !b1, !ac.table<[#n3], !type_QueueTablePair>), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["local_ready", "local_valid", "local_data", "pop_ready", "pop_valid", "pop_data"]} : () -> ()
  "ac.module"() ({
  ^bb0(%clk: !b1, %rst: !b1, %valid: !controls, %take: !controls, %bit1: !ac.table<[#n2], !b1>, %bit13: !ac.table<[#n2], !b13>, %bit65: !ac.table<[#n2], !b65>, %bit130: !ac.table<[#n2], !b130>, %record_a: !ac.table<[#n2], !ac.struct<"RecordA">>, %record_b: !ac.table<[#n2], !ac.struct<"RecordB">>, %table130: !ac.table<[#n2, #n3], !b130>, %table_record: !ac.table<[#n2, #n3], !ac.struct<"RecordA">>):
    %clocks = "ac.table.splat"(%clk) {shape = [#n2]} : (!b1) -> !controls
    %resets = "ac.table.splat"(%rst) {shape = [#n2]} : (!b1) -> !controls
    %bit1_local_ready, %bit1_local_valid, %bit1_local_data, %bit1_pop_ready, %bit1_pop_valid, %bit1_pop_data = "ac.collection"(%valid, %bit1, %take, %clocks, %resets) {instance_name = "bit1", callee = @QueuePair, parameters = [#n3, #n1], type_arguments = [!b1], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "bit1"}]}, expansion = []}} : (!controls, !ac.table<[#n2], !b1>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2], !b1>, !controls, !controls, !ac.table<[#n2], !b1>)
    %bit13_local_ready, %bit13_local_valid, %bit13_local_data, %bit13_pop_ready, %bit13_pop_valid, %bit13_pop_data = "ac.collection"(%valid, %bit13, %take, %clocks, %resets) {instance_name = "bit13", callee = @QueuePair, parameters = [#n5, #n1], type_arguments = [!b13], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "bit13"}]}, expansion = []}} : (!controls, !ac.table<[#n2], !b13>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2], !b13>, !controls, !controls, !ac.table<[#n2], !b13>)
    %bit65_local_ready, %bit65_local_valid, %bit65_local_data, %bit65_pop_ready, %bit65_pop_valid, %bit65_pop_data = "ac.collection"(%valid, %bit65, %take, %clocks, %resets) {instance_name = "bit65", callee = @QueuePair, parameters = [#n3, #n1], type_arguments = [!b65], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "bit65"}]}, expansion = []}} : (!controls, !ac.table<[#n2], !b65>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2], !b65>, !controls, !controls, !ac.table<[#n2], !b65>)
    %bit130_local_ready, %bit130_local_valid, %bit130_local_data, %bit130_pop_ready, %bit130_pop_valid, %bit130_pop_data = "ac.collection"(%valid, %bit130, %take, %clocks, %resets) {instance_name = "bit130", callee = @QueuePair, parameters = [#n5, #n1], type_arguments = [!b130], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "bit130"}]}, expansion = []}} : (!controls, !ac.table<[#n2], !b130>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2], !b130>, !controls, !controls, !ac.table<[#n2], !b130>)
    %record_a_local_ready, %record_a_local_valid, %record_a_local_data, %record_a_pop_ready, %record_a_pop_valid, %record_a_pop_data = "ac.collection"(%valid, %record_a, %take, %clocks, %resets) {instance_name = "record_a", callee = @QueuePair, parameters = [#n3, #n1], type_arguments = [!ac.struct<"RecordA">], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "record_a"}]}, expansion = []}} : (!controls, !ac.table<[#n2], !ac.struct<"RecordA">>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordA">>)
    %record_b_local_ready, %record_b_local_valid, %record_b_local_data, %record_b_pop_ready, %record_b_pop_valid, %record_b_pop_data = "ac.collection"(%valid, %record_b, %take, %clocks, %resets) {instance_name = "record_b", callee = @QueuePair, parameters = [#n5, #n1], type_arguments = [!ac.struct<"RecordB">], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "record_b"}]}, expansion = []}} : (!controls, !ac.table<[#n2], !ac.struct<"RecordB">>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2], !ac.struct<"RecordB">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordB">>)
    %table130_local_ready, %table130_local_valid, %table130_local_data, %table130_pop_ready, %table130_pop_valid, %table130_pop_data = "ac.collection"(%valid, %table130, %take, %clocks, %resets) {instance_name = "table130", callee = @QueueTablePair, parameters = [#n3, #n1], type_arguments = [!b130], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "table130"}]}, expansion = []}} : (!controls, !ac.table<[#n2, #n3], !b130>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2, #n3], !b130>, !controls, !controls, !ac.table<[#n2, #n3], !b130>)
    %table_record_local_ready, %table_record_local_valid, %table_record_local_data, %table_record_pop_ready, %table_record_pop_valid, %table_record_pop_data = "ac.collection"(%valid, %table_record, %take, %clocks, %resets) {instance_name = "table_record", callee = @QueueTablePair, parameters = [#n5, #n1], type_arguments = [!ac.struct<"RecordA">], shape = [#n2], occurrence = {site = {definition = @QueueTokens, ast_path = [{kind = "field", name = "table_record"}]}, expansion = []}} : (!controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>, !controls, !controls, !controls) -> (!controls, !controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>)
    "ac.yield"(%bit1_local_ready, %bit1_local_valid, %bit1_local_data, %bit1_pop_ready, %bit1_pop_valid, %bit1_pop_data, %bit13_local_ready, %bit13_local_valid, %bit13_local_data, %bit13_pop_ready, %bit13_pop_valid, %bit13_pop_data, %bit65_local_ready, %bit65_local_valid, %bit65_local_data, %bit65_pop_ready, %bit65_pop_valid, %bit65_pop_data, %bit130_local_ready, %bit130_local_valid, %bit130_local_data, %bit130_pop_ready, %bit130_pop_valid, %bit130_pop_data, %record_a_local_ready, %record_a_local_valid, %record_a_local_data, %record_a_pop_ready, %record_a_pop_valid, %record_a_pop_data, %record_b_local_ready, %record_b_local_valid, %record_b_local_data, %record_b_pop_ready, %record_b_pop_valid, %record_b_pop_data, %table130_local_ready, %table130_local_valid, %table130_local_data, %table130_pop_ready, %table130_pop_valid, %table130_pop_data, %table_record_local_ready, %table_record_local_valid, %table_record_local_data, %table_record_pop_ready, %table_record_pop_valid, %table_record_pop_data) : (!controls, !controls, !ac.table<[#n2], !b1>, !controls, !controls, !ac.table<[#n2], !b1>, !controls, !controls, !ac.table<[#n2], !b13>, !controls, !controls, !ac.table<[#n2], !b13>, !controls, !controls, !ac.table<[#n2], !b65>, !controls, !controls, !ac.table<[#n2], !b65>, !controls, !controls, !ac.table<[#n2], !b130>, !controls, !controls, !ac.table<[#n2], !b130>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordB">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordB">>, !controls, !controls, !ac.table<[#n2, #n3], !b130>, !controls, !controls, !ac.table<[#n2, #n3], !b130>, !controls, !controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>) -> ()
  }) {sym_name = "QueueTokens", source_owner = {package = "", path = "queue_emission.py"}, parameters = [], type_parameters = [], function_type = (!b1, !b1, !controls, !controls, !ac.table<[#n2], !b1>, !ac.table<[#n2], !b13>, !ac.table<[#n2], !b65>, !ac.table<[#n2], !b130>, !ac.table<[#n2], !ac.struct<"RecordA">>, !ac.table<[#n2], !ac.struct<"RecordB">>, !ac.table<[#n2, #n3], !b130>, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>) -> (!controls, !controls, !ac.table<[#n2], !b1>, !controls, !controls, !ac.table<[#n2], !b1>, !controls, !controls, !ac.table<[#n2], !b13>, !controls, !controls, !ac.table<[#n2], !b13>, !controls, !controls, !ac.table<[#n2], !b65>, !controls, !controls, !ac.table<[#n2], !b65>, !controls, !controls, !ac.table<[#n2], !b130>, !controls, !controls, !ac.table<[#n2], !b130>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordB">>, !controls, !controls, !ac.table<[#n2], !ac.struct<"RecordB">>, !controls, !controls, !ac.table<[#n2, #n3], !b130>, !controls, !controls, !ac.table<[#n2, #n3], !b130>, !controls, !controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>, !controls, !controls, !ac.table<[#n2, #n3], !ac.struct<"RecordA">>), input_names = ["clk", "rst", "valid", "take", "bit1", "bit13", "bit65", "bit130", "record_a", "record_b", "table130", "table_record"], output_names = ["bit1_local_ready", "bit1_local_valid", "bit1_local_data", "bit1_pop_ready", "bit1_pop_valid", "bit1_pop_data", "bit13_local_ready", "bit13_local_valid", "bit13_local_data", "bit13_pop_ready", "bit13_pop_valid", "bit13_pop_data", "bit65_local_ready", "bit65_local_valid", "bit65_local_data", "bit65_pop_ready", "bit65_pop_valid", "bit65_pop_data", "bit130_local_ready", "bit130_local_valid", "bit130_local_data", "bit130_pop_ready", "bit130_pop_valid", "bit130_pop_data", "record_a_local_ready", "record_a_local_valid", "record_a_local_data", "record_a_pop_ready", "record_a_pop_valid", "record_a_pop_data", "record_b_local_ready", "record_b_local_valid", "record_b_local_data", "record_b_pop_ready", "record_b_pop_valid", "record_b_pop_data", "table130_local_ready", "table130_local_valid", "table130_local_data", "table130_pop_ready", "table130_pop_valid", "table130_pop_data", "table_record_local_ready", "table_record_local_valid", "table_record_local_data", "table_record_pop_ready", "table_record_pop_valid", "table_record_pop_data"]} : () -> ()
  "ac.system"() {entry = {callee = @QueueTokens, parameters = [], type_arguments = []}, domain = "default"} : () -> ()
}

// -----
// QUEUE-CASE: atomic
#n0 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<0>}}>
#n1 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<1>}}>
#n2 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<2>}}>
#n3 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<3>}}>
#n5 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<5>}}>
#n13 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<13>}}>
#n65 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<65>}}>
#n130 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<130>}}>
!b1 = !ac.bits<#n1>
!b13 = !ac.bits<#n13>
!b65 = !ac.bits<#n65>
!b130 = !ac.bits<#n130>
!controls = !ac.table<[#n2], !b1>
#depth_LocalWrapper = #ac.static_expr<{kind = "reference", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @LocalWrapper, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @LocalWrapper, name = "D"}}>
#depth_PopWrapper = #ac.static_expr<{kind = "reference", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @PopWrapper, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @PopWrapper, name = "D"}}>
module {
  "ac.module.import"() {sym_name = "storage", source_owner = {package = "gfsim", path = "dffe.py"}, parameters = [], type_parameters = ["T"], function_type = (!b1, !b1, !b1, !ac.type_param<@storage, "T">, !ac.type_param<@storage, "T">) -> !ac.type_param<@storage, "T">, input_names = ["clk", "rst", "en", "d", "init"], output_names = ["q"], primitive_kind = "dffe", dependency_summary = [{output = {port = 0 : i64, path = []}, inputs = []}]} : () -> ()
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !b13, %take: !b1, %clk: !b1, %rst: !b1):
    %fifo_ready, %fifo_valid, %fifo_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "fifo", depth = #depth_LocalWrapper, ready_policy = "local_occupancy", availability_latency = #n1, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @LocalWrapper, ast_path = [{kind = "field", name = "fifo"}]}, expansion = []}} : (!b1, !b1, !b1, !b13, !b1) -> (!b1, !b1, !b13)
    "ac.yield"(%fifo_ready, %fifo_valid, %fifo_data) : (!b1, !b1, !b13) -> ()
  }) {sym_name = "LocalWrapper", source_owner = {package = "", path = "queue_atomic.py"}, parameters = [{name = "D", type = !ac.math_int}], type_parameters = [], function_type = (!b1, !b13, !b1, !b1, !b1) -> (!b1, !b1, !b13), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["ready", "available", "head"]} : () -> ()
  "ac.module"() ({
  ^bb0(%valid: !b1, %data: !b13, %take: !b1, %clk: !b1, %rst: !b1):
    %fifo_ready, %fifo_valid, %fifo_data = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "fifo", depth = #depth_PopWrapper, ready_policy = "downstream_pop", availability_latency = #n1, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @PopWrapper, ast_path = [{kind = "field", name = "fifo"}]}, expansion = []}} : (!b1, !b1, !b1, !b13, !b1) -> (!b1, !b1, !b13)
    "ac.yield"(%fifo_ready, %fifo_valid, %fifo_data) : (!b1, !b1, !b13) -> ()
  }) {sym_name = "PopWrapper", source_owner = {package = "", path = "queue_atomic.py"}, parameters = [{name = "D", type = !ac.math_int}], type_parameters = [], function_type = (!b1, !b13, !b1, !b1, !b1) -> (!b1, !b1, !b13), input_names = ["valid", "data", "take", "clk", "rst"], output_names = ["ready", "available", "head"]} : () -> ()
  "ac.module"() ({
  ^bb0(%clk: !b1, %rst: !b1, %valid0: !b1, %valid1: !b1, %take0: !b1, %take1: !b1, %data0: !b13, %data1: !b13, %loop0: !b1, %loop1: !b1, %reg_enable: !b1, %reg_data: !b13):
    %feed0 = "ac.bits.select"(%loop0, %head0, %data0) : (!b1, !b13, !b13) -> !b13
    %ready0, %available0, %head0 = "ac.instance"(%valid0, %feed0, %take0, %clk, %rst) {instance_name = "left", callee = @LocalWrapper, parameters = [#n3], type_arguments = [], occurrence = {site = {definition = @QueueAtomic, ast_path = [{kind = "field", name = "left"}]}, expansion = []}} : (!b1, !b13, !b1, !b1, !b1) -> (!b1, !b1, !b13)
    %feed1 = "ac.bits.select"(%loop1, %head1, %data1) : (!b1, !b13, !b13) -> !b13
    %ready1, %available1, %head1 = "ac.instance"(%valid1, %feed1, %take1, %clk, %rst) {instance_name = "right", callee = @PopWrapper, parameters = [#n5], type_arguments = [], occurrence = {site = {definition = @QueueAtomic, ast_path = [{kind = "field", name = "right"}]}, expansion = []}} : (!b1, !b13, !b1, !b1, !b1) -> (!b1, !b1, !b13)
    %zero = "ac.bits.constant"() {value = #n0} : () -> !b13
    %parent_q = "ac.instance"(%clk, %rst, %reg_enable, %reg_data, %zero) {instance_name = "parent_reg", callee = @storage, parameters = [], type_arguments = [!b13], occurrence = {site = {definition = @QueueAtomic, ast_path = [{kind = "field", name = "parent_reg"}]}, expansion = []}} : (!b1, !b1, !b1, !b13, !b13) -> !b13
    "ac.yield"(%ready0, %available0, %head0, %ready1, %available1, %head1, %parent_q) : (!b1, !b1, !b13, !b1, !b1, !b13, !b13) -> ()
  }) {sym_name = "QueueAtomic", source_owner = {package = "", path = "queue_atomic.py"}, parameters = [], type_parameters = [], function_type = (!b1, !b1, !b1, !b1, !b1, !b1, !b13, !b13, !b1, !b1, !b1, !b13) -> (!b1, !b1, !b13, !b1, !b1, !b13, !b13), input_names = ["clk", "rst", "valid0", "valid1", "take0", "take1", "data0", "data1", "loop0", "loop1", "reg_enable", "reg_data"], output_names = ["ready0", "available0", "head0", "ready1", "available1", "head1", "parent_q"]} : () -> ()
  "ac.system"() {entry = {callee = @QueueAtomic, parameters = [], type_arguments = []}, domain = "default"} : () -> ()
}

// -----
// QUEUE-CASE: dead
#n0 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<0>}}>
#n1 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<1>}}>
#n2 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<2>}}>
#n3 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<3>}}>
#n5 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<5>}}>
#n13 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<13>}}>
#n65 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<65>}}>
#n130 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<130>}}>
!b1 = !ac.bits<#n1>
!b13 = !ac.bits<#n13>
!b65 = !ac.bits<#n65>
!b130 = !ac.bits<#n130>
!controls = !ac.table<[#n2], !b1>
#depth_LocalWrapper = #ac.static_expr<{kind = "reference", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @LocalWrapper, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @LocalWrapper, name = "D"}}>
#depth_PopWrapper = #ac.static_expr<{kind = "reference", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @PopWrapper, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @PopWrapper, name = "D"}}>
module {
  "ac.module"() ({
  ^bb0(%clk: !b1, %rst: !b1, %valid: !b1, %take: !b1, %data: !b13):
    %ready, %available, %head = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "fifo", depth = #n3, ready_policy = "local_occupancy", availability_latency = #n1, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueueOwner, ast_path = [{kind = "field", name = "fifo"}]}, expansion = []}} : (!b1, !b1, !b1, !b13, !b1) -> (!b1, !b1, !b13)
    %one = "ac.bits.constant"() {value = #n1} : () -> !b1
    %zero1 = "ac.bits.constant"() {value = #n0} : () -> !b1
    %zero = "ac.bits.constant"() {value = #n0} : () -> !b13
    "ac.yield"(%one, %zero1, %zero, %zero) : (!b1, !b1, !b13, !b13) -> ()
  }) {sym_name = "QueueOwner", source_owner = {package = "", path = "queue_owner.py"}, parameters = [], type_parameters = [], function_type = (!b1, !b1, !b1, !b1, !b13) -> (!b1, !b1, !b13, !b13), input_names = ["clk", "rst", "valid", "take", "data"], output_names = ["ready", "available", "head", "echo"]} : () -> ()
  "ac.system"() {entry = {callee = @QueueOwner, parameters = [], type_arguments = []}, domain = "default"} : () -> ()
}

// -----
// QUEUE-CASE: collision
#n0 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<0>}}>
#n1 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<1>}}>
#n2 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<2>}}>
#n3 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<3>}}>
#n5 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<5>}}>
#n13 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<13>}}>
#n65 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<65>}}>
#n130 = #ac.static_expr<{kind = "literal", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @QueueTokens, ast_path = []}, expansion = []}, value = {kind = "integer", value = #ac.math_int<130>}}>
!b1 = !ac.bits<#n1>
!b13 = !ac.bits<#n13>
!b65 = !ac.bits<#n65>
!b130 = !ac.bits<#n130>
!controls = !ac.table<[#n2], !b1>
#depth_LocalWrapper = #ac.static_expr<{kind = "reference", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @LocalWrapper, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @LocalWrapper, name = "D"}}>
#depth_PopWrapper = #ac.static_expr<{kind = "reference", location = {path = "queue_tokens.py", line = 1 : i64, column = 1 : i64, end_line = 1 : i64, end_column = 2 : i64}, origin = {site = {definition = @PopWrapper, ast_path = []}, expansion = []}, ref = {kind = "parameter", owner = @PopWrapper, name = "D"}}>
module {
  "ac.module"() ({
  ^bb0(%data: !b13):
    "ac.yield"(%data) : (!b13) -> ()
  }) {sym_name = "Identity", source_owner = {package = "", path = "queue_owner.py"}, parameters = [], type_parameters = [], function_type = (!b13) -> !b13, input_names = ["data"], output_names = ["echo"]} : () -> ()
  "ac.module"() ({
  ^bb0(%clk: !b1, %rst: !b1, %valid: !b1, %take: !b1, %data: !b13):
    %ready, %available, %head = "ac.queue"(%clk, %rst, %valid, %data, %take) {instance_name = "fifo", depth = #n3, ready_policy = "local_occupancy", availability_latency = #n1, head_read_latency = #n0, empty_flow = false, read_during_write = "old", reset_policy = "sync_high_empty", empty_data = "zero", occurrence = {site = {definition = @QueueOwner, ast_path = [{kind = "field", name = "fifo"}]}, expansion = []}} : (!b1, !b1, !b1, !b13, !b1) -> (!b1, !b1, !b13)
    %one = "ac.bits.constant"() {value = #n1} : () -> !b1
    %zero1 = "ac.bits.constant"() {value = #n0} : () -> !b1
    %zero = "ac.bits.constant"() {value = #n0} : () -> !b13
    %echo = "ac.instance"(%data) {instance_name = "fifo_state", callee = @Identity, parameters = [], type_arguments = [], occurrence = {site = {definition = @QueueOwner, ast_path = [{kind = "field", name = "fifo_state"}]}, expansion = []}} : (!b13) -> !b13
    "ac.yield"(%ready, %available, %head, %echo) : (!b1, !b1, !b13, !b13) -> ()
  }) {sym_name = "QueueOwner", source_owner = {package = "", path = "queue_owner.py"}, parameters = [], type_parameters = [], function_type = (!b1, !b1, !b1, !b1, !b13) -> (!b1, !b1, !b13, !b13), input_names = ["clk", "rst", "valid", "take", "data"], output_names = ["ready", "available", "head", "echo"]} : () -> ()
  "ac.system"() {entry = {callee = @QueueOwner, parameters = [], type_arguments = []}, domain = "default"} : () -> ()
}
