find_package(MLIR REQUIRED CONFIG HINTS /home/lc/opt/llvm-22.1.8/lib/cmake/mlir)
if(NOT TARGET zstd::libzstd_static AND TARGET zstd::libzstd_shared)
  add_library(zstd::libzstd_static ALIAS zstd::libzstd_shared)
endif()
list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}")
include(AddLLVM)
include(AddMLIR)
include_directories(${MLIR_INCLUDE_DIRS})
set(LLVM_TARGET_DEFINITIONS ACIR.td)
mlir_tablegen(ACIRDialect.h.inc -gen-dialect-decls -dialect=acir)
mlir_tablegen(ACIRDialect.cpp.inc -gen-dialect-defs -dialect=acir)
mlir_tablegen(ACIRTypes.h.inc -gen-typedef-decls -typedefs-dialect=acir)
mlir_tablegen(ACIRTypes.cpp.inc -gen-typedef-defs -typedefs-dialect=acir)
mlir_tablegen(ACIROps.h.inc -gen-op-decls)
mlir_tablegen(ACIROps.cpp.inc -gen-op-defs)
set(LLVM_TARGET_DEFINITIONS Passes.td)
mlir_tablegen(ACIRPasses.h.inc -gen-pass-decls -name ACIR)
add_public_tablegen_target(ACIRIncGen)
add_library(ACIRCompiler STATIC Dialect.cpp Compiler.cpp)
add_dependencies(ACIRCompiler ACIRIncGen)
target_include_directories(ACIRCompiler PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
target_include_directories(ACIRCompiler SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
target_compile_definitions(ACIRCompiler PRIVATE ${LLVM_DEFINITIONS})
target_compile_features(ACIRCompiler PRIVATE cxx_std_20)
target_link_libraries(ACIRCompiler PUBLIC MLIRParser MLIRIR MLIRPass MLIRTransforms
  MLIRFuncDialect MLIRArithDialect MLIRControlFlowDialect MLIREmitCDialect MLIRSCFDialect
  MLIRTargetCpp MLIRSupport)
if(NOT LLVM_ENABLE_RTTI)
  target_compile_options(ACIRCompiler PRIVATE -fno-rtti)
endif()

add_executable(acir-compile Driver.cpp)
add_executable(acir-opt Opt.cpp)
foreach(tool IN ITEMS acir-compile acir-opt)
  target_compile_features(${tool} PRIVATE cxx_std_20)
  target_include_directories(${tool} PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
  target_link_libraries(${tool} PRIVATE ACIRCompiler)
  if(NOT LLVM_ENABLE_RTTI)
    target_compile_options(${tool} PRIVATE -fno-rtti)
  endif()
endforeach()
target_link_libraries(acir-opt PRIVATE MLIROptLib)
