#!/usr/bin/env python3
"""Generate the pinned Unicode full-casefold table used for SourceOwner IDs."""

from __future__ import annotations

import unicodedata
from pathlib import Path

EXPECTED_UNICODE_VERSION = "16.0.0"
OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "lib"
    / "Dialect"
    / "ACIR"
    / "ACIRSourceOwnerCaseFoldData.h"
)


def main() -> None:
    if unicodedata.unidata_version != EXPECTED_UNICODE_VERSION:
        raise SystemExit(
            f"requires Unicode {EXPECTED_UNICODE_VERSION}, got "
            f"{unicodedata.unidata_version}"
        )

    entries: list[tuple[int, int, int]] = []
    values: list[int] = []
    for codepoint in range(0x110000):
        folded = chr(codepoint).casefold()
        if folded == chr(codepoint):
            continue
        sequence = [ord(character) for character in folded]
        entries.append((codepoint, len(values), len(sequence)))
        values.extend(sequence)

    lines = [
        "// Generated by compiler/tools/generate_source_owner_casefold.py.",
        "// Unicode 16.0.0 default full case folding; do not hand-edit.",
        "#ifndef ACIR_LIB_DIALECT_ACIR_ACIRSOURCEOWNERCASEFOLDDATA_H",
        "#define ACIR_LIB_DIALECT_ACIR_ACIRSOURCEOWNERCASEFOLDDATA_H",
        "",
        "#include <cstdint>",
        "",
        "namespace acir::ac::final_detail {",
        "struct SourceOwnerCaseFoldEntry {",
        "  std::uint32_t codePoint;",
        "  std::uint32_t valueOffset;",
        "  std::uint8_t valueLength;",
        "};",
        "",
        "inline constexpr SourceOwnerCaseFoldEntry",
        "    kSourceOwnerCaseFoldEntries[] = {",
    ]
    for index in range(0, len(entries), 4):
        chunk = entries[index : index + 4]
        lines.append(
            "        "
            + ", ".join(
                f"{{0x{codepoint:x}, {offset}, {length}}}"
                for codepoint, offset, length in chunk
            )
            + ","
        )
    lines.extend(
        [
            "};",
            "",
            "inline constexpr std::uint32_t kSourceOwnerCaseFoldValues[] = {",
        ]
    )
    for index in range(0, len(values), 12):
        chunk = values[index : index + 12]
        lines.append(
            "    " + ", ".join(f"0x{codepoint:x}" for codepoint in chunk) + ","
        )
    lines.extend(
        [
            "};",
            "} // namespace acir::ac::final_detail",
            "",
            "#endif // ACIR_LIB_DIALECT_ACIR_ACIRSOURCEOWNERCASEFOLDDATA_H",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
