# Shared public-command plumbing, extracted from the verified module_loop flow.
enable_testing()
include_guard(GLOBAL)
include(CMakeParseArguments)
option(PYC_EXAMPLE_VERIFY "Register independent example verification" ON)
# Run at directory completion so auxiliary four-state/encoder tests share the
# owning example's tier, including standalone example builds (CMake >= 3.25).
function(pycircuit_label_example_tests)
  get_property(_tests DIRECTORY PROPERTY TESTS)
  if(NOT DEFINED PYC_EXAMPLE_LABELS)
    set(PYC_EXAMPLE_LABELS "examples;nightly")
  endif()
  if(_tests)
    set_tests_properties(${_tests} PROPERTIES LABELS "${PYC_EXAMPLE_LABELS}")
  endif()
endfunction()

function(pycircuit_add_system_verification name cycles timeout)
  if(NOT cycles MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "System verification requires an explicit positive cycle count")
  endif()
  find_program(VERILATOR_EXECUTABLE verilator REQUIRED)
  add_test(NAME ${name}_system COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/verify_example.py"
    --system --source "${CMAKE_CURRENT_SOURCE_DIR}"
    --runner "${PYC_DRIVER}" --toolchain "${PYCIRCUIT_TOOLCHAIN_ROOT}"
    --build "${CMAKE_CURRENT_BINARY_DIR}/system-verification"
    --include "${PYCIRCUIT_RUNTIME_INCLUDE_DIR}"
    --cycles "${cycles}" --timeout "${timeout}")
  math(EXPR _system_timeout "3 * ${timeout} + 30")
  set_tests_properties(${name}_system PROPERTIES
    LABELS "${PYC_EXAMPLE_LABELS}" TIMEOUT "${_system_timeout}")
endfunction()

function(pycircuit_add_example name)
  cmake_language(DEFER CALL pycircuit_label_example_tests)
  cmake_parse_arguments(EX "" "TOP;PACKAGE;ENTRY_SOURCE;DRIVER;RUNNER;TIMEOUT_SECONDS;CYCLES;SYSTEM_TOP;SYSTEM_ENTRY_SOURCE;SYSTEM_CYCLES;SYSTEM_TIMEOUT_SECONDS" "SOURCES;SYSTEM_SOURCES" ${ARGN})
  foreach(_required TOP PACKAGE ENTRY_SOURCE SOURCES)
    if(NOT EX_${_required})
      message(FATAL_ERROR "pycircuit_add_example requires ${_required}")
    endif()
  endforeach()
  if(EX_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unknown example arguments: ${EX_UNPARSED_ARGUMENTS}")
  endif()
  if(EX_SYSTEM_TOP OR EX_SYSTEM_ENTRY_SOURCE OR EX_SYSTEM_SOURCES OR EX_SYSTEM_CYCLES)
    foreach(_required SYSTEM_TOP SYSTEM_ENTRY_SOURCE SYSTEM_SOURCES SYSTEM_CYCLES)
      if(NOT EX_${_required})
        message(FATAL_ERROR "System selection requires ${_required}")
      endif()
    endforeach()
    if(NOT EX_SYSTEM_CYCLES MATCHES "^[1-9][0-9]*$")
      message(FATAL_ERROR "SYSTEM_CYCLES requires a positive integer number of cycles")
    endif()
    # Ordinary aggregate builds retain the reusable module and its independent
    # oracle. Public run selects the separately authored closed system root.
    if(PYC_EXAMPLE_RUN_TARGET)
      set(EX_TOP "${EX_SYSTEM_TOP}")
      set(EX_ENTRY_SOURCE "${EX_SYSTEM_ENTRY_SOURCE}")
      set(EX_SOURCES "${EX_SYSTEM_SOURCES}")
    endif()
  endif()
  if("TIMEOUT_SECONDS" IN_LIST EX_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "TIMEOUT_SECONDS requires a positive integer number of seconds")
  endif()
  if(NOT DEFINED EX_TIMEOUT_SECONDS)
    set(EX_TIMEOUT_SECONDS 180)
  endif()
  if(NOT EX_TIMEOUT_SECONDS MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "TIMEOUT_SECONDS requires a positive integer number of seconds")
  endif()
  if("SYSTEM_TIMEOUT_SECONDS" IN_LIST EX_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "SYSTEM_TIMEOUT_SECONDS requires a positive integer number of seconds")
  endif()
  if(NOT DEFINED EX_SYSTEM_TIMEOUT_SECONDS)
    set(EX_SYSTEM_TIMEOUT_SECONDS "${EX_TIMEOUT_SECONDS}")
  endif()
  if(NOT EX_SYSTEM_TIMEOUT_SECONDS MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "SYSTEM_TIMEOUT_SECONDS requires a positive integer number of seconds")
  endif()
  if(NOT EX_DRIVER)
    set(EX_DRIVER driver.cpp)
  endif()
  if(NOT EX_RUNNER)
    set(EX_RUNNER pycircuit_${name})
  endif()
  string(REPLACE "." "/" _package_path "${EX_PACKAGE}")
  # SOURCES is the explicit dependency order. Each listed file owns modules;
  # dependency manifests still record only the interfaces actually consumed.
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  if(NOT PYCIRCUIT_DRIVER_EXECUTABLE OR NOT EXISTS "${PYCIRCUIT_DRIVER_EXECUTABLE}")
    message(FATAL_ERROR "Source examples require the installed pycircuit compiler driver")
  endif()
  set(PYC_DRIVER "${PYCIRCUIT_DRIVER_EXECUTABLE}")
  set(_helpers "${PYC_DRIVER}")
  # Reuse the existing publication-safe Ninja directory preparation helper.
  set(_prepare "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/prepare_output.py")
  list(APPEND _helpers "${_prepare}")
  if(DEFINED PYCIRCUIT_PYTHON_DIR)
    file(GLOB_RECURSE _driver_python CONFIGURE_DEPENDS
      "${PYCIRCUIT_PYTHON_DIR}/pycircuit/*.py")
    list(APPEND _helpers ${_driver_python})
  endif()
  file(GLOB _package_configs CONFIGURE_DEPENDS
    "${PYCIRCUIT_TOOLCHAIN_ROOT}/share/pycircuit/cmake/*.cmake")
  list(APPEND _helpers ${_package_configs}
    "${PYCIRCUIT_TOOLCHAIN_ROOT}/share/pycircuit/toolchain-metadata.json")
  foreach(_name pycircuit-source-unit pycircuit-link pycircuit-emit)
    set(_helper "${PYCIRCUIT_TOOLCHAIN_ROOT}/bin/${_name}${CMAKE_EXECUTABLE_SUFFIX}")
    if(NOT EXISTS "${_helper}")
      message(FATAL_ERROR "Installed compiler helper is missing: ${_helper}")
    endif()
    list(APPEND _helpers "${_helper}")
  endforeach()
  set(_units "${CMAKE_CURRENT_BINARY_DIR}/units")
  set(_unit_dirs)
  set(_interfaces)
  set(_link_inputs)
  set(_source_stems)
  foreach(_file IN LISTS EX_SOURCES)
    if(IS_ABSOLUTE "${_file}" OR _file MATCHES "(^|/)\\.\\.(/|$)" OR NOT _file MATCHES "\\.py$")
      message(FATAL_ERROR "Example source must be a relative Python path: ${_file}")
    endif()
    string(REGEX REPLACE "\\.py$" "" _stem "${_file}")
    list(APPEND _source_stems "${_stem}")
  endforeach()
  foreach(_file IN LISTS EX_SOURCES)
    get_filename_component(_source "${_file}" NAME_WE)
    string(REGEX REPLACE "\\.py$" "" _stem "${_file}")
    set(_imports)
    set(_dependencies "${CMAKE_CURRENT_SOURCE_DIR}/${_file}" ${_helpers})
    foreach(_prior IN LISTS _unit_dirs)
      list(APPEND _imports -I "${_prior}")
    endforeach()
    list(APPEND _dependencies ${_interfaces})
    add_custom_command(OUTPUT "${_units}/${_stem}/${_source}.ac" "${_units}/${_stem}/${_source}.interface.ac" "${_units}/${_stem}/unit.json"
      BYPRODUCTS "${_units}/${_stem}/${_source}.d"
      COMMAND "${CMAKE_COMMAND}" -E make_directory "${_units}"
      COMMAND "${Python3_EXECUTABLE}" "${_prepare}" "${_units}/${_stem}"
      COMMAND "${PYC_DRIVER}" compile -c "${CMAKE_CURRENT_SOURCE_DIR}/${_file}" --source-root "${CMAKE_CURRENT_SOURCE_DIR}" --package-prefix "${EX_PACKAGE}" ${_imports} -o "${_units}/${_stem}" --replace
      DEPFILE "${_units}/${_stem}/${_source}.d" DEPENDS ${_dependencies} VERBATIM)
    list(APPEND _unit_dirs "${_units}/${_stem}")
    list(APPEND _interfaces "${_units}/${_stem}/${_source}.interface.ac" "${_units}/${_stem}/unit.json")
    list(APPEND _link_inputs "${_units}/${_stem}/${_source}.ac" "${_units}/${_stem}/${_source}.interface.ac" "${_units}/${_stem}/unit.json")
  endforeach()
  set(_final "${CMAKE_CURRENT_BINARY_DIR}/${EX_ENTRY_SOURCE}.ac")
  add_custom_command(OUTPUT "${_final}"
    COMMAND "${PYC_DRIVER}" link ${_unit_dirs} --top "${EX_TOP}" -o "${_final}" --replace
    DEPENDS ${_link_inputs} ${_helpers} VERBATIM)
  foreach(_target cpp verilog)
    set(_byproducts "${CMAKE_CURRENT_BINARY_DIR}/${_target}/CMakeLists.txt")
    foreach(_stem IN LISTS _source_stems)
      list(APPEND _byproducts
        "${CMAKE_CURRENT_BINARY_DIR}/${_target}/sources/${_package_path}/${_stem}.source-map.json")
    endforeach()
    if(_target STREQUAL "cpp")
      list(APPEND _byproducts "${CMAKE_CURRENT_BINARY_DIR}/cpp/pycircuit_system.hpp"
        "${CMAKE_CURRENT_BINARY_DIR}/cpp/pycircuit_support.hpp")
      foreach(_stem IN LISTS _source_stems)
        list(APPEND _byproducts "${CMAKE_CURRENT_BINARY_DIR}/cpp/sources/${_package_path}/${_stem}.hpp"
          "${CMAKE_CURRENT_BINARY_DIR}/cpp/sources/${_package_path}/${_stem}.cpp")
      endforeach()
    else()
      list(APPEND _byproducts "${CMAKE_CURRENT_BINARY_DIR}/verilog/design_top.sv")
      foreach(_stem IN LISTS _source_stems)
        list(APPEND _byproducts
          "${CMAKE_CURRENT_BINARY_DIR}/verilog/sources/${_package_path}/${_stem}.v")
      endforeach()
    endif()
    add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${_target}/generated.json"
      BYPRODUCTS ${_byproducts}
      COMMAND "${Python3_EXECUTABLE}" "${_prepare}" "${CMAKE_CURRENT_BINARY_DIR}/${_target}"
      COMMAND "${PYC_DRIVER}" emit "${_final}" --target ${_target} -o "${CMAKE_CURRENT_BINARY_DIR}/${_target}" --replace
      DEPENDS "${_final}" ${_helpers} VERBATIM)
    add_custom_target(${name}_${_target}_artifacts ALL DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/${_target}/generated.json")
  endforeach()
  if(PYC_EXAMPLE_RUN_TARGET)
    if(NOT PYC_EXAMPLE_RUN_TARGET MATCHES "^(cpp|verilog)$")
      message(FATAL_ERROR "Simulation target must be cpp or verilog")
    endif()
    if(TARGET pycircuit_simulation_artifacts)
      message(FATAL_ERROR "Run one example directory, not the aggregate example catalog")
    endif()
    add_custom_target(pycircuit_simulation_artifacts DEPENDS ${name}_${PYC_EXAMPLE_RUN_TARGET}_artifacts)
  endif()
  set(_sources)
  foreach(_stem IN LISTS _source_stems)
    list(APPEND _sources "${CMAKE_CURRENT_BINARY_DIR}/cpp/sources/${_package_path}/${_stem}.cpp")
  endforeach()
  set_source_files_properties(${_sources} PROPERTIES GENERATED TRUE)
  set(_authored_driver TRUE)
  if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${EX_DRIVER}" AND NOT IS_ABSOLUTE "${EX_DRIVER}")
    set(_authored_driver FALSE)
    set(EX_DRIVER "${CMAKE_CURRENT_BINARY_DIR}/cpp/simulation_main.cpp")
    set_source_files_properties("${EX_DRIVER}" PROPERTIES GENERATED TRUE)
  endif()
  add_executable(${EX_RUNNER} "${EX_DRIVER}" ${_sources})
  add_dependencies(${EX_RUNNER} ${name}_cpp_artifacts)
  target_compile_features(${EX_RUNNER} PRIVATE cxx_std_20)
  target_include_directories(${EX_RUNNER} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/cpp")
  target_link_libraries(${EX_RUNNER} PRIVATE pycircuit::pyc6_runtime)
  if(NOT PYC_EXAMPLE_VERIFY)
    return()
  endif()
  if(NOT _authored_driver)
    pycircuit_add_system_verification(${name} "${EX_CYCLES}" "${EX_SYSTEM_TIMEOUT_SECONDS}")
    return()
  endif()
  find_program(VERILATOR_EXECUTABLE verilator REQUIRED)
  add_test(NAME ${name} COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/verify_example.py"
    --source "${CMAKE_CURRENT_SOURCE_DIR}"
    --runner "$<TARGET_FILE:${EX_RUNNER}>" --build "${CMAKE_CURRENT_BINARY_DIR}"
    --include "${PYCIRCUIT_RUNTIME_INCLUDE_DIR}" --verilator "${VERILATOR_EXECUTABLE}"
    --timeout "${EX_TIMEOUT_SECONDS}")
  if(NOT DEFINED PYC_EXAMPLE_LABELS)
    set(PYC_EXAMPLE_LABELS "examples;nightly")
  endif()
  math(EXPR _test_timeout "4 * ${EX_TIMEOUT_SECONDS} + 30")
  set_tests_properties(${name} PROPERTIES
    LABELS "${PYC_EXAMPLE_LABELS}" TIMEOUT "${_test_timeout}")
  if(EX_SYSTEM_TOP)
    pycircuit_add_system_verification(${name} "${EX_SYSTEM_CYCLES}" "${EX_SYSTEM_TIMEOUT_SECONDS}")
  endif()
endfunction()
