#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List

from crawler import load_config
from dependency_closure import RepositoryModel, build_dependency_closure
from dependency_overlay import apply_dependency_overlay
from repo_manager import ensure_repo, git_metadata


def write_csv(path: Path, rows: List[Dict], fields: List[str]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction='ignore')
        w.writeheader()
        w.writerows(rows)


def safe_name(s: str) -> str:
    return re.sub(r'[^A-Za-z0-9_.-]+', '_', s)


def verilator_version() -> str:
    exe = shutil.which('verilator')
    if not exe:
        return ''
    try:
        p = subprocess.run([exe, '--version'], text=True, capture_output=True, check=False)
        return (p.stdout or p.stderr).strip()
    except Exception:
        return ''


def create_filelist(repo_dir: Path, closure: Dict, outdir: Path) -> Path:
    lines = [
        '// Auto-generated by pyCircuit RTL Crawler v0.3.1.1',
        '// Relative paths in this -F file are relative to this file.',
    ]

    # -F makes relative paths relative to the filelist itself, so use paths from
    # candidate directory to repo files.
    for root in closure['include_roots']:
        inc_abs = (repo_dir / root).resolve()
        rel = Path(shutil.os.path.relpath(inc_abs, outdir.resolve())).as_posix()
        lines.append(f'-I{rel}')

    # Sibling repositories are intentionally kept outside the primary checkout
    # to preserve provenance.  Their include roots are absolute because the
    # candidate filelist can be consumed from either Windows or WSL.
    for root in closure.get('external_include_roots', []):
        lines.append(f'-I{Path(root).resolve().as_posix()}')

    # Packages must appear before modules that import them.
    compile_files = []
    seen = set()
    for relsrc in closure['package_files'] + closure['module_files']:
        if relsrc in seen:
            continue
        seen.add(relsrc)
        compile_files.append(relsrc)

    for relsrc in compile_files:
        src_abs = (repo_dir / relsrc).resolve()
        rel = Path(shutil.os.path.relpath(src_abs, outdir.resolve())).as_posix()
        lines.append(rel)

    # External packages must be read before modules that use their typedefs.
    for src in closure.get('external_package_files', []):
        lines.append(Path(src).resolve().as_posix())
    for src in closure.get('external_files', []):
        lines.append(Path(src).resolve().as_posix())

    path = outdir / 'candidate.f'
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return path



def materialize_generated_files(source: Dict, outdir: Path, closure: Dict, config_dir: Path) -> None:
    """Write source-declared generated headers/shims into the candidate."""
    specs = {}
    for rel, content in (source.get('generated_files', {}) or {}).items():
        if isinstance(rel, str) and isinstance(content, str):
            specs[rel.replace('\\\\', '/').lstrip('/')] = content
    for item in (source.get('generated_file_paths', []) or []):
        path = Path(str(item))
        if not path.is_absolute():
            path = config_dir / path
        if path.is_file():
            specs[path.name] = path.read_text(encoding='utf-8')
    if not specs:
        return
    generated_root = (outdir / '_generated').resolve()
    generated_root.mkdir(parents=True, exist_ok=True)
    generated = []
    module_names, include_names = set(), set()
    for rel, content in sorted(specs.items()):
        target = (generated_root / rel).resolve()
        if generated_root not in target.parents and target != generated_root:
            raise ValueError(f'generated file escapes candidate directory: {rel}')
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content if content.endswith('\n') else content + '\n', encoding='utf-8')
        generated.append(str(target))
        if target.suffix.lower() in {'.v', '.sv'}:
            module_names.update(re.findall(r'(?m)^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)', content))
            closure.setdefault('external_files', []).append(str(target))
        else:
            include_names.add(target.name)
            closure.setdefault('external_include_roots', []).append(str(target.parent))
            closure.setdefault('generated_header_files', []).append(str(target))
    for edge in closure.get('unresolved', []):
        name = str(edge.get('dependency_name', ''))
        if edge.get('dependency_kind') == 'submodule' and name in module_names:
            edge['resolution_status'] = 'resolved_generated'
            edge['resolved_file'] = '@generated/' + name
        elif edge.get('dependency_kind') == 'include' and Path(name).name in include_names:
            edge['resolution_status'] = 'resolved_generated'
            edge['resolved_file'] = '@generated/' + Path(name).name
    closure['external_files'] = sorted(set(closure.get('external_files', [])))
    closure['external_include_roots'] = sorted(set(closure.get('external_include_roots', [])))
    closure['generated_files'] = sorted(generated)
    closure['generated_header_files'] = sorted(set(closure.get('generated_header_files', [])))
    closure['unresolved'] = [e for e in closure.get('unresolved', []) if e.get('resolution_status') not in {'resolved', 'resolved_generated', 'pruned_config_dead'}]
    closure['closure_status'] = 'COMPLETE' if not closure['unresolved'] else 'PARTIAL'


def validation_wrapper_spec(source: Dict, module: str) -> Dict:
    specs = source.get('validation_wrappers', {}) or {}
    spec = specs.get(module, {})
    return dict(spec) if isinstance(spec, dict) else {}


def configured_parameter_overrides(source: Dict, module: str) -> Dict:
    """Return deterministic elaboration parameters for one candidate.

    The crawler must not guess values for parameters that change the shape of
    a reusable primitive.  Source manifests may therefore provide exact
    per-module values (and an optional ``*`` fallback).  Values are kept as
    JSON scalars so they can be passed unchanged to both Verilator ``-G`` and
    Yosys ``chparam``.
    """
    raw = source.get('parameter_overrides', {}) or {}
    if not isinstance(raw, dict):
        return {}
    merged = {}
    wildcard = raw.get('*', {})
    if isinstance(wildcard, dict):
        merged.update(wildcard)
    exact = raw.get(module, {})
    if isinstance(exact, dict):
        merged.update(exact)
    return {str(k): v for k, v in merged.items() if str(k).strip()}


def _axi4_wrapper(module: str, spec: Dict, top: str) -> str:
    """Build a concrete AXI4 struct-type wrapper for generic PULP AXI RTL.

    The upstream modules intentionally default their ``parameter type`` ports
    to ``logic`` and are expected to be instantiated by a typed design.  A
    standalone crawler candidate has no such context, so Verilator reports a
    member selection on ``logic``.  This wrapper supplies the canonical AXI
    typedefs from the repository and leaves the DUT implementation untouched.
    """
    if module == 'axi_cdc':
        inst = f'''  {module} #(
    .aw_chan_t(pyc_axi_aw_chan_t), .w_chan_t(pyc_axi_w_chan_t),
    .b_chan_t(pyc_axi_b_chan_t), .ar_chan_t(pyc_axi_ar_chan_t),
    .r_chan_t(pyc_axi_r_chan_t), .axi_req_t(pyc_axi_req_t),
    .axi_resp_t(pyc_axi_resp_t), .LogDepth({int(spec.get("log_depth", 1))})
  ) dut (
    .src_clk_i(src_clk_i), .src_rst_ni(src_rst_ni), .src_req_i(src_req_i),
    .src_resp_o(src_resp_o), .dst_clk_i(dst_clk_i), .dst_rst_ni(dst_rst_ni),
    .dst_req_o(dst_req_o), .dst_resp_i(dst_resp_i)
  );'''
        signals = '''  logic src_clk_i, src_rst_ni, dst_clk_i, dst_rst_ni;
  pyc_axi_req_t src_req_i, dst_req_o;
  pyc_axi_resp_t src_resp_o, dst_resp_i;
'''
    elif lite_src_uses_full:
        bus = "AXI_BUS"
        bus_params = " .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_ID_WIDTH(4), .AXI_USER_WIDTH(1) "
        async_bus = "AXI_LITE_ASYNC_GRAY"
        async_params = f" .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .LOG_DEPTH({log_depth}) "
        widths = f".AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .LOG_DEPTH({log_depth}), .SYNC_STAGES({sync_stages})"
    else:
        inst = f'''  {module} #(
    .AxiIdWidth(4), .AtopSupport(1'b0),
    .aw_chan_t(pyc_axi_aw_chan_t), .w_chan_t(pyc_axi_w_chan_t),
    .b_chan_t(pyc_axi_b_chan_t), .ar_chan_t(pyc_axi_ar_chan_t),
    .r_chan_t(pyc_axi_r_chan_t),
    .axi_req_t(pyc_axi_req_t), .axi_resp_t(pyc_axi_resp_t),
    .NoMstPorts({int(spec.get("no_mst_ports", 2))}),
    .MaxTrans({int(spec.get("max_trans", 4))})
  ) dut (
    .clk_i(clk_i), .rst_ni(rst_ni), .test_i(test_i),
    .slv_req_i(slv_req_i), .slv_aw_select_i(slv_aw_select_i),
    .slv_ar_select_i(slv_ar_select_i), .slv_resp_o(slv_resp_o),
    .mst_reqs_o(mst_reqs_o), .mst_resps_i(mst_resps_i)
  );'''
        ports = int(spec.get('no_mst_ports', 2))
        signals = f'''  logic clk_i, rst_ni, test_i;
  logic [0:0] slv_aw_select_i, slv_ar_select_i;
  pyc_axi_req_t slv_req_i;
  pyc_axi_resp_t slv_resp_o;
  pyc_axi_req_t [0:{ports - 1}] mst_reqs_o;
  pyc_axi_resp_t [0:{ports - 1}] mst_resps_i;
'''
    return f'''// Auto-generated validation context; DUT remains upstream RTL.
`include "axi/typedef.svh"
module {top};
  import axi_pkg::*;
  typedef logic [31:0] pyc_addr_t;
  typedef logic [3:0]  pyc_id_t;
  typedef logic [31:0] pyc_data_t;
  typedef logic [3:0]  pyc_strb_t;
  typedef logic [0:0]  pyc_user_t;
  `AXI_TYPEDEF_ALL(pyc_axi, pyc_addr_t, pyc_id_t, pyc_data_t, pyc_strb_t, pyc_user_t)
{signals}{inst}
endmodule
'''


def _axi4_endpoint_wrapper(module: str, spec: Dict, top: str) -> str:
    """Concrete typed context for the raw AXI CDC endpoint halves.

    ``axi_cdc_src/dst`` are intentionally generic over seven struct types.
    Running either half as a standalone candidate otherwise leaves those
    types as ``logic`` and Verilator reports ``Member call on object``.  The
    wrapper only supplies typedefs and tie-off signals; the CDC implementation
    remains the upstream RTL.
    """
    log_depth = int(spec.get("log_depth", 1))
    sync_stages = int(spec.get("sync_stages", 3))
    depth = 2 ** log_depth
    ptr_w = log_depth + 1
    if module not in {"axi_cdc_src", "axi_cdc_dst"}:
        raise ValueError(f"Unsupported AXI endpoint wrapper module {module}")
    if module == "axi_cdc_dst":
        ports = f'''  pyc_axi_aw_chan_t [{depth - 1}:0] async_data_slave_aw_data_i;
  logic [{ptr_w - 1}:0] async_data_slave_aw_wptr_i, async_data_slave_aw_rptr_o;
  pyc_axi_w_chan_t  [{depth - 1}:0] async_data_slave_w_data_i;
  logic [{ptr_w - 1}:0] async_data_slave_w_wptr_i, async_data_slave_w_rptr_o;
  pyc_axi_b_chan_t  [{depth - 1}:0] async_data_slave_b_data_o;
  logic [{ptr_w - 1}:0] async_data_slave_b_wptr_o, async_data_slave_b_rptr_i;
  pyc_axi_ar_chan_t [{depth - 1}:0] async_data_slave_ar_data_i;
  logic [{ptr_w - 1}:0] async_data_slave_ar_wptr_i, async_data_slave_ar_rptr_o;
  pyc_axi_r_chan_t  [{depth - 1}:0] async_data_slave_r_data_o;
  logic [{ptr_w - 1}:0] async_data_slave_r_wptr_o, async_data_slave_r_rptr_i;
  logic dst_clk_i, dst_rst_ni;
  pyc_axi_req_t dst_req_o;
  pyc_axi_resp_t dst_resp_i;'''
        call = '''    .async_data_slave_aw_data_i, .async_data_slave_aw_wptr_i,
    .async_data_slave_aw_rptr_o, .async_data_slave_w_data_i,
    .async_data_slave_w_wptr_i, .async_data_slave_w_rptr_o,
    .async_data_slave_b_data_o, .async_data_slave_b_wptr_o,
    .async_data_slave_b_rptr_i, .async_data_slave_ar_data_i,
    .async_data_slave_ar_wptr_i, .async_data_slave_ar_rptr_o,
    .async_data_slave_r_data_o, .async_data_slave_r_wptr_o,
    .async_data_slave_r_rptr_i, .dst_clk_i, .dst_rst_ni,
    .dst_req_o, .dst_resp_i'''
    else:
        ports = f'''  logic src_clk_i, src_rst_ni;
  pyc_axi_req_t src_req_i;
  pyc_axi_resp_t src_resp_o;
  pyc_axi_aw_chan_t [{depth - 1}:0] async_data_master_aw_data_o;
  logic [{ptr_w - 1}:0] async_data_master_aw_wptr_o, async_data_master_aw_rptr_i;
  pyc_axi_w_chan_t  [{depth - 1}:0] async_data_master_w_data_o;
  logic [{ptr_w - 1}:0] async_data_master_w_wptr_o, async_data_master_w_rptr_i;
  pyc_axi_b_chan_t  [{depth - 1}:0] async_data_master_b_data_i;
  logic [{ptr_w - 1}:0] async_data_master_b_wptr_i, async_data_master_b_rptr_o;
  pyc_axi_ar_chan_t [{depth - 1}:0] async_data_master_ar_data_o;
  logic [{ptr_w - 1}:0] async_data_master_ar_wptr_o, async_data_master_ar_rptr_i;
  pyc_axi_r_chan_t  [{depth - 1}:0] async_data_master_r_data_i;
  logic [{ptr_w - 1}:0] async_data_master_r_wptr_i, async_data_master_r_rptr_o;'''
        call = '''    .src_clk_i, .src_rst_ni, .src_req_i, .src_resp_o,
    .async_data_master_aw_data_o, .async_data_master_aw_wptr_o,
    .async_data_master_aw_rptr_i, .async_data_master_w_data_o,
    .async_data_master_w_wptr_o, .async_data_master_w_rptr_i,
    .async_data_master_b_data_i, .async_data_master_b_wptr_i,
    .async_data_master_b_rptr_o, .async_data_master_ar_data_o,
    .async_data_master_ar_wptr_o, .async_data_master_ar_rptr_i,
    .async_data_master_r_data_i, .async_data_master_r_wptr_i,
    .async_data_master_r_rptr_o'''
    return f'''// Auto-generated typed validation context; DUT remains upstream RTL.
`include "axi/typedef.svh"
module {top};
  import axi_pkg::*;
  typedef logic [31:0] pyc_addr_t;
  typedef logic [3:0]  pyc_id_t;
  typedef logic [31:0] pyc_data_t;
  typedef logic [3:0]  pyc_strb_t;
  typedef logic [0:0]  pyc_user_t;
  `AXI_TYPEDEF_ALL(pyc_axi, pyc_addr_t, pyc_id_t, pyc_data_t, pyc_strb_t, pyc_user_t)
{ports}
  {module} #(
    .LogDepth({log_depth}), .SyncStages({sync_stages}),
    .aw_chan_t(pyc_axi_aw_chan_t), .w_chan_t(pyc_axi_w_chan_t),
    .b_chan_t(pyc_axi_b_chan_t), .ar_chan_t(pyc_axi_ar_chan_t),
    .r_chan_t(pyc_axi_r_chan_t), .axi_req_t(pyc_axi_req_t),
    .axi_resp_t(pyc_axi_resp_t)
  ) dut (
{call}
  );
endmodule
'''


def _axi_interface_context_wrapper(module: str, spec: Dict, top: str) -> str:
    """Tie off interface ports with real interface instances.

    An interface port is not a legal standalone top-level connection in
    Yosys/Verilator.  Instantiating the matching interface objects gives the
    DUT an elaboration context without flattening or changing its semantics.
    """
    lite = module.startswith("axi_lite_")
    is_dst = module.endswith("_dst_intf")
    is_src = module.endswith("_src_intf")
    is_full = module in {"axi_cdc_intf", "axi_lite_cdc_intf"}
    if not (is_dst or is_src or is_full):
        raise ValueError(f"Unsupported interface context wrapper module {module}")
    log_depth = int(spec.get("log_depth", 1))
    sync_stages = int(spec.get("sync_stages", 3))
    # The upstream lite source endpoint currently declares its synchronous
    # ``src`` port as AXI_BUS (the implementation still uses the lite assign
    # macros).  Match that declaration exactly so the wrapper exposes a real
    # interface rather than masking a source-level mismatch.
    lite_src_uses_full = module == "axi_lite_cdc_src_intf"
    if lite and not lite_src_uses_full:
        bus = "AXI_LITE"
        bus_params = " .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32) "
        async_bus = "AXI_LITE_ASYNC_GRAY"
        async_params = f" .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .LOG_DEPTH({log_depth}) "
        widths = f".AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .LOG_DEPTH({log_depth}), .SYNC_STAGES({sync_stages})"
    elif lite_src_uses_full:
        bus = "AXI_BUS"
        bus_params = " .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_ID_WIDTH(4), .AXI_USER_WIDTH(1) "
        async_bus = "AXI_LITE_ASYNC_GRAY"
        async_params = f" .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .LOG_DEPTH({log_depth}) "
        widths = f".AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .LOG_DEPTH({log_depth}), .SYNC_STAGES({sync_stages})"
    else:
        bus = "AXI_BUS"
        bus_params = " .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_ID_WIDTH(4), .AXI_USER_WIDTH(1) "
        async_bus = "AXI_BUS_ASYNC_GRAY"
        async_params = f" .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_ID_WIDTH(4), .AXI_USER_WIDTH(1), .LOG_DEPTH({log_depth}) "
        widths = f".AXI_ID_WIDTH(4), .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_USER_WIDTH(1), .LOG_DEPTH({log_depth}), .SYNC_STAGES({sync_stages})"
    if is_dst:
        decl = f"  {async_bus} #({async_params}) src();\n  {bus} #({bus_params}) dst();"
        ports = ".src(src), .dst_clk_i(clk_i), .dst_rst_ni(rst_ni), .dst(dst)"
    elif is_src:
        decl = f"  {bus} #({bus_params}) src();\n  {async_bus} #({async_params}) dst();"
        ports = ".src_clk_i(clk_i), .src_rst_ni(rst_ni), .src(src), .dst(dst)"
    else:
        decl = f"  {bus} #({bus_params}) src();\n  {bus} #({bus_params}) dst();"
        ports = ".src_clk_i(src_clk_i), .src_rst_ni(src_rst_ni), .src(src), .dst_clk_i(dst_clk_i), .dst_rst_ni(dst_rst_ni), .dst(dst)"
    clocks = "  logic clk_i, rst_ni;" if not is_full else "  logic src_clk_i, src_rst_ni, dst_clk_i, dst_rst_ni;"
    return f'''// Auto-generated interface validation context; DUT remains upstream RTL.
module {top};
{clocks}
{decl}
  {module} #({widths}) dut ({ports});
endmodule
'''


def _axi_lite_wrapper(module: str, spec: Dict, top: str) -> str:
    if module == 'axi_lite_mux':
        ports = int(spec.get('no_slv_ports', 2))
        inst = f'''  {module} #(
    .aw_chan_t(pyc_lite_aw_chan_t), .w_chan_t(pyc_lite_w_chan_t),
    .b_chan_t(pyc_lite_b_chan_t), .ar_chan_t(pyc_lite_ar_chan_t),
    .r_chan_t(pyc_lite_r_chan_t), .axi_req_t(pyc_lite_req_t),
    .axi_resp_t(pyc_lite_resp_t), .NoSlvPorts({ports}),
    .MaxTrans({int(spec.get("max_trans", 4))})
  ) dut (
    .clk_i(clk_i), .rst_ni(rst_ni), .test_i(test_i),
    .slv_reqs_i(slv_reqs_i), .slv_resps_o(slv_resps_o),
    .mst_req_o(mst_req_o), .mst_resp_i(mst_resp_i)
  );'''
        signals = f'''  logic clk_i, rst_ni, test_i;
  pyc_lite_req_t [0:{ports - 1}] slv_reqs_i;
  pyc_lite_resp_t [0:{ports - 1}] slv_resps_o;
  pyc_lite_req_t mst_req_o;
  pyc_lite_resp_t mst_resp_i;
'''
    else:
        ports = int(spec.get('no_mst_ports', 2))
        inst = f'''  {module} #(
    .aw_chan_t(pyc_lite_aw_chan_t), .w_chan_t(pyc_lite_w_chan_t),
    .b_chan_t(pyc_lite_b_chan_t), .ar_chan_t(pyc_lite_ar_chan_t),
    .r_chan_t(pyc_lite_r_chan_t), .axi_req_t(pyc_lite_req_t),
    .axi_resp_t(pyc_lite_resp_t), .NoMstPorts({ports}),
    .MaxTrans({int(spec.get("max_trans", 4))})
  ) dut (
    .clk_i(clk_i), .rst_ni(rst_ni), .test_i(test_i),
    .slv_req_i(slv_req_i), .slv_aw_select_i(slv_aw_select_i),
    .slv_ar_select_i(slv_ar_select_i), .slv_resp_o(slv_resp_o),
    .mst_reqs_o(mst_reqs_o), .mst_resps_i(mst_resps_i)
  );'''
        signals = f'''  logic clk_i, rst_ni, test_i;
  logic [0:0] slv_aw_select_i, slv_ar_select_i;
  pyc_lite_req_t slv_req_i;
  pyc_lite_resp_t slv_resp_o;
  pyc_lite_req_t [0:{ports - 1}] mst_reqs_o;
  pyc_lite_resp_t [0:{ports - 1}] mst_resps_i;
'''
    return f'''// Auto-generated validation context; DUT remains upstream RTL.
`include "axi/typedef.svh"
module {top};
  import axi_pkg::*;
  typedef logic [31:0] pyc_lite_addr_t;
  typedef logic [31:0] pyc_lite_data_t;
  typedef logic [3:0]  pyc_lite_strb_t;
  `AXI_LITE_TYPEDEF_ALL(pyc_lite, pyc_lite_addr_t, pyc_lite_data_t, pyc_lite_strb_t)
{signals}{inst}
endmodule
'''


def _cva6_btb_wrapper(spec: Dict, top: str) -> str:
    config = str(spec.get('config') or 'core/include/cv64a6_imafdc_sv39_config_pkg.sv')
    config_name = Path(config).name
    nr_entries = int(spec.get('nr_entries', 32))
    return f'''// Auto-generated fixed CVA6 validation context; upstream BTB RTL is unchanged.
`include "{config_name}"
`include "build_config_pkg.sv"
module {top};
  import config_pkg::*;
  typedef struct packed {{
    logic valid;
    logic [63:0] pc;
    logic [63:0] target_address;
  }} pyc_btb_update_t;
  typedef struct packed {{
    logic valid;
    logic [63:0] target_address;
  }} pyc_btb_prediction_t;
  localparam config_pkg::cva6_cfg_t pyc_cfg = build_config_pkg::build_config(cva6_config_pkg::cva6_cfg);
  logic clk_i, rst_ni, flush_bp_i, debug_mode_i;
  pyc_btb_update_t btb_update_i;
  pyc_btb_prediction_t [pyc_cfg.INSTR_PER_FETCH-1:0] btb_prediction_o;
  btb #(
    .CVA6Cfg(pyc_cfg), .btb_update_t(pyc_btb_update_t),
    .btb_prediction_t(pyc_btb_prediction_t), .NR_ENTRIES({nr_entries})
  ) dut (
    .clk_i(clk_i), .rst_ni(rst_ni), .flush_bp_i(flush_bp_i),
    .debug_mode_i(debug_mode_i), .vpc_i('0), .btb_update_i(btb_update_i),
    .btb_prediction_o(btb_prediction_o)
  );
endmodule
'''


def _axi4_scalar_wrapper(module: str, spec: Dict, top: str) -> str:
    is_gran = module == 'axi_burst_splitter_gran'
    extra = '.len_limit_i(8\'h00), ' if is_gran else ''
    params = f'''    .MaxReadTxns({int(spec.get("max_read_txns", 4))}),
    .MaxWriteTxns({int(spec.get("max_write_txns", 4))}),
    .AddrWidth(32), .DataWidth(32), .IdWidth(4), .UserWidth(1),
    .axi_req_t(pyc_axi_req_t), .axi_resp_t(pyc_axi_resp_t),
    .axi_aw_chan_t(pyc_axi_aw_chan_t), .axi_w_chan_t(pyc_axi_w_chan_t),
    .axi_b_chan_t(pyc_axi_b_chan_t), .axi_ar_chan_t(pyc_axi_ar_chan_t),
    .axi_r_chan_t(pyc_axi_r_chan_t)'''
    if not is_gran:
        params = f'''    .MaxReadTxns({int(spec.get("max_read_txns", 4))}),
    .MaxWriteTxns({int(spec.get("max_write_txns", 4))}),
    .AddrWidth(32), .DataWidth(32), .IdWidth(4), .UserWidth(1),
    .axi_req_t(pyc_axi_req_t), .axi_resp_t(pyc_axi_resp_t)'''
    call = f'''    .clk_i(clk_i), .rst_ni(rst_ni), {extra}
    .slv_req_i(slv_req_i), .slv_resp_o(slv_resp_o),
    .mst_req_o(mst_req_o), .mst_resp_i(mst_resp_i)'''
    return f'''// Auto-generated validation context; DUT remains upstream RTL.
`include "axi/typedef.svh"
module {top};
  import axi_pkg::*;
  typedef logic [31:0] pyc_addr_t;
  typedef logic [3:0] pyc_id_t;
  typedef logic [31:0] pyc_data_t;
  typedef logic [3:0] pyc_strb_t;
  typedef logic [0:0] pyc_user_t;
  `AXI_TYPEDEF_ALL(pyc_axi, pyc_addr_t, pyc_id_t, pyc_data_t, pyc_strb_t, pyc_user_t)
  logic clk_i, rst_ni;
  pyc_axi_req_t slv_req_i, mst_req_o;
  pyc_axi_resp_t slv_resp_o, mst_resp_i;
  {module} #(
{params}
  ) dut (
{call}
  );
endmodule
'''


def _axi_interface_wrapper(module: str, spec: Dict, top: str) -> str:
    lite = module.startswith('axi_lite_')
    count = int(spec.get('count', 2))
    iface = 'AXI_LITE' if lite else 'AXI_BUS'
    params = '.AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32)' if lite else '.AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_ID_WIDTH(4), .AXI_USER_WIDTH(1)'
    if module in {'axi_lite_demux_intf', 'axi_demux_intf'}:
        port_decl = f'''  {iface} #({params}) slv();
  {iface} #({params}) mst [0:{count - 1}]();'''
        call = f'''    .clk_i(clk_i), .rst_ni(rst_ni), .test_i(test_i),
    .slv_aw_select_i(slv_aw_select_i), .slv_ar_select_i(slv_ar_select_i),
    .slv(slv), .mst(mst)'''
        select = '  logic [0:0] slv_aw_select_i, slv_ar_select_i;\n'
        if lite:
            instparams = f'.AxiAddrWidth(32), .AxiDataWidth(32), .NoMstPorts({count}), .MaxTrans(4)'
        else:
            instparams = f'.AXI_ID_WIDTH(4), .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_USER_WIDTH(1), .NO_MST_PORTS({count}), .MAX_TRANS(4)'
    elif module in {'axi_lite_mux_intf', 'axi_mux_intf'}:
        port_decl = f'''  {iface} #({params}) slv [0:{count - 1}]();
  {iface} #({params}) mst();'''
        call = '    .clk_i(clk_i), .rst_ni(rst_ni), .test_i(test_i), .slv(slv), .mst(mst)'
        select = ''
        if lite:
            instparams = f'.AxiAddrWidth(32), .AxiDataWidth(32), .NoSlvPorts({count}), .MaxTrans(4)'
        else:
            instparams = f'.SLV_AXI_ID_WIDTH(4), .MST_AXI_ID_WIDTH(5), .AXI_ADDR_WIDTH(32), .AXI_DATA_WIDTH(32), .AXI_USER_WIDTH(1), .NO_SLV_PORTS({count}), .MAX_W_TRANS(4)'
    else:
        raise ValueError(f'Unsupported interface wrapper module {module}')
    return f'''// Auto-generated interface validation context; DUT remains upstream RTL.
module {top};
  logic clk_i, rst_ni, test_i;
{select}{port_decl}
  {module} #({instparams}) dut (
{call}
  );
endmodule
'''


def _cva6_fifo_wrapper(top: str) -> str:
    return f'''// Auto-generated CVA6 SRAM primitive validation context.
// Both FPGA branches are elaborated to exercise the exact primitive ports.
module {top};
  logic clk_i, rst_ni, flush_i, testmode_i;
  logic [31:0] data_i_async, data_o_async;
  logic [31:0] data_i_sync, data_o_sync;
  logic push_async, pop_async, push_sync, pop_sync;
  logic full_async, empty_async, full_sync, empty_sync;
  logic [2:0] usage_async, usage_sync;
  cva6_fifo_v3 #(.DATA_WIDTH(32), .DEPTH(4), .FPGA_EN(1'b1), .FPGA_ALTERA(1'b0))
    dut_async (
      .clk_i, .rst_ni, .flush_i, .testmode_i,
      .full_o(full_async), .empty_o(empty_async), .usage_o(usage_async),
      .data_i(data_i_async), .push_i(push_async), .data_o(data_o_async), .pop_i(pop_async)
    );
  cva6_fifo_v3 #(.DATA_WIDTH(32), .DEPTH(4), .FPGA_EN(1'b1), .FPGA_ALTERA(1'b1))
    dut_sync (
      .clk_i, .rst_ni, .flush_i, .testmode_i,
      .full_o(full_sync), .empty_o(empty_sync), .usage_o(usage_sync),
      .data_i(data_i_sync), .push_i(push_sync), .data_o(data_o_sync), .pop_i(pop_sync)
    );
endmodule
'''


def materialize_validation_wrapper(source: Dict, module: str, outdir: Path, closure: Dict) -> str:
    spec = validation_wrapper_spec(source, module)
    if not spec:
        return module
    kind = str(spec.get('kind', '')).lower()
    top = str(spec.get('top') or f'pycircuit_validate_{safe_name(module)}')
    if kind in {'axi4', 'axi4_cdc'}:
        content = _axi4_wrapper(module, spec, top)
    elif kind == 'axi4_endpoint':
        content = _axi4_endpoint_wrapper(module, spec, top)
    elif kind in {'axi_lite', 'axi_lite_mux'}:
        content = _axi_lite_wrapper(module, spec, top)
    elif kind == 'cva6_btb':
        content = _cva6_btb_wrapper(spec, top)
    elif kind == 'axi4_scalar':
        content = _axi4_scalar_wrapper(module, spec, top)
    elif kind == 'axi_intf':
        content = _axi_interface_wrapper(module, spec, top)
    elif kind in {'axi_cdc_intf', 'axi_cdc_endpoint_intf'}:
        content = _axi_interface_context_wrapper(module, spec, top)
    elif kind == 'cva6_fifo':
        content = _cva6_fifo_wrapper(top)
    else:
        raise ValueError(f'Unsupported validation wrapper kind {kind!r} for {module}')
    target = (outdir / '_generated' / f'{top}.sv').resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')
    closure.setdefault('external_files', []).append(str(target))
    closure.setdefault('generated_files', []).append(str(target))
    # The wrapper supplies concrete types, so the original generic module and
    # its normal dependencies remain in the closure and retain provenance.
    module_names = set(re.findall(r'(?m)^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)', content))
    for edge in closure.get('unresolved', []):
        if edge.get('dependency_kind') == 'submodule' and edge.get('dependency_name') in module_names:
            edge['resolution_status'] = 'resolved_generated'
            edge['resolved_file'] = '@generated/' + target.name
    closure['external_files'] = sorted(set(closure.get('external_files', [])))
    closure['generated_files'] = sorted(set(closure.get('generated_files', [])))
    closure['closure_status'] = 'COMPLETE' if not closure.get('unresolved') else 'PARTIAL'
    return top


def add_declared_include_roots(model: RepositoryModel, source: Dict, closure: Dict,
                               primary: bool = True) -> None:
    """Seed the filelist with configured include/vendor roots.

    Static dependency discovery only adds a directory after it sees an
    include in a parsed file.  A number of generated and legacy RTL trees
    include headers indirectly (or through macro-expanded paths), so those
    roots must be present even when no direct edge was parsed.  Keep primary
    checkout paths relative and sibling-repository paths absolute, matching
    the rest of the candidate filelist format.
    """
    fields = ("include_hints", "vendor_hints")
    for field in fields:
        for raw in source.get(field, []) or []:
            rel = str(raw).replace('\\', '/').strip().strip('/')
            if not rel or rel == '.':
                continue
            path = (model.repo_dir / rel).resolve()
            # A hint may name a header rather than a directory.  In that
            # case Verilator needs the containing directory on its -I path.
            root = path.parent if path.is_file() else path
            if not root.exists():
                # Keep the configured path visible in the manifest/filelist;
                # a missing sparse path is actionable and should not silently
                # turn into an unresolved include later in the run.
                root = path
            if primary:
                closure.setdefault('include_roots', []).append(rel if root == path else str(Path(rel).parent.as_posix()))
            else:
                closure.setdefault('external_include_roots', []).append(str(root))
    closure['include_roots'] = sorted(set(closure.get('include_roots', [])))
    closure['external_include_roots'] = sorted(set(closure.get('external_include_roots', [])))


def parse_verilator_messages(text: str) -> Dict:
    """
    Parse Verilator's structured %Warning-CODE / %Error-CODE diagnostics.
    Keep raw text in lint_report as source of truth; this is a convenience index.
    """
    warning_records = []
    error_records = []

    # Examples:
    # %Warning-WIDTHTRUNC: file.sv:272:14: message...
    # %Error-MODNOTFOUND: file.sv:10:1: message...
    pat = re.compile(
        r'(?m)^%(Warning|Error)(?:-([A-Za-z0-9_]+))?:\s*(.*)$'
    )
    for m in pat.finditer(text):
        severity = m.group(1).lower()
        code = m.group(2) or "UNCLASSIFIED"
        message = m.group(3).strip()
        rec = {
            "severity": severity,
            "code": code,
            "message": message,
        }
        if severity == "warning":
            warning_records.append(rec)
        else:
            error_records.append(rec)

    def counts(records):
        out = {}
        for r in records:
            out[r["code"]] = out.get(r["code"], 0) + 1
        return dict(sorted(out.items()))

    return {
        "warning_records": warning_records,
        "error_records": error_records,
        "warning_codes": counts(warning_records),
        "error_codes": counts(error_records),
    }


def run_verilator(top_module: str, filelist: Path, outdir: Path, parameters=None, defines=None) -> Dict:
    exe = shutil.which('verilator')
    report = {
        'tool': 'verilator',
        'tool_path': exe or '',
        'tool_version': verilator_version(),
        'top_module': top_module,
        'filelist': str(filelist),
        'status': 'SKIP_TOOL_MISSING' if not exe else 'NOT_RUN',
        'returncode': None,
        'warning_count': 0,
        'error_count': 0,
        'command': [],
        'stdout': '',
        'stderr': '',
        'warning_codes': {},
        'error_codes': {},
        'warning_records': [],
        'error_records': [],
        'hard_gate': {
            'dependency_closure': 'NOT_EVALUATED',
            'verilator_compile': 'SKIP_TOOL_MISSING' if not exe else 'NOT_RUN',
            'overall': 'NOT_RUN',
        },
    }
    if not exe:
        return report

    cmd = [
        exe,
        '--lint-only',
        '--Wno-fatal',
        '--top-module', top_module,
        '-F', filelist.name,
    ]
    # Project-level preprocessor defines are part of a fixed build context
    # (for example Vortex's XLEN axis).  Keep them separate from -G
    # parameter overrides: -D affects preprocessing of packages/headers,
    # while -G elaborates a top-module parameter.
    for define in (defines or []):
        define = str(define).strip()
        if not define:
            continue
        if define.startswith('-D'):
            define = define[2:]
        cmd.append(f'-D{define}')
    for name, value in (parameters or {}).items():
        cmd += [f'-G{name}={value}']
    p = subprocess.run(cmd, cwd=outdir, text=True, capture_output=True, check=False)
    combined = (p.stdout or '') + '\n' + (p.stderr or '')
    warnings = len(re.findall(r'(?m)^%Warning', combined))
    errors = len(re.findall(r'(?m)^%Error', combined))

    parsed = parse_verilator_messages(combined)
    compile_status = 'PASS' if p.returncode == 0 else 'FAIL'
    report.update({
        'status': compile_status,
        'returncode': p.returncode,
        'warning_count': warnings,
        'error_count': errors,
        'command': cmd,
        'stdout': p.stdout or '',
        'stderr': p.stderr or '',
        'warning_codes': parsed['warning_codes'],
        'error_codes': parsed['error_codes'],
        'warning_records': parsed['warning_records'],
        'error_records': parsed['error_records'],
        'hard_gate': {
            'dependency_closure': 'NOT_EVALUATED',
            'verilator_compile': compile_status,
            'overall': compile_status,
        },
    })
    return report


def main():
    ap = argparse.ArgumentParser(description='Build one recursive RTL candidate closure and optionally run Verilator compile/lint gate')
    ap.add_argument('module', help='Exact top module, e.g. cc_rr_arb_tree')
    ap.add_argument('--project', default='pulp_common_cells')
    ap.add_argument('--sources', default='sources.json')
    ap.add_argument('--workdir', default='work')
    ap.add_argument('--candidate-root', default='candidates')
    ap.add_argument('--candidate-id', default='', help='Optional unique output directory name for batch runs')
    ap.add_argument('--param', action='append', default=[], help='Top parameter override NAME=VALUE; repeatable')
    ap.add_argument('--top-file', default='', help='Disambiguate duplicate module definitions')
    ap.add_argument('--update', action='store_true', help='Update repository before building closure')
    ap.add_argument('--lint', action='store_true', help='Run Verilator --lint-only Hard Gate')
    ap.add_argument(
        '--prune-module',
        action='append',
        default=[],
        help='Configuration-dead module dependency to prune from static closure; repeatable.'
    )
    ap.add_argument(
        '--prune-package',
        action='append',
        default=[],
        help='Configuration-dead package dependency to prune from static closure; repeatable.'
    )
    ap.add_argument(
        '--prune-include',
        action='append',
        default=[],
        help='Configuration-dead include dependency to prune from static closure; repeatable.'
    )
    args = ap.parse_args()

    base = Path.cwd()
    cfg = load_config(base / args.sources)
    candidates = [s for s in cfg.get('sources', []) if s.get('project') == args.project]
    if not candidates:
        raise SystemExit(f'Unknown project in sources config: {args.project}')
    source = candidates[0]

    repo_dir = ensure_repo(source, (base / args.workdir / 'repos').resolve(), update=args.update)
    meta = git_metadata(repo_dir)

    print(f'[model] parsing repository: {args.project}')
    model = RepositoryModel(repo_dir, source)
    print(f'[model] RTL files={len(model.rtl_files)}, modules={sum(len(v) for v in model.module_index.values())}')

    configured_prune_modules = list(source.get('prune_modules', []) or [])
    configured_prune_packages = list(source.get('prune_packages', []) or [])
    configured_prune_includes = list(source.get('prune_includes', []) or [])
    configured_defines = [str(x) for x in (source.get('defines', []) or []) if str(x).strip()]
    closure = build_dependency_closure(
        model,
        args.module,
        args.top_file,
        prune_modules=set(args.prune_module) | set(configured_prune_modules),
        prune_packages=set(args.prune_package) | set(configured_prune_packages),
        prune_includes=set(args.prune_include) | set(configured_prune_includes),
    )

    # Resolve explicitly declared sibling repositories (technology cells,
    # common-cells, vendor assertions, HardFloat, ...).  Dependencies are
    # loaded lazily and only the transitive files selected by the closure are
    # appended to candidate.f.
    dependency_models = {}
    source_by_project = {s.get('project'): s for s in cfg.get('sources', [])}
    pending = list(source.get('dependency_projects', []) or [])
    seen_projects = set()
    while pending:
        project = pending.pop(0)
        if project in seen_projects or project == args.project:
            continue
        dep_source = source_by_project.get(project)
        if not dep_source:
            continue
        seen_projects.add(project)
        dep_repo = ensure_repo(dep_source, (base / args.workdir / 'repos').resolve(), update=args.update)
        dependency_models[project] = RepositoryModel(dep_repo, dep_source)
        pending.extend(dep_source.get('dependency_projects', []) or [])
    if (
        dependency_models
        or source.get('module_overrides')
        or source.get('package_overrides')
        or source.get('include_overrides')
        or configured_prune_modules
        or configured_prune_packages
    ):
        closure = apply_dependency_overlay(
            model,
            closure,
            dependency_models,
            module_overrides=source.get('module_overrides', {}),
            package_overrides=source.get('package_overrides', {}),
            include_overrides=source.get('include_overrides', {}),
            prune_modules=set(args.prune_module) | set(configured_prune_modules),
            prune_packages=set(args.prune_package) | set(configured_prune_packages),
            prune_includes=set(args.prune_include) | set(configured_prune_includes),
        )

    # Include/vendor hints describe roots that are not always discoverable
    # from the lightweight parser (generated headers and legacy macro trees
    # are the common cases). Add primary roots as relative paths and all
    # transitive dependency roots as absolute paths before emitting candidate.f.
    add_declared_include_roots(model, source, closure, primary=True)
    for project, dep_model in dependency_models.items():
        dep_source = source_by_project.get(project, dep_model.source)
        add_declared_include_roots(dep_model, dep_source, closure, primary=False)

    output_name = args.candidate_id or args.module
    outdir = (base / args.candidate_root / safe_name(args.project) / safe_name(output_name)).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    # Add deterministic project shims (generated headers, black-box memories,
    # or vendor compatibility modules) before writing the candidate filelist.
    materialize_generated_files(source, outdir, closure, base)
    validation_top = materialize_validation_wrapper(source, args.module, outdir, closure)
    wrapper_spec = validation_wrapper_spec(source, args.module)

    # Some legacy Verilog trees keep elaboration-time outputs next to the RTL
    # as ``.v.pyv`` files. The lightweight parser intentionally ignores those
    # generated units; projects may list the small set needed by a candidate
    # here so they are still included deterministically.
    forced_files = []
    # Most forced legacy units are only valid for one top.  A global
    # ``forced_files`` list is retained for backwards compatibility, while
    # ``forced_files_by_module`` prevents unrelated candidates from inheriting
    # an OpenPiton/.v.pyv implementation (and its project-specific headers).
    forced_items = list(source.get('forced_files', []) or [])
    by_module = source.get('forced_files_by_module', {}) or {}
    forced_items.extend(by_module.get(args.module, []) or [])
    forced_items.extend(by_module.get('*', []) or [])
    for item in forced_items:
        rel = str(item).replace('\\\\', '/').lstrip('/')
        path = (repo_dir / rel).resolve()
        repo_root = repo_dir.resolve()
        if path.is_file() and (path == repo_root or repo_root in path.parents):
            forced_files.append(rel)
            if path.suffix.lower() in {'.v', '.sv', '.pyv'}:
                closure.setdefault('module_files', []).append(rel)
            closure.setdefault('include_roots', []).append(str(Path(rel).parent.as_posix()))
    closure['module_files'] = sorted(set(closure.get('module_files', [])))
    closure['include_roots'] = sorted(set(closure.get('include_roots', [])))
    closure['forced_files'] = sorted(set(forced_files))

    # Forced files are real upstream RTL selected by the fixed project
    # configuration (for example CVA6's technology SRAM wrappers).  The
    # lightweight dependency parser may not see them while walking the
    # candidate, so reconcile their module declarations with unresolved
    # submodule edges before computing the hard closure gate.  This keeps the
    # manifest truthful: a dependency is marked resolved only when the actual
    # source file is present in the generated candidate filelist.
    forced_module_files = {}
    for rel in closure['forced_files']:
        src = (repo_dir / rel).resolve()
        if src.suffix.lower() not in {'.v', '.sv'} or not src.is_file():
            continue
        try:
            text = src.read_text(encoding='utf-8', errors='replace')
        except OSError:
            continue
        for name in re.findall(r'(?m)^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)', text):
            forced_module_files.setdefault(name, rel)
    if forced_module_files:
        for edge in closure.get('unresolved', []):
            name = str(edge.get('dependency_name', ''))
            rel = forced_module_files.get(name)
            if edge.get('dependency_kind') == 'submodule' and rel:
                edge['resolution_status'] = 'resolved_forced_file'
                edge['resolved_file'] = '@forced/' + rel
        closure['unresolved'] = [
            edge for edge in closure.get('unresolved', [])
            if edge.get('resolution_status') not in {
                'resolved', 'resolved_generated', 'resolved_forced_file',
                'pruned_config_dead',
            }
        ]
        closure['closure_status'] = 'COMPLETE' if not closure['unresolved'] else 'PARTIAL'

    filelist = create_filelist(repo_dir, closure, outdir)

    manifest = {
        'schema_version': '0.3',
        'source_project': args.project,
        'repo_url': meta['remote_url'],
        'branch': meta.get('branch', ''),
        'commit_sha': meta['commit_sha'],
        'top_module': closure['top_module'],
        'validation_top': validation_top,
        'validation_wrapper': wrapper_spec or None,
        'fixed_config': source.get('fixed_config'),
        'verification_dependencies': source.get('verification_dependencies', {}),
        'candidate_id': args.candidate_id or args.module,
        'parameter_overrides': {},
        'defines': configured_defines,
        'top_file': closure['top_file'],
        'closure_status': closure['closure_status'],
        'module_files': closure['module_files'],
        'package_files': closure['package_files'],
        'header_files': closure['header_files'],
        'include_roots': closure['include_roots'],
        'external_files': closure.get('external_files', []),
        'external_package_files': closure.get('external_package_files', []),
        'external_include_roots': closure.get('external_include_roots', []),
        'generated_files': closure.get('generated_files', []),
        'generated_header_files': closure.get('generated_header_files', []),
        'forced_files': closure.get('forced_files', []),
        'overlay_projects': closure.get('overlay_projects', []),
        'unresolved_dependencies': closure['unresolved'],
        'parse_warnings': closure['parse_warnings'],
        'pruned_modules': closure.get('pruned_modules', []),
        'pruned_packages': closure.get('pruned_packages', []),
        'pruned_includes': closure.get('pruned_includes', []),
        'candidate_filelist': 'candidate.f',
    }
    (outdir / 'manifest.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

    write_csv(outdir / 'closure_edges.csv', closure['edges'], [
        'parent_kind','parent_name','parent_file','dependency_kind','dependency_name',
        'instance_name','resolution_status','resolved_file'
    ])

    define_flags = ' '.join(f'-D{d[2:] if str(d).startswith("-D") else d}' for d in configured_defines)
    run_script = f'''#!/usr/bin/env bash\nset -euo pipefail\ncd "$(dirname "$0")"\nverilator --lint-only --Wno-fatal --top-module {validation_top} {define_flags} -F candidate.f\n'''
    run_path = outdir / 'run_lint.sh'
    run_path.write_text(run_script, encoding='utf-8')
    run_path.chmod(0o755)

    lint_report = None
    # Start from the fixed project context, then let an explicit CLI value
    # override it for one-off experiments.  Keeping the resolved map in the
    # manifest makes the exact Verilator/Yosys elaboration reproducible.
    parameters = configured_parameter_overrides(source, args.module)
    for item in args.param:
        if '=' not in item:
            raise SystemExit(f'--param expects NAME=VALUE, got {item!r}')
        name, value = item.split('=', 1)
        parameters[name] = value
    manifest['parameter_overrides'] = parameters
    (outdir / 'manifest.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

    if args.lint:
        # In a typed validation wrapper the wrapper owns the concrete DUT
        # parameters; forwarding crawler-inferred parameters to the wrapper
        # itself would address non-existent top-level parameters.
        lint_parameters = parameters if validation_top == args.module else {}
        lint_report = run_verilator(validation_top, filelist, outdir, lint_parameters, configured_defines)
        closure_gate = 'PASS' if closure['closure_status'] == 'COMPLETE' else 'FAIL'
        compile_gate = lint_report['status']
        if compile_gate == 'SKIP_TOOL_MISSING':
            overall_gate = 'SKIP_TOOL_MISSING'
        else:
            overall_gate = 'PASS' if (closure_gate == 'PASS' and compile_gate == 'PASS') else 'FAIL'
        lint_report['hard_gate'] = {
            'dependency_closure': closure_gate,
            'verilator_compile': compile_gate,
            'overall': overall_gate,
        }
        (outdir / 'lint_report.json').write_text(json.dumps(lint_report, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

        gate_report = {
            'schema_version': '0.3.1',
            'source_project': args.project,
            'commit_sha': meta['commit_sha'],
            'top_module': args.module,
            'validation_top': validation_top,
            'top_file': closure['top_file'],
            'hard_gate': lint_report['hard_gate'],
            'closure_status': closure['closure_status'],
            'unresolved_dependency_count': len(closure['unresolved']),
            'verilator_version': lint_report['tool_version'],
            'verilator_returncode': lint_report['returncode'],
            'warning_count': lint_report['warning_count'],
            'error_count': lint_report['error_count'],
            'warning_codes': lint_report['warning_codes'],
            'error_codes': lint_report['error_codes'],
        }
        (outdir / 'hard_gate_report.json').write_text(
            json.dumps(gate_report, indent=2, ensure_ascii=False) + '\n',
            encoding='utf-8'
        )

    print('\n=== Candidate Build ===')
    print('project          :', args.project)
    print('top_module       :', args.module)
    print('top_file         :', closure['top_file'])
    print('closure_status   :', closure['closure_status'])
    print('module_files     :', len(closure['module_files']))
    print('package_files    :', len(closure['package_files']))
    print('header_files     :', len(closure['header_files']))
    print('include_roots    :', ';'.join(closure['include_roots']) or '(none)')
    print('dependency_edges :', len(closure['edges']))
    print('unresolved       :', len(closure['unresolved']))
    print('pruned_modules   :', ';'.join(closure.get('pruned_modules', [])) or '(none)')
    print('pruned_packages  :', ';'.join(closure.get('pruned_packages', [])) or '(none)')
    print('pruned_includes  :', ';'.join(closure.get('pruned_includes', [])) or '(none)')
    print('candidate_dir    :', outdir)
    print('filelist         :', filelist)
    if lint_report is not None:
        print('\n=== Verilator Hard Gate ===')
        print('tool_version     :', lint_report['tool_version'] or '(not installed)')
        print('status           :', lint_report['status'])
        print('warnings         :', lint_report['warning_count'])
        print('errors           :', lint_report['error_count'])
        print('returncode       :', lint_report['returncode'])
        print('warning_codes    :', json.dumps(lint_report.get('warning_codes', {}), ensure_ascii=False))
        print('overall_gate     :', lint_report.get('hard_gate', {}).get('overall', lint_report['status']))
        print('report           :', outdir / 'lint_report.json')
        print('hard_gate_report :', outdir / 'hard_gate_report.json')


if __name__ == '__main__':
    main()
