#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Dict, List, Tuple

import yaml

from synth_wrapper import generate_wrapper


def run(cmd, cwd=None):
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def yosys_version():
    exe = shutil.which("yosys")
    if not exe:
        return ""
    p = run([exe, "-V"])
    return (p.stdout or p.stderr).strip()


def parse_candidate_filelist(filelist: Path) -> Tuple[List[Path], List[Path]]:
    """
    candidate.f is a Verilator -F file generated by v0.3.
    Convert it into absolute source/include paths for Yosys.
    """
    srcs = []
    incs = []
    base = filelist.parent
    for raw in filelist.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("#"):
            continue
        if line.startswith("-I"):
            p = Path(line[2:])
            incs.append((base / p).resolve())
        elif line.startswith("-"):
            # v0.5 deliberately ignores Verilator-specific flags not needed by Yosys.
            continue
        else:
            srcs.append((base / line).resolve())
    return srcs, incs


def yosys_quote(path: Path) -> str:
    # Yosys script string quoting for paths with spaces.
    s = str(path).replace("\\", "/").replace('"', '\\"')
    return f'"{s}"'


def yosys_has_read_slang(yosys: str) -> bool:
    p = run([yosys, "-Q", "-p", "help read_slang"])
    text = (p.stdout or "") + "\n" + (p.stderr or "")
    return p.returncode == 0 and "read_slang" in text and "No such command" not in text


def make_read_command(
    srcs: List[Path],
    incs: List[Path],
    wrapper: Path,
    frontend: str,
    defines=None,
) -> str:
    defines = list(defines or [])
    if frontend == "slang":
        # Important: read_slang forwards arguments to the Slang command-line
        # parser. Literal double quotes embedded in the Yosys script can become
        # part of the path seen by Slang. For our normalized project paths
        # (which contain no whitespace), pass plain POSIX paths here.
        def slang_path(p: Path) -> str:
            s = str(p).replace("\\", "/")
            if any(ch.isspace() for ch in s):
                raise ValueError(
                    "v0.5.2 read_slang path contains whitespace; "
                    "move the project to a path without spaces or extend the "
                    "file-list escaping layer."
                )
            return s

        args = [
            "read_slang",
            "--std", "1800-2023",
            "--single-unit",
        ]
        for inc in incs:
            args += ["-I", slang_path(inc)]
        for define in defines:
            args += [f"-D{define}"]
        args += [slang_path(p) for p in srcs]
        args.append(slang_path(wrapper))
        args += ["--top", "pyc_synth_top"]
        return " ".join(args)

    if frontend == "native":
        args = ["read_verilog", "-sv"]
        for inc in incs:
            args += ["-I", yosys_quote(inc)]
        for define in defines:
            args += [f"-D{define}"]
        args += [yosys_quote(p) for p in srcs]
        args.append(yosys_quote(wrapper))
        return " ".join(args)

    raise ValueError(f"Unknown frontend: {frontend}")


def write_generic_script(srcs, incs, wrapper, case_dir, frontend, defines=None):
    stat_json = case_dir / "generic_stat.json"
    cmos_log = case_dir / "cmos_stat.log"
    ltp_log = case_dir / "ltp.log"
    netlist_json = case_dir / "generic_netlist.json"
    netlist_v = case_dir / "generic_netlist.v"

    script = f"""
{make_read_command(srcs, incs, wrapper, frontend, defines)}
hierarchy -check -top pyc_synth_top
synth -top pyc_synth_top -flatten

# Strip verification/formal cells before QoR accounting.
chformal -remove
opt_clean

tee -o {yosys_quote(stat_json)} stat -json -top pyc_synth_top
tee -o {yosys_quote(cmos_log)} stat -tech cmos -top pyc_synth_top
tee -o {yosys_quote(ltp_log)} ltp -noff
write_json {yosys_quote(netlist_json)}
write_verilog -noattr -simple-lhs {yosys_quote(netlist_v)}
"""
    path = case_dir / "generic.ys"
    path.write_text(textwrap_dedent(script), encoding="utf-8")
    return path


def write_liberty_script(srcs, incs, wrapper, case_dir, liberty: Path, frontend, defines=None):
    stat_json = case_dir / "liberty_stat.json"
    netlist_v = case_dir / "mapped_netlist.v"

    script = f"""
{make_read_command(srcs, incs, wrapper, frontend, defines)}
hierarchy -check -top pyc_synth_top
synth -top pyc_synth_top -flatten

# Formal/assertion cells are not implementation hardware.
chformal -remove
opt_clean

dfflibmap -liberty {yosys_quote(liberty)}
abc -liberty {yosys_quote(liberty)}
clean
tee -o {yosys_quote(stat_json)} stat -json -liberty {yosys_quote(liberty)} -top pyc_synth_top
write_verilog -noattr -simple-lhs {yosys_quote(netlist_v)}
"""
    path = case_dir / "liberty.ys"
    path.write_text(textwrap_dedent(script), encoding="utf-8")
    return path


def textwrap_dedent(s):
    import textwrap
    return textwrap.dedent(s).lstrip()


def extract_json(path: Path):
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8", errors="ignore").strip()
    # Some Yosys builds may surround the JSON with log text. Extract the widest object.
    a = text.find("{")
    b = text.rfind("}")
    if a < 0 or b < a:
        return {}
    try:
        return json.loads(text[a:b+1])
    except Exception:
        return {}


def module_stats(stat_obj: Dict) -> Dict:
    mods = stat_obj.get("modules", {})
    if not isinstance(mods, dict) or not mods:
        return {}
    for k in ("\\pyc_synth_top", "pyc_synth_top"):
        if k in mods:
            return mods[k]
    # flattened synth usually leaves a single top module
    return next(iter(mods.values()))


def parse_ltp(path: Path):
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8", errors="ignore")
    patterns = [
        r"length\s*=\s*(\d+)",
        r"length\s+(\d+)",
    ]
    vals = []
    for pat in patterns:
        vals += [int(x) for x in re.findall(pat, text, flags=re.I)]
    return max(vals) if vals else None


def find_area(obj):
    """
    stat -json -liberty schemas vary by Yosys version.
    Recursively search numeric fields whose key contains 'area'.
    """
    hits = []
    def rec(x, path=""):
        if isinstance(x, dict):
            for k, v in x.items():
                kp = f"{path}.{k}" if path else str(k)
                if "area" in str(k).lower() and isinstance(v, (int, float)):
                    hits.append((kp, float(v)))
                rec(v, kp)
        elif isinstance(x, list):
            for i, v in enumerate(x):
                rec(v, f"{path}[{i}]")
    rec(obj)
    return hits[0][1] if hits else None


def flatten_metrics(stat_obj: Dict):
    m = module_stats(stat_obj)
    return {
        "num_wires": m.get("num_wires"),
        "num_wire_bits": m.get("num_wire_bits"),
        "num_cells": m.get("num_cells"),
        "num_processes": m.get("num_processes"),
        "num_memories": m.get("num_memories"),
        "num_memory_bits": m.get("num_memory_bits"),
        "cell_types": m.get("num_cells_by_type", m.get("cell_types", {})),
    }


def main():
    ap = argparse.ArgumentParser(description="pyCircuit Yosys Synthesis/QoR Harness v0.5.2")
    ap.add_argument("module", choices=["cc_lzc", "cc_popcount", "cc_rr_arb_tree"])
    ap.add_argument("--profile", choices=["smoke", "standard", "scaling"], default="standard")
    ap.add_argument("--project", default="pulp_common_cells")
    ap.add_argument("--specs", default="synthesis_specs.yaml")
    ap.add_argument("--candidate-root", default="candidates")
    ap.add_argument("--output-root", default="synthesis_results")
    ap.add_argument("--liberty", default="", help="Optional Liberty .lib for mapped cell area")
    ap.add_argument(
        "--frontend",
        choices=["auto", "slang", "native"],
        default="auto",
        help="SystemVerilog frontend. auto prefers read_slang and falls back to native.",
    )
    args = ap.parse_args()

    base = Path.cwd()
    yosys = shutil.which("yosys")
    if not yosys:
        raise SystemExit("Yosys not found. Run `yosys -V` after installing Yosys/OSS CAD Suite.")

    slang_available = yosys_has_read_slang(yosys)
    if args.frontend == "auto":
        frontend = "slang" if slang_available else "native"
    elif args.frontend == "slang":
        if not slang_available:
            raise SystemExit(
                "Requested --frontend slang, but `read_slang` is unavailable in this Yosys build."
            )
        frontend = "slang"
    else:
        frontend = "native"

    specs = yaml.safe_load((base / args.specs).read_text(encoding="utf-8"))
    configs = specs["profiles"][args.profile][args.module]

    cand = base / args.candidate_root / args.project / args.module
    filelist = cand / "candidate.f"
    if not filelist.exists():
        raise SystemExit(f"Missing {filelist}; copy/build candidate first.")

    gate = cand / "hard_gate_report.json"
    if gate.exists():
        g = json.loads(gate.read_text(encoding="utf-8"))
        overall = g.get("hard_gate", {}).get("overall")
        if overall and overall != "PASS":
            raise SystemExit(f"Compile Hard Gate prerequisite is {overall}, not PASS.")

    srcs, incs = parse_candidate_filelist(filelist)
    liberty = Path(args.liberty).expanduser().resolve() if args.liberty else None
    if liberty and not liberty.exists():
        raise SystemExit(f"Liberty file not found: {liberty}")

    out_root = base / args.output_root / args.project / args.module / args.profile
    out_root.mkdir(parents=True, exist_ok=True)

    print("=== pyCircuit Yosys Synthesis/QoR v0.5.2 ===")
    print("module        :", args.module)
    print("profile       :", args.profile)
    print("configs       :", len(configs))
    print("yosys         :", yosys_version())
    print("frontend      :", frontend)
    print("read_slang    :", "available" if slang_available else "unavailable")
    print("liberty       :", liberty or "(none; generic QoR only)")
    print()

    results = []
    for i, cfg in enumerate(configs):
        case_dir = out_root / cfg["name"]
        if case_dir.exists():
            shutil.rmtree(case_dir)
        case_dir.mkdir(parents=True)

        wrapper = case_dir / "synth_top.sv"
        wrapper.write_text(generate_wrapper(args.module, cfg), encoding="utf-8")

        generic_script = write_generic_script(srcs, incs, wrapper, case_dir, frontend)
        print(f"[case {i+1}/{len(configs)}] {cfg['name']} {cfg}")

        t0 = time.time()
        gp = run([yosys, "-s", str(generic_script)], cwd=case_dir)
        generic_seconds = time.time() - t0
        (case_dir / "yosys_generic_stdout.log").write_text(gp.stdout or "", encoding="utf-8")
        (case_dir / "yosys_generic_stderr.log").write_text(gp.stderr or "", encoding="utf-8")

        result = {
            "name": cfg["name"],
            "config": cfg,
            "frontend": frontend,
            "generic_status": "PASS" if gp.returncode == 0 else "FAIL",
            "generic_returncode": gp.returncode,
            "generic_seconds": round(generic_seconds, 4),
            "logic_depth": None,
            "liberty_status": "NOT_REQUESTED" if not liberty else "NOT_RUN",
            "liberty_area": None,
        }

        if gp.returncode == 0:
            stat = extract_json(case_dir / "generic_stat.json")
            result.update(flatten_metrics(stat))
            result["logic_depth"] = parse_ltp(case_dir / "ltp.log")
        else:
            result.update({
                "num_wires": None, "num_wire_bits": None, "num_cells": None,
                "num_processes": None, "num_memories": None, "num_memory_bits": None,
                "cell_types": {},
            })

        if liberty and gp.returncode == 0:
            lib_script = write_liberty_script(srcs, incs, wrapper, case_dir, liberty, frontend)
            t1 = time.time()
            lp = run([yosys, "-s", str(lib_script)], cwd=case_dir)
            result["liberty_seconds"] = round(time.time() - t1, 4)
            result["liberty_status"] = "PASS" if lp.returncode == 0 else "FAIL"
            result["liberty_returncode"] = lp.returncode
            (case_dir / "yosys_liberty_stdout.log").write_text(lp.stdout or "", encoding="utf-8")
            (case_dir / "yosys_liberty_stderr.log").write_text(lp.stderr or "", encoding="utf-8")
            if lp.returncode == 0:
                lib_stat = extract_json(case_dir / "liberty_stat.json")
                result["liberty_area"] = find_area(lib_stat)

        (case_dir / "synthesis_case_report.json").write_text(
            json.dumps(result, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8"
        )
        results.append(result)

        print("  ->", result["generic_status"],
              "cells=", result.get("num_cells"),
              "depth=", result.get("logic_depth"),
              "area=", result.get("liberty_area"))

    overall = "PASS" if all(r["generic_status"] == "PASS" for r in results) else "FAIL"
    if liberty and any(r["liberty_status"] != "PASS" for r in results):
        overall = "PARTIAL" if any(r["generic_status"] == "PASS" for r in results) else "FAIL"

    report = {
        "schema_version": "0.5.2",
        "module": args.module,
        "project": args.project,
        "profile": args.profile,
        "yosys_version": yosys_version(),
        "frontend": frontend,
        "read_slang_available": slang_available,
        "liberty": str(liberty) if liberty else "",
        "synthesis_gate": overall,
        "configuration_count": len(results),
        "configuration_generic_pass_count": sum(r["generic_status"] == "PASS" for r in results),
        "cases": results,
        "metric_semantics": {
            "num_cells": "Yosys generic synthesized cell count; compare only under the same tool/version/flow.",
            "logic_depth": "Yosys ltp longest topological path after flattening; timing proxy, not Fmax.",
            "liberty_area": "Mapped standard-cell area when a Liberty file is supplied; still pre-place-and-route.",
            "power": "Not measured in v0.5."
        }
    }
    rp = out_root / "synthesis_report.json"
    rp.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Convenient CSV for spreadsheet/ranking later.
    csv_path = out_root / "synthesis_summary.csv"
    fields = [
        "name","frontend","generic_status","num_cells","num_wires","num_wire_bits",
        "logic_depth","liberty_status","liberty_area","generic_seconds"
    ]
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(results)

    print()
    print("=== Synthesis Gate ===")
    print("status         :", overall)
    print("generic_pass   :", f"{report['configuration_generic_pass_count']}/{len(results)}")
    print("report         :", rp)
    print("summary_csv    :", csv_path)
    raise SystemExit(0 if overall in ("PASS", "PARTIAL") else 1)


if __name__ == "__main__":
    main()
