
from __future__ import annotations

from typing import Dict


def _header(module: str, config: Dict, seed: int) -> str:
    return f"""// Auto-generated by pyCircuit RTL Correctness Harness v0.4
// DUT: {module}
// Config: {config}
// Seed: {seed}
`timescale 1ns/1ps
"""


def gen_lzc(config: Dict, seed: int) -> str:
    width = int(config["width"])
    mode = str(config["mode"]).lower()
    random_tests = int(config.get("random_tests", 256))
    if width < 2:
        raise ValueError("v0.4 cc_lzc tests Width >= 2; Width=1 corner case is deferred.")
    if mode not in ("leading", "trailing"):
        raise ValueError("mode must be leading or trailing")
    mode_expr = (
        "cc_pkg::LZC_LEADING_ZERO_CNT"
        if mode == "leading"
        else "cc_pkg::LZC_TRAILING_ZERO_CNT"
    )
    lead = "1'b1" if mode == "leading" else "1'b0"

    return _header("cc_lzc", config, seed) + f"""
module tb;
  localparam int unsigned WIDTH = {width};
  localparam int unsigned CNT_W = cc_pkg::idx_width(WIDTH);
  localparam int unsigned RANDOM_TESTS = {random_tests};
  localparam bit LEADING = {lead};

  logic [WIDTH-1:0] in_i;
  logic [CNT_W-1:0] cnt_o;
  logic empty_o;

  int unsigned test_count = 0;
  int unsigned error_count = 0;
  int unsigned rng_state = 32'h{seed & 0xffffffff:08x};

  cc_lzc #(
    .Width ( WIDTH ),
    .Mode  ( {mode_expr} )
  ) dut (
    .in_i    ( in_i ),
    .cnt_o   ( cnt_o ),
    .empty_o ( empty_o )
  );

  function automatic int unsigned next_rand();
    rng_state = rng_state ^ (rng_state << 13);
    rng_state = rng_state ^ (rng_state >> 17);
    rng_state = rng_state ^ (rng_state << 5);
    return rng_state;
  endfunction

  function automatic int unsigned ref_count(input logic [WIDTH-1:0] x);
    int unsigned cnt;
    bit found;
    cnt = 0;
    found = 0;
    if (x == '0) begin
      // cc_lzc documents empty separately; for Width>1 cnt_o carries Width-1.
      return WIDTH - 1;
    end

    if (LEADING) begin
      for (int i = WIDTH-1; i >= 0; i--) begin
        if (!found) begin
          if (x[i]) found = 1;
          else cnt++;
        end
      end
    end else begin
      for (int i = 0; i < WIDTH; i++) begin
        if (!found) begin
          if (x[i]) found = 1;
          else cnt++;
        end
      end
    end
    return cnt;
  endfunction

  task automatic check_vec(input logic [WIDTH-1:0] x);
    int unsigned expected_cnt;
    bit expected_empty;
    in_i = x;
    #1;
    expected_empty = (x == '0);
    expected_cnt = ref_count(x);
    test_count++;
    if ((empty_o !== expected_empty) || (cnt_o !== CNT_W'(expected_cnt))) begin
      error_count++;
      $display("FAIL cc_lzc WIDTH=%0d LEADING=%0d x=%h got(cnt=%0d empty=%0b) exp(cnt=%0d empty=%0b)",
               WIDTH, LEADING, x, cnt_o, empty_o, expected_cnt, expected_empty);
    end
  endtask

  initial begin
    // Directed corner patterns.
    check_vec('0);
    check_vec('1);

    for (int pos = 0; pos < WIDTH; pos++) begin
      logic [WIDTH-1:0] onehot;
      onehot = '0;
      onehot[pos] = 1'b1;
      check_vec(onehot);
    end

    begin
      logic [WIDTH-1:0] alt_a, alt_5;
      alt_a = '0; alt_5 = '0;
      for (int i = 0; i < WIDTH; i++) begin
        alt_a[i] = i[0];
        alt_5[i] = ~i[0];
      end
      check_vec(alt_a);
      check_vec(alt_5);
    end

    // Deterministic randomized regression.
    for (int t = 0; t < RANDOM_TESTS; t++) begin
      logic [WIDTH-1:0] x;
      for (int b = 0; b < WIDTH; b++)
        x[b] = next_rand()[0];
      check_vec(x);
    end

    if (error_count != 0) begin
      $display("PYC_CORRECTNESS_RESULT FAIL module=cc_lzc tests=%0d errors=%0d", test_count, error_count);
      $fatal(1);
    end
    $display("PYC_CORRECTNESS_RESULT PASS module=cc_lzc tests=%0d errors=0", test_count);
    $finish;
  end
endmodule
"""


def gen_popcount(config: Dict, seed: int) -> str:
    width = int(config["width"])
    random_tests = int(config.get("random_tests", 256))
    if width < 1:
        raise ValueError("width must be >= 1")

    return _header("cc_popcount", config, seed) + f"""
module tb;
  localparam int unsigned WIDTH = {width};
  localparam int unsigned OUT_W = $clog2(WIDTH + 1);
  localparam int unsigned RANDOM_TESTS = {random_tests};

  logic [WIDTH-1:0] data_i;
  logic [OUT_W-1:0] popcount_o;

  int unsigned test_count = 0;
  int unsigned error_count = 0;
  int unsigned rng_state = 32'h{seed & 0xffffffff:08x};

  cc_popcount #(
    .InputWidth ( WIDTH )
  ) dut (
    .data_i     ( data_i ),
    .popcount_o ( popcount_o )
  );

  function automatic int unsigned next_rand();
    rng_state = rng_state ^ (rng_state << 13);
    rng_state = rng_state ^ (rng_state >> 17);
    rng_state = rng_state ^ (rng_state << 5);
    return rng_state;
  endfunction

  function automatic int unsigned ref_popcount(input logic [WIDTH-1:0] x);
    int unsigned n;
    n = 0;
    for (int i = 0; i < WIDTH; i++)
      n += x[i];
    return n;
  endfunction

  task automatic check_vec(input logic [WIDTH-1:0] x);
    int unsigned expected;
    data_i = x;
    #1;
    expected = ref_popcount(x);
    test_count++;
    if (popcount_o !== OUT_W'(expected)) begin
      error_count++;
      $display("FAIL cc_popcount WIDTH=%0d x=%h got=%0d exp=%0d",
               WIDTH, x, popcount_o, expected);
    end
  endtask

  initial begin
    check_vec('0);
    check_vec('1);

    for (int pos = 0; pos < WIDTH; pos++) begin
      logic [WIDTH-1:0] onehot;
      onehot = '0;
      onehot[pos] = 1'b1;
      check_vec(onehot);
    end

    for (int t = 0; t < RANDOM_TESTS; t++) begin
      logic [WIDTH-1:0] x;
      for (int b = 0; b < WIDTH; b++)
        x[b] = next_rand()[0];
      check_vec(x);
    end

    if (error_count != 0) begin
      $display("PYC_CORRECTNESS_RESULT FAIL module=cc_popcount tests=%0d errors=%0d", test_count, error_count);
      $fatal(1);
    end
    $display("PYC_CORRECTNESS_RESULT PASS module=cc_popcount tests=%0d errors=0", test_count);
    $finish;
  end
endmodule
"""


def gen_rr_arb_extprio(config: Dict, seed: int) -> str:
    num_in = int(config["num_in"])
    data_width = int(config.get("data_width", 16))
    random_tests = int(config.get("random_tests", 256))
    if num_in < 2:
        raise ValueError("v0.4 rr_arb_extprio starts at NumIn >= 2")
    idx_w = max(1, (num_in - 1).bit_length())

    return _header("cc_rr_arb_tree", config, seed) + f"""
module tb;
  localparam int unsigned NUM_IN = {num_in};
  localparam int unsigned DATA_W = {data_width};
  localparam int unsigned IDX_W = {idx_w};
  localparam int unsigned RANDOM_TESTS = {random_tests};

  logic clk_i;
  logic rst_ni;
  logic clr_i;
  logic [IDX_W-1:0] rr_i;
  logic [NUM_IN-1:0] req_i;
  logic [NUM_IN-1:0] gnt_o;
  logic [NUM_IN-1:0][DATA_W-1:0] data_i;
  logic req_o;
  logic gnt_i;
  logic [DATA_W-1:0] data_o;
  logic [IDX_W-1:0] idx_o;

  int unsigned test_count = 0;
  int unsigned error_count = 0;
  int unsigned rng_state = 32'h{seed & 0xffffffff:08x};

  cc_rr_arb_tree #(
    .NumIn      ( NUM_IN ),
    .DataWidth  ( DATA_W ),
    .ExtPrio    ( 1'b1 ),
    .AxiVldRdy  ( 1'b0 ),
    .LockIn     ( 1'b0 ),
    .FairArb    ( 1'b1 )
  ) dut (
    .clk_i  ( clk_i ),
    .rst_ni ( rst_ni ),
    .clr_i  ( clr_i ),
    .rr_i   ( rr_i ),
    .req_i  ( req_i ),
    .gnt_o  ( gnt_o ),
    .data_i ( data_i ),
    .req_o  ( req_o ),
    .gnt_i  ( gnt_i ),
    .data_o ( data_o ),
    .idx_o  ( idx_o )
  );

  function automatic int unsigned next_rand();
    rng_state = rng_state ^ (rng_state << 13);
    rng_state = rng_state ^ (rng_state >> 17);
    rng_state = rng_state ^ (rng_state << 5);
    return rng_state;
  endfunction

  // Independent reference:
  // the arbitration tree prefers at each binary-tree level the branch
  // selected by the corresponding rr_i bit if that branch contains a request.
  // Equivalently, among active request indices, select minimum (index XOR rr_i).
  function automatic int expected_winner(
    input logic [NUM_IN-1:0] req,
    input int unsigned rr
  );
    int win;
    int unsigned best_metric;
    bit found;
    win = 0;
    best_metric = '1;
    found = 0;
    for (int i = 0; i < NUM_IN; i++) begin
      if (req[i]) begin
        int unsigned metric;
        metric = i ^ rr;
        if (!found || metric < best_metric) begin
          found = 1;
          best_metric = metric;
          win = i;
        end
      end
    end
    return win;
  endfunction

  task automatic load_data();
    for (int i = 0; i < NUM_IN; i++)
      data_i[i] = DATA_W'((i * 17) + 3);
  endtask

  task automatic check_case(
    input logic [NUM_IN-1:0] req,
    input int unsigned rr,
    input bit grant_in
  );
    int win;
    logic [NUM_IN-1:0] expected_gnt;
    req_i = req;
    rr_i = IDX_W'(rr);
    gnt_i = grant_in;
    #1;
    test_count++;

    expected_gnt = '0;

    if (req == '0) begin
      if (req_o !== 1'b0) begin
        error_count++;
        $display("FAIL rr_arb empty req_o=%0b", req_o);
      end
      if (gnt_o !== '0) begin
        error_count++;
        $display("FAIL rr_arb empty gnt_o=%b", gnt_o);
      end
    end else begin
      win = expected_winner(req, rr);
      if (grant_in)
        expected_gnt[win] = 1'b1;

      if (req_o !== 1'b1) begin
        error_count++;
        $display("FAIL rr_arb req_o req=%b rr=%0d", req, rr);
      end
      if (idx_o !== IDX_W'(win)) begin
        error_count++;
        $display("FAIL rr_arb idx req=%b rr=%0d got=%0d exp=%0d",
                 req, rr, idx_o, win);
      end
      if (data_o !== data_i[win]) begin
        error_count++;
        $display("FAIL rr_arb data req=%b rr=%0d got=%h exp=%h",
                 req, rr, data_o, data_i[win]);
      end
      if (gnt_o !== expected_gnt) begin
        error_count++;
        $display("FAIL rr_arb gnt req=%b rr=%0d gnt_i=%0b got=%b exp=%b",
                 req, rr, grant_in, gnt_o, expected_gnt);
      end
    end
  endtask

  initial begin
    clk_i = 1'b0;
    rst_ni = 1'b1;
    clr_i = 1'b0;
    req_i = '0;
    rr_i = '0;
    gnt_i = 1'b0;
    load_data();
    #1;

    // Directed: empty, one-hot and multi-request patterns across all legal rr_i.
    for (int rr = 0; rr < NUM_IN; rr++) begin
      check_case('0, rr, 1'b0);
      check_case('0, rr, 1'b1);
      for (int pos = 0; pos < NUM_IN; pos++) begin
        logic [NUM_IN-1:0] onehot;
        onehot = '0;
        onehot[pos] = 1'b1;
        check_case(onehot, rr, 1'b0);
        check_case(onehot, rr, 1'b1);
      end
      check_case('1, rr, 1'b1);
    end

    // Exhaustive request patterns for small arbiters.
    if (NUM_IN <= 5) begin
      for (int rr = 0; rr < NUM_IN; rr++) begin
        for (int mask = 0; mask < (1 << NUM_IN); mask++) begin
          check_case(NUM_IN'(mask), rr, 1'b1);
        end
      end
    end

    // Deterministic randomized regression.
    for (int t = 0; t < RANDOM_TESTS; t++) begin
      logic [NUM_IN-1:0] req;
      int unsigned rr;
      bit grant_in;
      for (int i = 0; i < NUM_IN; i++)
        req[i] = next_rand()[0];
      rr = next_rand() % NUM_IN;
      grant_in = next_rand()[0];
      check_case(req, rr, grant_in);
    end

    if (error_count != 0) begin
      $display("PYC_CORRECTNESS_RESULT FAIL module=cc_rr_arb_tree tests=%0d errors=%0d", test_count, error_count);
      $fatal(1);
    end
    $display("PYC_CORRECTNESS_RESULT PASS module=cc_rr_arb_tree tests=%0d errors=0", test_count);
    $finish;
  end
endmodule
"""


GENERATORS = {
    "lzc": gen_lzc,
    "popcount": gen_popcount,
    "rr_arb_extprio": gen_rr_arb_extprio,
}


def generate(adapter: str, config: Dict, seed: int) -> str:
    if adapter not in GENERATORS:
        raise KeyError(f"Unsupported correctness adapter: {adapter}")
    return GENERATORS[adapter](config, seed)
